### ISSUE TITLE
hi, thanks for sharing! I just ran and had some problems with lio-sam

### ISSUE THREAD

**Issue by hunkyu** [TixiaoShan/LIO-SAM#1]
The data set I used is caual_walk.bag and it looks like the location is not updated
![2020-07-03 10-51-10 的屏幕截图](https://user-images.githubusercontent.com/20533364/86427061-c976e380-bd1b-11ea-802b-46bf9cb35a57.png)

**Comment by YuehChuan** [comment]
I use it without problem. 
Great job, Sweet!

**Comment by YuehChuan** [comment]
you need to install 
sudo apt install libparmetis-dev
use caual_walk.bag

terminal#1 **roscore**
terminal#2 **rosbag play --clock -l casual_walk.bag** 

terminal#3 **roslaunch lio_sam run.launch**
**Enjoy!**

**Comment by TixiaoShan** [comment]
> you need to install
> sudo apt install libparmetis-dev
> use caual_walk.bag
> 
> terminal#1 **roscore**
> terminal#2 **rosbag play --clock -l casual_walk.bag**
> 
> terminal#3 **roslaunch lio_sam run.launch**
> **Enjoy!**

@YuehChuan 

I am curious why just playing the bag doesn’t work.

**Comment by YuehChuan** [comment]
@TixiaoShan  I thought the bag will come to the end soon, It fact we should do it in speed run.
 I just want to reply  hunkyu how I made it.  Fixed.  Thanks for remind!   
terminal#1 **roscore**
terminal#2 **rosbag play casual_walk.bag -r 3**
terminal#3 **roslaunch lio_sam run.launch**

**Comment by hunkyu** [comment]
I just made rosbag *.bag -r 3 according to your method, but still the same, I don’t know why! I use ubuntu 18.04. The develop branch used by gtsam @TixiaoShan @YuehChuan

**Comment by hunkyu** [comment]
![2020-07-04 01-28-24 的屏幕截图](https://user-images.githubusercontent.com/20533364/86489076-bacd1280-bd95-11ea-950d-813c4bd293e8.png)
I just made rosbag *.bag -r 3 according to your method, but still the same, I don’t know why! I use ubuntu 18.04. The develop branch used by gtsam @TixiaoShan @YuehChuan

**Comment by TixiaoShan** [comment]
@hunkyu 
It’s a gtsam problem. Have you tried the version mentioned in the readme?

**Comment by YuehChuan** [comment]
@hunkyu I encountered this issue at first, too,  could you check whether you already install
 **sudo apt install libparmetis-dev** ?

**Comment by hunkyu** [comment]
@TixiaoShan Thank you! It is indeed a gtsam version problem
