### ISSUE TITLE
Large velocity with ouster example bag

### ISSUE THREAD

**Issue by JimmyFroost** [TixiaoShan/LIO-SAM#100]
Hi,

First, let me thank you for sharing your great work !

I am new to this slam environment using ROS, so I don't get all parameters right... I have a few ouster OS1-16 rosbags of my own but I want to see how things work with available files here.
I managed to play casualWalk.bag without any problem. Then I made every specified modifications for the Ouster bag but when I play it , I get this  when using **/imu_correct**  in params.yaml: 

![image](https://user-images.githubusercontent.com/50022505/92392623-d69abf00-f11e-11ea-9ba1-8eb6df3e1998.png)

with the message 
 
> 
 [ WARN] [1599483814.228653537]: Large velocity, reset IMU-preintegration!
 
Then I used **/imu_raw** and I get this weird trajectory :

![image](https://user-images.githubusercontent.com/50022505/92393735-a3f1c600-f120-11ea-9de5-2e7fce413a1d.png)

What should I do so that the rosbag can be properly played ?

**Comment by TixiaoShan** [comment]
Since you are using your own bag, you should change the extrinsics according to your own setup.

**Comment by JimmyFroost** [comment]
Yes I understand that, but the pictures I show are from the test using the Ouster bags you provided. I would like to see this one work first.

Thanks

**Comment by TixiaoShan** [comment]
I just tested the Ouster dataset, it works fine. Some parameters are not set up correctly probably. There is a section in [README](https://github.com/TixiaoShan/LIO-SAM#other-notes) named **Ouster lidar** explains the parameter settings.

**Comment by JimmyFroost** [comment]
you're right, I had some forgotten parameters that still needed to be modified, all is well now.
Thanks again for you time.
