### ISSUE TITLE
confusion about the use of GPS

### ISSUE THREAD

**Issue by Gaochao-hit** [TixiaoShan/LIO-SAM#102]
![rosgraph](https://user-images.githubusercontent.com/36912878/92434138-a8c28280-f1d1-11ea-840a-d37d5a60b2c7.png)
Hello, I am confused by the use of GPS. the /navsat node transform the GPS inforamtion into local coordinate. What is the function of node /ekfgps. What's the difference of /imu_raw and /imu_correct,? magnetic_declination?

**Comment by Gaochao-hit** [comment]
<joint name="imu_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="imu_link" />
    <origin xyz="0 -0.1 0" rpy="${PI} 0 ${PI}" />
  </joint>
can you also tell me why the relative transformation of imu and chassis is set like this?

**Comment by TixiaoShan** [comment]
That parameter is deprecated and not used anymore. The EKF takes in imu_correct, which is just a transformation with an identity matrix.

**Comment by Gaochao-hit** [comment]
> That parameter is deprecated and not used anymore. The EKF takes in imu_correct, which is just a transformation with an identity matrix.

Why the magnetic_declination is set zero ? The output of IMU has considered it ?

**Comment by TixiaoShan** [comment]
It's parameter decided by the user. You can set it to any number you like.
