### ISSUE TITLE
Large velocity nosie form imuPreintegration node? 

### ISSUE THREAD

**Issue by shibowing** [TixiaoShan/LIO-SAM#104]
Hi Tixiao, 

Thank you very much for sharing! This is really great work!

I just tested your code and noticed that the velocity you estimated is larger than the one estimated by the original loam, which will be difficult for the drone controller to use. Could you please give me some suggestions on how to reduce the velocity noise?

The red line is LIO-SAM and the blue line is the LOAM algorithm. It can be seen that the red line is not very smooth and has a big noise compared with the blue one.

![image](https://user-images.githubusercontent.com/29483569/92525724-58a7e800-f1f2-11ea-9571-dfa4f87e11ea.png)

![image](https://user-images.githubusercontent.com/29483569/92538541-f1e3f800-f20c-11ea-8d78-0cf0c79b0b10.png)

Thank you very much for your suggestions!

**Comment by TixiaoShan** [comment]
How is the velocity calculated from the original loam? Is a filter used there?

**Comment by rcabg** [comment]
I think that probably my problem is related. I'm using LIO-SAM with an UAV too and I'm getting a really choppy odometry, both position and velocity. For instance, here is the Y axis:

![y_axis](https://user-images.githubusercontent.com/15802231/93564464-0309d300-f98a-11ea-85fd-028ada950aae.png)
(**red**: '/odometry/imu/twist/linear/y'; **orange**: '/odometry/imu/pose/position/y'; **green**: vicon ground truth)

This is making the UAV really difficult to control, almost impossible. I am trying to filter it, but still I get still a choppy signal.

Also, I realized that the "saw shape" signal evolves in the direction of the signal sign, for instance:

- Possitive:
![saw_pos_sign](https://user-images.githubusercontent.com/15802231/93565869-5715b700-f98c-11ea-872f-9678667cd620.png)
(**red**: '/odometry/imu/twist/linear/y'; **orange**: '/odometry/imu/pose/position/y'; **green**: vicon ground truth)

- Negative:
![saw_neg_sign](https://user-images.githubusercontent.com/15802231/93565893-6268e280-f98c-11ea-9dcc-8a1555f201cf.png)
(**red**: '/odometry/imu/twist/linear/y'; **orange**: '/odometry/imu/pose/position/y'; **green**: vicon ground truth)

I'm not sure, but my feeling is that the speed estimation is higher than it actually is, causing this "saw" to appear. Maybe it is related to the IMU pre-integration? 

Any ideas?

Thanks!

**Comment by TixiaoShan** [comment]
@rcabg @shibowing 
[Can you try this version of LIO-SAM? ](https://github.com/TixiaoShan/LIO-SAM/tree/a7a5117d6bd983f9aec427e6b39f02ec35fb7968)I changed how imuPreintegration.cpp works in the latest commit. I am not sure whether I introduced some bugs or not.

**Comment by rcabg** [comment]
Hello @TixiaoShan 

Thanks for the response. It definitely improves a lot the odometry reducing noise.

Here some examples:

![ex1](https://user-images.githubusercontent.com/15802231/93884180-da177400-fce2-11ea-9570-07057c701343.png)
![ex2](https://user-images.githubusercontent.com/15802231/93884192-ddaafb00-fce2-11ea-8560-a65e16ad95b2.png)
(**pink**: last commit; **red**: old commit)

![ex3](https://user-images.githubusercontent.com/15802231/93884314-08954f00-fce3-11ea-9441-dcedd22a178c.png)
(**green**: last commit; **blue**: old commit)

I didn't have enough time for analizing the code and find out what could provoke this. Any idea?

Thanks!

**Comment by TixiaoShan** [comment]
@rcabg 
So my new code introduces some bugs. Is that possible for you to share your bag with ground truth so I can debug the code? It would be great if I could test the code with the reference you have shown above.

In the new code for imu preintegration, I introduced a new lidar odometry in mapOptimization that is only incremental with drift - it doesn't change even with loop closure. So the imuPreintegration won't reset when a loop-closure happens. Thus, the imu odometry is also increamental with drift. In the old code, imuPreintegration resets everytime when a loop-closure is detected.

**Comment by shibowing** [comment]
@TixiaoShan 
Hi Tixiao, thank you very much for your reply! 
I think the issues are caused by the following piece of code.
After commenting on the code relevant to imuPreintegrationResetId, the noise of velocity is much smaller than before. However, I am confused that why you set priorVelNoise=1e4, ba.norm()>1.0 and bg.norm()>1.0 . Would you mind explaining the reasons behind it? Thank you very much!  

`        //  if (currentResetId != imuPreintegrationResetId) {
          //    resetParams();
          //  imuPreintegrationResetId = currentResetId;
          //   return;
          }`

`  priorVelNoise = gtsam::noiseModel::Isotropic::Sigma(3, 1e4); // m/s`

`  bool failureDetection(const gtsam::Vector3 &velCur,
                        const gtsam::imuBias::ConstantBias &biasCur) {
    Eigen::Vector3f vel(velCur.x(), velCur.y(), velCur.z());
    if (vel.norm() > 30) {
      ROS_WARN("Large velocity, reset IMU-preintegration!");
      return true;
    }

    Eigen::Vector3f ba(biasCur.accelerometer().x(), biasCur.accelerometer().y(),
                       biasCur.accelerometer().z());
    Eigen::Vector3f bg(biasCur.gyroscope().x(), biasCur.gyroscope().y(),
                       biasCur.gyroscope().z());
    if (ba.norm() > 1.0 || bg.norm() > 1.0 ) {
      ROS_WARN("Large bias, reset IMU-preintegration!");
      return true;
    }

    return false;
  }`

**Comment by shibowing** [comment]
From my perspespective, it seems like we don't need to reset imu preintergration frequently. Frequent reset imu-preintegration may cause the large noise of velocity. Please correct me if I am wrong. Thank you very much!

**Comment by TixiaoShan** [comment]
@shibowing 
```After commenting on the code relevant to imuPreintegrationResetId, the noise of velocity is much smaller than before.```
The ```imuPreintegrationResetId``` was used in the old code. In the old code, the odometry from imuPreintegration directly serves as the initial guess for lidar scan matching in mapOptimization. So if a loop closure happens, the robot pose will jump. We need to update the imuPreintegration with the new pose, so the scan matching won't fail due to bad initial guess (if imuPreintegration is not reset). If loop closure or GPS is disabled, imuPreintegrationResetId is not used. 

```priorVelNoise=1e4``` with a large velocity prior, we may be able to initialize the system when the car is driving at 10m/s.
```ba.norm()>1.0, bg.norm()>1.0``` I find that for a good IMU, the bias should be pretty small. So I assume the system fails when there is a large bias.

```From my perspespective, it seems like we don't need to reset imu preintergration frequently. Frequent reset imu-preintegration may cause the large noise of velocity. Please correct me if I am wrong.```
You are right. I reset the whole process every 100 step. Because this will bound the computation of a graph. If I don't reset, imuPreintegration will become slower and slower.
