### ISSUE TITLE
Question about Odom gps in rviz.

### ISSUE THREAD

**Issue by zang09** [TixiaoShan/LIO-SAM#107]
Hello.Thank you for sharing your wonderful work! I am a beginner.
I have some questions about how to use gps with lio-sam.
I tried with your "park" dataset but, without "imu_correct" topic in bag files, odom gps is not published.
Is it right? Then, why it needs for "ekf_gps" node??
Please reply my question...
Thank you!

**Comment by TixiaoShan** [comment]
EFK and navsat both need IMU. Without it, they won't work. That's why GPS odometry is not published without imu_correct.
[You can find more information here.](http://docs.ros.org/melodic/api/robot_localization/html/navsat_transform_node.html)
