### ISSUE TITLE
Why not allow 6 axis IMU with a filter to create RPY?

### ISSUE THREAD

**Issue by SteveMacenski** [TixiaoShan/LIO-SAM#108]
All the "9 axis" IMUs (which are 3 DOF accelerator, mag, and gyro; the RPY angle are **not** axes) just have an internal filter to create roll pitch and yaw angles based on the mag and gyro internally. 

Is there any reason we can't use the internal built in IMU from a LIDAR and just use a complementary or other IMU filter to get RPY? It seems silly to me to need an external IMU when you have a perfectly capable one inside the unit.

**Comment by TixiaoShan** [comment]
It's for easy implementation. Please free to push a commit to add this function.
