### ISSUE TITLE
/usr/local/include/gtsam/base/Vector.h:72:1: error: static assertion failed: Error: GTSAM was built against a different version of Eigen

### ISSUE THREAD

**Issue by carlin314** [TixiaoShan/LIO-SAM#11]
Hi,

if someone has same error as me,

Use under to build `gtsam`:
`cmake -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF .. -DGTSAM_USE_SYSTEM_EIGEN=ON`

It is mainly due to system eigen version is 3.2.9, while we may install other eigen versions and if you comile gtsam not 3.2.9 and when you compile LIO-SAM, you will find this error.

BR

**Comment by carlin314** [comment]
If you have many eigen versions, and if you use the `DGTSAM_USE_SYSTEM_EIGEN`, while gtsam build still shows it use other version not system version, this maybe quite tricky

**Comment by YiChenCityU** [comment]
How to change the eigen version in this system?
