### ISSUE TITLE
add relTime

### ISSUE THREAD

**Issue by LeisureLei** [TixiaoShan/LIO-SAM#112]
@TixiaoShan I use a rsldiar16 and a MTi-300 to run LIO-SAM. Due to rsldiar16 has no ring and time, I add the calculation of relTime according to LOAM into projectPointCloud() function in imageProjection.cpp .But LIO-SAM becomes worse than before.Is there anything I didn't notice?

**Comment by TixiaoShan** [comment]
Make sure the relTime varies between 0 and 0.1 when the lidar rotates at 10Hz. The relative timestamp for the first point received in a scan should be around 0. The last point timestamp should be around 0.1. If the results become worse, I suspect the calculation for the point timestamp is wrong somewhere.

**Comment by LeisureLei** [comment]
> Make sure the relTime varies between 0 and 0.1 when the lidar rotates at 10Hz. The relative timestamp for the first point received in a scan should be around 0. The last point timestamp should be around 0.1. If the results become worse, I suspect the calculation for the point timestamp is wrong somewhere.

Thanks for your  timely reply!
I checked the timestamp and it is ok. The data was collected while walking. May the low speed cause that?
I also found that there is something wrong in projectPointCloud() function. When I was running the code, I found sometimes ‘i’ of ‘for loop’ suddenly from a number that is not equal zero to zero by print i.

**Comment by TixiaoShan** [comment]
```May the low speed cause that?```
I don't think so. Most of my datasets were gathered at walking speed.
``` I found sometimes ‘i’ of ‘for loop’ suddenly from a number that is not equal zero to zero by print i.```
I am not sure what you mean here. Do you mean the poin cloud is empty sometimes?

**Comment by LeisureLei** [comment]
> `May the low speed cause that?`
> I don't think so. Most of my datasets were gathered at walking speed.
> ` I found sometimes ‘i’ of ‘for loop’ suddenly from a number that is not equal zero to zero by print i.`
> I am not sure what you mean here. Do you mean the poin cloud is empty sometimes?

Normally,  when the functuion **projectPointCloud()** is called once, **i** in **for loop** will increase from 0 to cloudSize-1 such as:
    
    first time is: 0
    last time is: 0.1

    first time is: 0
    last time is: 0.1
    ... ...

   But sometimes I will get this:
    
    first time is: 0
    first time is: 0
    first time is: 0
    last time is: 0.1

    first time is: 0
    last time is: 0.1
    ... ...
    which means **i** become 0 for several time.
   

    void projectPointCloud()
    {
        float verticalAngle;

        int cloudSize = laserCloudIn->points.size();

        //calculate start angle,end engle
        double startOri = -atan2(laserCloudIn->points[0].y, laserCloudIn->points[0].x);
        double endOri = -atan2(laserCloudIn->points[cloudSize - 1].y,
                          laserCloudIn->points[cloudSize - 1].x) +
                   2 * M_PI;
        if (endOri - startOri > 3 * M_PI)
        {
            endOri -= 2 * M_PI;
        }
        else if (endOri - startOri < M_PI)
        {
            endOri += 2 * M_PI;
        }
        bool halfPassed = false;

        // range image projection
        
        for (int i = 0; i < cloudSize; ++i)
        {
            PointType thisPoint;
            thisPoint.x = laserCloudIn->points[i].x;
            thisPoint.y = laserCloudIn->points[i].y;
            thisPoint.z = laserCloudIn->points[i].z;
            thisPoint.intensity = laserCloudIn->points[i].intensity;

            ////////////////////////////////////////////////////////////////////////////////
            // int rowIdn = laserCloudIn->points[i].ring;                         //
                                                                                  //
            verticalAngle = atan2(thisPoint.z, sqrt(thisPoint.x * thisPoint.x +   //change
                                              thisPoint.y * thisPoint.y)) *       //
                      180 / M_PI;                                                 //
            int rowIdn = (verticalAngle + 15) / 2.0;                              //
            ///////////////////////////////////////////////////////////////////////////////

            if (rowIdn < 0 || rowIdn >= N_SCAN)
                {continue;}

            if (rowIdn % downsampleRate != 0)
                {continue;}

            float horizonAngle = atan2(thisPoint.x, thisPoint.y) * 180 / M_PI;

            static float ang_res_x = 360.0/float(Horizon_SCAN);
            int columnIdn = -round((horizonAngle-90.0)/ang_res_x) + Horizon_SCAN/2;
            if (columnIdn >= Horizon_SCAN)
                columnIdn -= Horizon_SCAN;

            if (columnIdn < 0 || columnIdn >= Horizon_SCAN)
                {continue;}

            float range = pointDistance(thisPoint);
            
            if (range < 1.0)
                {continue;}

            if (rangeMat.at<float>(rowIdn, columnIdn) != FLT_MAX)
                {continue;}
            
            //calculate reltime
            double ori = -atan2(laserCloudIn->points[i].y, laserCloudIn->points[i].x);
            if (!halfPassed)
            { 
                if (ori < startOri - M_PI / 2)
                {
                    ori += 2 * M_PI;
                }
                else if (ori > startOri + M_PI * 3 / 2)
                {
                    ori -= 2 * M_PI;
                }

                if (ori - startOri > M_PI)
                {
                    halfPassed = true;
                }
            }
            else
            {
                ori += 2 * M_PI;
                if (ori < endOri - M_PI * 3 / 2)
                {
                    ori += 2 * M_PI;
                }
                else if (ori > endOri + M_PI / 2)
                {
                    ori -= 2 * M_PI;
                }
            }
            double relTime = (ori - startOri) / (endOri - startOri) * 0.1;
             if(i==0)
             std::cout<<"first time is:"<<relTime<<std::endl;
         
             if(i==cloudSize-1){
                 std::cout<<"last time is:"<<relTime<<std::endl<<std::endl;
             }
            
            thisPoint = deskewPoint(&thisPoint, relTime);  // rslidar
            // thisPoint = deskewPoint(&thisPoint, laserCloudIn->points[i].time); // Velodyne
            // thisPoint = deskewPoint(&thisPoint, (float)laserCloudIn->points[i].t / 1000000000.0); // Ouster
            
            rangeMat.at<float>(rowIdn, columnIdn) = pointDistance(thisPoint);

            int index = columnIdn + rowIdn * Horizon_SCAN;
            fullCloud->points[index] = thisPoint;
        }
    }

**Comment by TixiaoShan** [comment]
Is it because the last point at cloudSize-1 is not valid, so the loop is skipped by ```continue```?

**Comment by LeisureLei** [comment]
> Is it because the last point at cloudSize-1 is not valid, so the loop is skipped by `continue`?

I think you are right ! I will check carefully !
Besides, I used original edge and surf parameters to test in corridor and there is a serious overlap at both ends of the corridor. Thus I increased  edge and surf parameters, which eliminates the overlap. But there are still altitude errors in corridor. Are there other methods to handle this based lio-sam? I guess lack of ground features cause altitude errors.Thus I tilted the lidar 30 degrees to test and I got worse results.
Also, Can you please tell me how you to calibrate the imu noise? I use [imu_utils](https://github.com/gaowenliang/imu_utils) to calibrate using at least two hours static imu data. And calculated noise parameters also cause worse relust!

**Comment by TixiaoShan** [comment]
```But there are still altitude errors in corridor. Are there other methods to handle this based lio-sam? I guess lack of ground features cause altitude errors.Thus I tilted the lidar 30 degrees to test and I got worse results.```
Indoor environments are generally degraded for lidar-based method. It's hard to make sure the features can form fine constraints to the lidar motion. Even if you can cover the ground well, the x - forward motion may not be constrained well. Using it with visual-inertial odometry may solve this problem.
```Can you please tell me how you to calibrate the imu noise?```
I used the exact same package. There are some noise parameters in imuPreintegration.cpp. You can try to tune those manually and see if the results improve.

**Comment by LeisureLei** [comment]
> `But there are still altitude errors in corridor. Are there other methods to handle this based lio-sam? I guess lack of ground features cause altitude errors.Thus I tilted the lidar 30 degrees to test and I got worse results.`
> Indoor environments are generally degraded for lidar-based method. It's hard to make sure the features can form fine constraints to the lidar motion. Even if you can cover the ground well, the x - forward motion may not be constrained well. Using it with visual-inertial odometry may solve this problem.
> `Can you please tell me how you to calibrate the imu noise?`
> I used the exact same package. There are some noise parameters in imuPreintegration.cpp. You can try to tune those manually and see if the results improve.

I tested with lidar-inertial odometry which solves the problem in corridor!
Thanks for your patient reply！

**Comment by athtest800** [comment]
I also plan on using it with rslidar16. Can you provide the working code for this?
Thank you.

**Comment by LeisureLei** [comment]
> I also plan on using it with rslidar16. Can you provide the working code for this?
> Thank you.

Just modify the yaml file in condig folder. 

#topic parameter
  **pointCloudTopic**: "rslidar_points"              
  **imuTopic**: "imu/data" 
 
#IMU noise parameters: I use default.
  **imuAccNoise**: 3.9939570888238808e-03
  **imuGyrNoise**: 1.5636343949698187e-03
  **imuAccBiasN**: 6.4356659353532566e-05
  **imuGyrBiasN**: 3.5640318696367613e-05

#Rotate your IMU data to same frame(You may take a while to make sure the  meaning of these parameters)
  **extrinsicRot**: [1, 0, 0,
                 0, 1, 0,
                 0, 0, 1]
  **extrinsicRPY**: [1, 0, 0,
                 0, 1, 0,
                 0, 0, 1]

**Comment by athtest800** [comment]
Thanks. How did you overcome the problem of time and ring that the rslidar ros package does not have?

**Comment by LeisureLei** [comment]
> Thanks. How did you overcome the problem of time and ring that the rslidar ros package does not have?

Modify the imageProjection.cpp according to lego-loam:

#include "utility.h"
#include "lio_sam/cloud_info.h"

// Velodyne
struct PointXYZIRT
{
    PCL_ADD_POINT4D
    PCL_ADD_INTENSITY;
    uint16_t ring;
    float time;
    EIGEN_MAKE_ALIGNED_OPERATOR_NEW
} EIGEN_ALIGN16;

POINT_CLOUD_REGISTER_POINT_STRUCT (PointXYZIRT,  
    (float, x, x) (float, y, y) (float, z, z) (float, intensity, intensity)
    (uint16_t, ring, ring) (float, time, time)
)

// Ouster
// struct PointXYZIRT {
//     PCL_ADD_POINT4D;
//     float intensity;
//     uint32_t t;
//     uint16_t reflectivity;
//     uint8_t ring;
//     uint16_t noise;
//     uint32_t range;
//     EIGEN_MAKE_ALIGNED_OPERATOR_NEW
// }EIGEN_ALIGN16;

// POINT_CLOUD_REGISTER_POINT_STRUCT(PointXYZIRT,
//     (float, x, x) (float, y, y) (float, z, z) (float, intensity, intensity)
//     (uint32_t, t, t) (uint16_t, reflectivity, reflectivity)
//     (uint8_t, ring, ring) (uint16_t, noise, noise) (uint32_t, range, range)
// )

const int queueLength = 500;

class ImageProjection : public ParamServer
{
private:

    std::mutex imuLock;
    std::mutex odoLock;

    ros::Subscriber subLaserCloud;
    ros::Publisher  pubLaserCloud;
    
    ros::Publisher pubExtractedCloud;
    ros::Publisher pubLaserCloudInfo;

    ros::Subscriber subImu;
    std::deque<sensor_msgs::Imu> imuQueue;

    ros::Subscriber subOdom;
    std::deque<nav_msgs::Odometry> odomQueue;

    std::deque<sensor_msgs::PointCloud2> cloudQueue;
    sensor_msgs::PointCloud2 currentCloudMsg;
    
    double *imuTime = new double[queueLength];
    double *imuRotX = new double[queueLength];
    double *imuRotY = new double[queueLength];
    double *imuRotZ = new double[queueLength];

    int imuPointerCur;
    bool firstPointFlag;
    Eigen::Affine3f transStartInverse;

    pcl::PointCloud<PointXYZIRT>::Ptr laserCloudIn;
    pcl::PointCloud<PointType>::Ptr   fullCloud;
    pcl::PointCloud<PointType>::Ptr   extractedCloud;

    int deskewFlag;
    cv::Mat rangeMat;

    bool odomDeskewFlag;
    float odomIncreX;
    float odomIncreY;
    float odomIncreZ;

    lio_sam::cloud_info cloudInfo;
    double timeScanCur;
    double timeScanNext;
    std_msgs::Header cloudHeader;


public:
    ImageProjection():
    deskewFlag(0)
    {
        subImu        = nh.subscribe<sensor_msgs::Imu>(imuTopic, 2000, &ImageProjection::imuHandler, this, ros::TransportHints().tcpNoDelay());
        subOdom       = nh.subscribe<nav_msgs::Odometry>(odomTopic+"_incremental", 2000, &ImageProjection::odometryHandler, this, ros::TransportHints().tcpNoDelay());
        subLaserCloud = nh.subscribe<sensor_msgs::PointCloud2>(pointCloudTopic, 5, &ImageProjection::cloudHandler, this, ros::TransportHints().tcpNoDelay());

        pubExtractedCloud = nh.advertise<sensor_msgs::PointCloud2> ("lio_sam/deskew/cloud_deskewed", 1);
        pubLaserCloudInfo = nh.advertise<lio_sam::cloud_info> ("lio_sam/deskew/cloud_info", 1);

        allocateMemory();
        resetParameters();

        pcl::console::setVerbosityLevel(pcl::console::L_ERROR);
    }

    void allocateMemory()
    {
        laserCloudIn.reset(new pcl::PointCloud<PointXYZIRT>());
        fullCloud.reset(new pcl::PointCloud<PointType>());
        extractedCloud.reset(new pcl::PointCloud<PointType>());

        fullCloud->points.resize(N_SCAN*Horizon_SCAN);

        cloudInfo.startRingIndex.assign(N_SCAN, 0);
        cloudInfo.endRingIndex.assign(N_SCAN, 0);

        cloudInfo.pointColInd.assign(N_SCAN*Horizon_SCAN, 0);
        cloudInfo.pointRange.assign(N_SCAN*Horizon_SCAN, 0);

        resetParameters();
    }

    void resetParameters()
    {
        laserCloudIn->clear();
        extractedCloud->clear();
        // reset range matrix for range image projection
        rangeMat = cv::Mat(N_SCAN, Horizon_SCAN, CV_32F, cv::Scalar::all(FLT_MAX));

        imuPointerCur = 0;
        firstPointFlag = true;
        odomDeskewFlag = false;

        for (int i = 0; i < queueLength; ++i)
        {
            imuTime[i] = 0;
            imuRotX[i] = 0;
            imuRotY[i] = 0;
            imuRotZ[i] = 0;
        }
    }

    ~ImageProjection(){}

    void imuHandler(const sensor_msgs::Imu::ConstPtr& imuMsg)
    {
        sensor_msgs::Imu thisImu = imuConverter(*imuMsg);

        std::lock_guard<std::mutex> lock1(imuLock);
        imuQueue.push_back(thisImu);

        // debug IMU data
        // cout << std::setprecision(6);
        // cout << "IMU acc: " << endl;
        // cout << "x: " << thisImu.linear_acceleration.x << 
        //       ", y: " << thisImu.linear_acceleration.y << 
        //       ", z: " << thisImu.linear_acceleration.z << endl;
        // cout << "IMU gyro: " << endl;
        // cout << "x: " << thisImu.angular_velocity.x << 
        //       ", y: " << thisImu.angular_velocity.y << 
        //       ", z: " << thisImu.angular_velocity.z << endl;
        // double imuRoll, imuPitch, imuYaw;
        // tf::Quaternion orientation;
        // tf::quaternionMsgToTF(thisImu.orientation, orientation);
        // tf::Matrix3x3(orientation).getRPY(imuRoll, imuPitch, imuYaw);
        // cout << "IMU roll pitch yaw: " << endl;
        // cout << "roll: " << imuRoll << ", pitch: " << imuPitch << ", yaw: " << imuYaw << endl << endl;
    }

    void odometryHandler(const nav_msgs::Odometry::ConstPtr& odometryMsg)
    {
        std::lock_guard<std::mutex> lock2(odoLock);
        odomQueue.push_back(*odometryMsg);
    }

    void cloudHandler(const sensor_msgs::PointCloud2ConstPtr& laserCloudMsg)
    {
        if (!cachePointCloud(laserCloudMsg))
            return;

        if (!deskewInfo())
            return;

        projectPointCloud();

        cloudExtraction();

        publishClouds();

        resetParameters();
    }

    bool cachePointCloud(const sensor_msgs::PointCloud2ConstPtr& laserCloudMsg)
    {
        // cache point cloud
        cloudQueue.push_back(*laserCloudMsg);

        if (cloudQueue.size() <= 2)
            return false;
        else
        {
            currentCloudMsg = cloudQueue.front();
            cloudQueue.pop_front();

            cloudHeader = currentCloudMsg.header;
            timeScanCur = cloudHeader.stamp.toSec();
            timeScanNext = cloudQueue.front().header.stamp.toSec();
        }

        // convert cloud
        pcl::fromROSMsg(currentCloudMsg, *laserCloudIn);

        // check dense flag
        if (laserCloudIn->is_dense == false)
        {
            ROS_ERROR("Point cloud is not in dense format, please remove NaN points first!");
            ros::shutdown();
        }

        // // check ring channel
        // static int ringFlag = 0;
        // if (ringFlag == 0)
        // {
        //     ringFlag = -1;
        //     for (int i = 0; i < (int)currentCloudMsg.fields.size(); ++i)
        //     {
        //         if (currentCloudMsg.fields[i].name == "ring")
        //         {
        //             ringFlag = 1;
        //             break;
        //         }
        //     }
        //     if (ringFlag == -1)
        //     {
        //         ROS_ERROR("Point cloud ring channel not available, please configure your point cloud data!");
        //         ros::shutdown();
        //     }
        // }   

        // check point time
        if (deskewFlag == 0)
        {
            deskewFlag = -1;
            for (int i = 0; i < (int)currentCloudMsg.fields.size(); ++i)
            {
                if (currentCloudMsg.fields[i].name == timeField)
                {
                    deskewFlag = 1;
                    break;
                }
            }
            if (deskewFlag == -1)
                ROS_WARN("Point cloud timestamp not available, deskew function disabled, system will drift significantly!");
        }

        return true;
    }

    bool deskewInfo()
    {
        std::lock_guard<std::mutex> lock1(imuLock);
        std::lock_guard<std::mutex> lock2(odoLock);

        // make sure IMU data available for the scan
        if (imuQueue.empty() || imuQueue.front().header.stamp.toSec() > timeScanCur || imuQueue.back().header.stamp.toSec() < timeScanNext)
        {
            ROS_DEBUG("Waiting for IMU data ...");
            return false;
        }

        imuDeskewInfo();

        odomDeskewInfo();

        return true;
    }

    void imuDeskewInfo()
    {
        cloudInfo.imuAvailable = false;

        while (!imuQueue.empty())
        {
            if (imuQueue.front().header.stamp.toSec() < timeScanCur - 0.01)
                imuQueue.pop_front();
            else
                break;
        }

        if (imuQueue.empty())
            return;

        imuPointerCur = 0;

        for (int i = 0; i < (int)imuQueue.size(); ++i)
        {
            sensor_msgs::Imu thisImuMsg = imuQueue[i];
            double currentImuTime = thisImuMsg.header.stamp.toSec();

            // get roll, pitch, and yaw estimation for this scan
            if (currentImuTime <= timeScanCur)
                imuRPY2rosRPY(&thisImuMsg, &cloudInfo.imuRollInit, &cloudInfo.imuPitchInit, &cloudInfo.imuYawInit);

            if (currentImuTime > timeScanNext + 0.01)
                break;

            if (imuPointerCur == 0){
                imuRotX[0] = 0;
                imuRotY[0] = 0;
                imuRotZ[0] = 0;
                imuTime[0] = currentImuTime;
                ++imuPointerCur;
                continue;
            }

            // get angular velocity
            double angular_x, angular_y, angular_z;
            imuAngular2rosAngular(&thisImuMsg, &angular_x, &angular_y, &angular_z);

            // integrate rotation
            double timeDiff = currentImuTime - imuTime[imuPointerCur-1];
            imuRotX[imuPointerCur] = imuRotX[imuPointerCur-1] + angular_x * timeDiff;
            imuRotY[imuPointerCur] = imuRotY[imuPointerCur-1] + angular_y * timeDiff;
            imuRotZ[imuPointerCur] = imuRotZ[imuPointerCur-1] + angular_z * timeDiff;
            imuTime[imuPointerCur] = currentImuTime;
            ++imuPointerCur;
        }

        --imuPointerCur;

        if (imuPointerCur <= 0)
            return;

        cloudInfo.imuAvailable = true;
    }

    void odomDeskewInfo()
    {
        cloudInfo.odomAvailable = false;

        while (!odomQueue.empty())
        {
            if (odomQueue.front().header.stamp.toSec() < timeScanCur - 0.01)
                odomQueue.pop_front();
            else
                break;
        }

        if (odomQueue.empty())
            return;

        if (odomQueue.front().header.stamp.toSec() > timeScanCur)
            return;

        // get start odometry at the beinning of the scan
        nav_msgs::Odometry startOdomMsg;

        for (int i = 0; i < (int)odomQueue.size(); ++i)
        {
            startOdomMsg = odomQueue[i];

            if (ROS_TIME(&startOdomMsg) < timeScanCur)
                continue;
            else
                break;
        }

        tf::Quaternion orientation;
        tf::quaternionMsgToTF(startOdomMsg.pose.pose.orientation, orientation);

        double roll, pitch, yaw;
        tf::Matrix3x3(orientation).getRPY(roll, pitch, yaw);

        // Initial guess used in mapOptimization
        cloudInfo.initialGuessX = startOdomMsg.pose.pose.position.x;
        cloudInfo.initialGuessY = startOdomMsg.pose.pose.position.y;
        cloudInfo.initialGuessZ = startOdomMsg.pose.pose.position.z;
        cloudInfo.initialGuessRoll  = roll;
        cloudInfo.initialGuessPitch = pitch;
        cloudInfo.initialGuessYaw   = yaw;

        cloudInfo.odomAvailable = true;

        // get end odometry at the end of the scan
        odomDeskewFlag = false;

        if (odomQueue.back().header.stamp.toSec() < timeScanNext)
            return;

        nav_msgs::Odometry endOdomMsg;

        for (int i = 0; i < (int)odomQueue.size(); ++i)
        {
            endOdomMsg = odomQueue[i];

            if (ROS_TIME(&endOdomMsg) < timeScanNext)
                continue;
            else
                break;
        }

        if (int(round(startOdomMsg.pose.covariance[0])) != int(round(endOdomMsg.pose.covariance[0])))
            return;

        Eigen::Affine3f transBegin = pcl::getTransformation(startOdomMsg.pose.pose.position.x, startOdomMsg.pose.pose.position.y, startOdomMsg.pose.pose.position.z, roll, pitch, yaw);

        tf::quaternionMsgToTF(endOdomMsg.pose.pose.orientation, orientation);
        tf::Matrix3x3(orientation).getRPY(roll, pitch, yaw);
        Eigen::Affine3f transEnd = pcl::getTransformation(endOdomMsg.pose.pose.position.x, endOdomMsg.pose.pose.position.y, endOdomMsg.pose.pose.position.z, roll, pitch, yaw);

        Eigen::Affine3f transBt = transBegin.inverse() * transEnd;

        float rollIncre, pitchIncre, yawIncre;
        pcl::getTranslationAndEulerAngles(transBt, odomIncreX, odomIncreY, odomIncreZ, rollIncre, pitchIncre, yawIncre);

        odomDeskewFlag = true;
    }

    void findRotation(double pointTime, float *rotXCur, float *rotYCur, float *rotZCur)
    {
        *rotXCur = 0; *rotYCur = 0; *rotZCur = 0;

        int imuPointerFront = 0;
        while (imuPointerFront < imuPointerCur)
        {
            if (pointTime < imuTime[imuPointerFront])
                break;
            ++imuPointerFront;
        }

        if (pointTime > imuTime[imuPointerFront] || imuPointerFront == 0)
        {
            *rotXCur = imuRotX[imuPointerFront];
            *rotYCur = imuRotY[imuPointerFront];
            *rotZCur = imuRotZ[imuPointerFront];
        } else {
            int imuPointerBack = imuPointerFront - 1;
            double ratioFront = (pointTime - imuTime[imuPointerBack]) / (imuTime[imuPointerFront] - imuTime[imuPointerBack]);
            double ratioBack = (imuTime[imuPointerFront] - pointTime) / (imuTime[imuPointerFront] - imuTime[imuPointerBack]);
            *rotXCur = imuRotX[imuPointerFront] * ratioFront + imuRotX[imuPointerBack] * ratioBack;
            *rotYCur = imuRotY[imuPointerFront] * ratioFront + imuRotY[imuPointerBack] * ratioBack;
            *rotZCur = imuRotZ[imuPointerFront] * ratioFront + imuRotZ[imuPointerBack] * ratioBack;
        }
    }

    void findPosition(double relTime, float *posXCur, float *posYCur, float *posZCur)
    {
        *posXCur = 0; *posYCur = 0; *posZCur = 0;

        // If the sensor moves relatively slow, like walking speed, positional deskew seems to have little benefits. Thus code below is commented.

        if (cloudInfo.odomAvailable == false || odomDeskewFlag == false)
            return;

        float ratio = relTime / (timeScanNext - timeScanCur);

        *posXCur = ratio * odomIncreX;
        *posYCur = ratio * odomIncreY;
        *posZCur = ratio * odomIncreZ;
    }

    PointType deskewPoint(PointType *point, double relTime)
    {
        if (deskewFlag == -1 || cloudInfo.imuAvailable == false)
            return *point;
        // if (cloudInfo.imuAvailable == false)
        //     return *point;
        // std::cout<<"deskewPoint begin"<<std::endl;
        double pointTime = timeScanCur + relTime;

        float rotXCur, rotYCur, rotZCur;
        findRotation(pointTime, &rotXCur, &rotYCur, &rotZCur);

        float posXCur, posYCur, posZCur;
        findPosition(relTime, &posXCur, &posYCur, &posZCur);

        if (firstPointFlag == true)
        {
            transStartInverse = (pcl::getTransformation(posXCur, posYCur, posZCur, rotXCur, rotYCur, rotZCur)).inverse();
            firstPointFlag = false;
        }

        // transform points to start
        Eigen::Affine3f transFinal = pcl::getTransformation(posXCur, posYCur, posZCur, rotXCur, rotYCur, rotZCur);
        Eigen::Affine3f transBt = transStartInverse * transFinal;

        PointType newPoint;
        newPoint.x = transBt(0,0) * point->x + transBt(0,1) * point->y + transBt(0,2) * point->z + transBt(0,3);
        newPoint.y = transBt(1,0) * point->x + transBt(1,1) * point->y + transBt(1,2) * point->z + transBt(1,3);
        newPoint.z = transBt(2,0) * point->x + transBt(2,1) * point->y + transBt(2,2) * point->z + transBt(2,3);
        newPoint.intensity = point->intensity;

        return newPoint;
    }

    void projectPointCloud()
    {
        float verticalAngle;

        int cloudSize = laserCloudIn->points.size();

        //calculate start angle,end engle
        double startOri = -atan2(laserCloudIn->points[0].y, laserCloudIn->points[0].x);
        double endOri = -atan2(laserCloudIn->points[cloudSize - 1].y,
                          laserCloudIn->points[cloudSize - 1].x) +
                   2 * M_PI;
        if (endOri - startOri > 3 * M_PI)
        {
            endOri -= 2 * M_PI;
        }
        else if (endOri - startOri < M_PI)
        {
            endOri += 2 * M_PI;
        }
        bool halfPassed = false;

        // range image projection
        
        for (int i = 0; i < cloudSize; ++i)
        {
            PointType thisPoint;
            thisPoint.x = laserCloudIn->points[i].x;
            thisPoint.y = laserCloudIn->points[i].y;
            thisPoint.z = laserCloudIn->points[i].z;
            thisPoint.intensity = laserCloudIn->points[i].intensity;

            ////////////////////////////////////////////////////////////////////////////////
            // int rowIdn = laserCloudIn->points[i].ring;                         //
                                                                                  //
            verticalAngle = atan2(thisPoint.z, sqrt(thisPoint.x * thisPoint.x +   //change
                                              thisPoint.y * thisPoint.y)) *       //
                      180 / M_PI;                                                 //
            int rowIdn = (verticalAngle + 15) / 2.0;                              //
            ///////////////////////////////////////////////////////////////////////////////

            if (rowIdn < 0 || rowIdn >= N_SCAN)
                {continue;}

            if (rowIdn % downsampleRate != 0)
                {continue;}

            float horizonAngle = atan2(thisPoint.x, thisPoint.y) * 180 / M_PI;

            static float ang_res_x = 360.0/float(Horizon_SCAN);
            int columnIdn = -round((horizonAngle-90.0)/ang_res_x) + Horizon_SCAN/2;
            if (columnIdn >= Horizon_SCAN)
                columnIdn -= Horizon_SCAN;

            if (columnIdn < 0 || columnIdn >= Horizon_SCAN)
                {continue;}

            float range = pointDistance(thisPoint);
            
            if (range < 1.0)
                {continue;}

            if (rangeMat.at<float>(rowIdn, columnIdn) != FLT_MAX)
                {continue;}
            
            //calculate reltime
            double ori = -atan2(laserCloudIn->points[i].y, laserCloudIn->points[i].x);
            if (!halfPassed)
            { 
                if (ori < startOri - M_PI / 2)
                {
                    ori += 2 * M_PI;
                }
                else if (ori > startOri + M_PI * 3 / 2)
                {
                    ori -= 2 * M_PI;
                }

                if (ori - startOri > M_PI)
                {
                    halfPassed = true;
                }
            }
            else
            {
                ori += 2 * M_PI;
                if (ori < endOri - M_PI * 3 / 2)
                {
                    ori += 2 * M_PI;
                }
                else if (ori > endOri + M_PI / 2)
                {
                    ori -= 2 * M_PI;
                }
            }
            double relTime = (ori - startOri) / (endOri - startOri) * 0.1;
            // if(i==0)
            // std::cout<<"first time is:"<<relTime<<std::endl;
         
            // if(i%100==0){
            //     std::cout<<" time is:"<<relTime<<std::endl;
                
            // }
            // if(i==cloudSize-1){
            //     std::cout<<"last time is:"<<relTime<<std::endl<<std::endl;
            // }
            
            thisPoint = deskewPoint(&thisPoint, relTime);  // rslidar
            // thisPoint = deskewPoint(&thisPoint, laserCloudIn->points[i].time); // Velodyne
            // thisPoint = deskewPoint(&thisPoint, (float)laserCloudIn->points[i].t / 1000000000.0); // Ouster
            
            rangeMat.at<float>(rowIdn, columnIdn) = pointDistance(thisPoint);

            int index = columnIdn + rowIdn * Horizon_SCAN;
            fullCloud->points[index] = thisPoint;
        }
    }

    void cloudExtraction()
    {
        int count = 0;
        // extract segmented cloud for lidar odometry
        for (int i = 0; i < N_SCAN; ++i)
        {
            cloudInfo.startRingIndex[i] = count - 1 + 5;

            for (int j = 0; j < Horizon_SCAN; ++j)
            {
                if (rangeMat.at<float>(i,j) != FLT_MAX)
                {
                    // mark the points' column index for marking occlusion later
                    cloudInfo.pointColInd[count] = j;
                    // save range info
                    cloudInfo.pointRange[count] = rangeMat.at<float>(i,j);
                    // save extracted cloud
                    extractedCloud->push_back(fullCloud->points[j + i*Horizon_SCAN]);
                    // size of extracted cloud
                    ++count;
                }
            }
            cloudInfo.endRingIndex[i] = count -1 - 5;
        }
    }
    
    void publishClouds()
    {
        cloudInfo.header = cloudHeader;
        cloudInfo.cloud_deskewed  = publishCloud(&pubExtractedCloud, extractedCloud, cloudHeader.stamp, lidarFrame);
        pubLaserCloudInfo.publish(cloudInfo);
    }
};

int main(int argc, char** argv)
{
    ros::init(argc, argv, "lio_sam");

    ImageProjection IP;
    
    ROS_INFO("\033[1;32m----> Image Projection Started.\033[0m");

    ros::MultiThreadedSpinner spinner(3);
    spinner.spin();
    
    return 0;
}

**Comment by athtest800** [comment]
Thank you very much!

**Comment by oskarmue** [comment]
Hey, thank you for your solution! When I try to compile your new code I always get an error, that the variable "timeField" is not declared. 
Furthermore I had to switch "cloudInfo.cloud_deskewed  = publishCloud(&pubExtractedCloud, extractedCloud, cloudHeader.stamp, lidarFrame);" to "cloudInfo.cloud_deskewed  = publishCloud(pubExtractedCloud, extractedCloud, cloudHeader.stamp, lidarFrame);" in order to successfully compile. Is there some error from my side?
