### ISSUE TITLE
Test kitti 00

### ISSUE THREAD

**Issue by darkdelting** [TixiaoShan/LIO-SAM#113]
Thanks for your work ! 
I use your kitti2bag tools to get the 2011-10-03-0027 bag file (sequences 00).Then,I according to Readme.md to modify the params in the params.yaml. Unfortunately,I get a bad result. However,I run the 2011-09-30-0028 (sequences 08) bag file and I got good result. Is that the imu data of sequences00 worse than sequences08.

**Comment by TixiaoShan** [comment]
I didn't check the imu data of 00. It's possible the IMU data is not good.

**Comment by darkdelting** [comment]
Thanks for your answer.

**Comment by polbolso** [comment]
@darkdelting I'm also using KITTI sequence 08 but it seems to be a clear misalignment with the ground truth when evaluating them using evo.
Have you experienced something similar?

![Screenshot from 2021-05-13 17-45-55](https://user-images.githubusercontent.com/72814058/118444632-afed4900-b6ed-11eb-8bff-f1f159b94869.png)
