### ISSUE TITLE
the paths and maps generatedt are different from paper

### ISSUE THREAD

**Issue by Turtlehan1021** [TixiaoShan/LIO-SAM#114]
Thank you for your excellent work on LIO-SAM!
I run the sample datasets following the tips, and  I have change nothing except that parameters in config/params.yaml are adapted to the dataset. But the results including maps and paths are different from the paper. what's the reason? @TixiaoShan

**Comment by TixiaoShan** [comment]
There are many reasons that may cause this, for example, using different computing hardware, optimization returns different results.
