### ISSUE TITLE
the value of currentResetId != imuPreintegrationResetId?

### ISSUE THREAD

**Issue by zzyand** [TixiaoShan/LIO-SAM#115]
Thanks for your outstanding work !
      I have learned your work for a long time,but the value of ' currentResetId = round(odomMsg->pose.covariance[0]) ' always make me confused .And why  "currentResetId != imuPreintegrationResetId" is due to the ” correction pose jumped, reset imu pre-integration "?I don't know the value of  ' currentResetId = round(odomMsg->pose.covariance[0])' when it will be changed?and what the value it will be?

**Comment by TixiaoShan** [comment]
I couldn't find the code you mentioned. I think it was deleted months ago.
