### ISSUE TITLE
Point cloud data for each trajectory point

### ISSUE THREAD

**Issue by jungwoohan72** [TixiaoShan/LIO-SAM#117]
Thank you for your effort! Could anyone give me some help on following issue?

Seems like 'trajectory.pcd' file stores coordinates of each trajectory point, but is it possible to obtain corresponding point cloud data in addition to the trajectory point?

**Comment by TixiaoShan** [comment]
You can export all the point clouds in
```
vector<pcl::PointCloud<PointType>::Ptr> cornerCloudKeyFrames;
vector<pcl::PointCloud<PointType>::Ptr> surfCloudKeyFrames;
```
These clouds are saved in local coordinates. You can use trajectory cloud to transform them into global map frame.

**Comment by MaxikKot** [comment]
> 
> 
> You can export all the point clouds in
> 
> ```
> vector<pcl::PointCloud<PointType>::Ptr> cornerCloudKeyFrames;
> vector<pcl::PointCloud<PointType>::Ptr> surfCloudKeyFrames;
> ```
> 
> These clouds are saved in local coordinates. You can use trajectory cloud to transform them into global map frame.

Hi, TixiaoShan! Thanks for the great job.  
Could you please explain how I can use trajectory cloud to transform local coordinateы pointcloud into global map frame?
Thanks a lot in advance!
