### ISSUE TITLE
how to save global coordinate map?

### ISSUE THREAD

**Issue by zang09** [TixiaoShan/LIO-SAM#118]
Can i save cloud map using gps coordinate?

I want to make global map that each cloud points contain gps coordinate, not relative cartesian coordinate.

Of course, i use gps. My own bag files contain '/gps/fix' topic.

Is there any good way to solve this problem??

Thank you.

**Comment by TixiaoShan** [comment]
One way to do this is create another keyframe copy similar to
```
vector<pcl::PointCloud<PointType>::Ptr> cornerCloudKeyFrames;
vector<pcl::PointCloud<PointType>::Ptr> surfCloudKeyFrames;
```
Instead of saving points coordinate in the local frame, you can use a new copy to save GPS coordinates for each point.

**Comment by zang09** [comment]
I want to use navsat_transform_node in robot localization package to get my utm coordinate.

So I changed params like:
`wait_for_datum: true`
`broadcast_utm_transform: true`
`broadcast_utm_transform_as_parent_frame: true`

But, 'gps/odometry' topic still give me relative xyz, not absolute xyz.

**Comment by stah-ba** [comment]
@TixiaoShan could you elaborate a little more on the possibility to add the gps coordinate to each point in the map? I would like to have a map in utm coordinates. I started as you suggested above, but i get the gps position only each few meters and it is inserted to the factor graph for optimizatiion. Can i get the information afterwards for each point from the optimized position also as a global gps position?

**Comment by stah-ba** [comment]
@zang09 did you solve the problem or how did you continue working on it?
