### ISSUE TITLE
ERROR: cannot launch node ...

### ISSUE THREAD

**Issue by cristianrubioa** [TixiaoShan/LIO-SAM#119]
When I compile [roslaunch lio_sam run.launch] the launch terminal gives me:

ERROR: cannot launch node of type [robot_localization/ekf_localization_node]: robot_localization
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/rubio/catkin_ws/src
ROS path [2]=/opt/ros/melodic/share
ERROR: cannot launch node of type [robot_localization/navsat_transform_node]: robot_localization
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/rubio/catkin_ws/src
ROS path [2]=/opt/ros/melodic/share

**Comment by px4Li** [comment]
@cristianrubioa Have you tried " source /opt/ros/melodic/setup.bash" and "source devel/setup.bash" in lio-sam workspace directory?

**Comment by cristianrubioa** [comment]
@px4Li  Thanks. I tried and everything remains the same. I still have the error

**Comment by px4Li** [comment]
@cristianrubioa 
maybe you forgot install:

sudo apt-get install -y ros-melodic-robot-localization

**Comment by cristianrubioa** [comment]
@px4Li Thanks, solved.
