### ISSUE TITLE
How to time synch LiDAR with IMU.

### ISSUE THREAD

**Issue by px4Li** [TixiaoShan/LIO-SAM#120]
Hi, @TixiaoShan 
I am using os-32 and vectornav imu for lio-sam as shown in the image below.
![IMG_3266](https://user-images.githubusercontent.com/32841491/94098013-a1060d80-fe62-11ea-90a4-696ece27ab15.jpg)

As shown in the figure below, when I run lio-sam, rviz starts to jerking.
![issue](https://user-images.githubusercontent.com/32841491/94098435-8ed89f00-fe63-11ea-8bc7-f6aacc3d8e84.jpg)

![jerking](https://user-images.githubusercontent.com/32841491/94101717-62c11c00-fe6b-11ea-8f1a-00b3bfc05a19.gif)

I have read #94 but I still do not understand to time synch LiDAR with IMU. I did  "ptpd" to do time synchronization of the ouster LiDAR  on my pc. Do you have any suggestions on how to synchronize the IMU?

rosbag: 
https://drive.google.com/file/d/1KxAbhBx3XiXdnXEjLACgTOJZpXvAr9zE/view?usp=sharing

**Comment by TixiaoShan** [comment]
It may be caused by vibration. I suggest you calibrate the IMU while the lidar is turned on and static. New IMU parameters may help this problem.

**Comment by px4Li** [comment]
@TixiaoShan Thanks for your suggestion. I will try that.
Sorry I have others questions. I would like to ask you. 
1. Here is the image I captured when I run my datasets. The IMU timestamp and LiDAR timestamp are all using same ros time in secs. But do you know why in nsecs they are not same?
![time_synch](https://user-images.githubusercontent.com/32841491/94356503-525aac80-00ca-11eb-8f59-4d7de6efd207.jpg)

2. The time synchronization does care if the LiDAR and IMU readings are captured at the same time? i.e. They do not have to be synchronized. However, they need to share the same clock, meaning that it is important to know that e.g. the IMU data was taken 4ms after the LiDAR data. For this to be possible, the different clocks must be synchronized.

**Comment by IvanVN** [comment]
Hi @px4Li,

I'm trying to use the same IMU and I'm struggling to get good extrinsic parameters for it. Can you share the configuration you have used, please?

Thank you!

**Comment by px4Li** [comment]
Hi @IvanVN 
parameter setting for imu:
[vn100.zip](https://github.com/TixiaoShan/LIO-SAM/files/5406168/vn100.zip)

parameter setting for slam:
[params.zip](https://github.com/TixiaoShan/LIO-SAM/files/5406175/params.zip)

I hope these will give you help.

**Comment by IvanVN** [comment]
> Hi @IvanVN
> parameter setting for imu:
> [vn100.zip](https://github.com/TixiaoShan/LIO-SAM/files/5406168/vn100.zip)
> 
> parameter setting for slam:
> [params.zip](https://github.com/TixiaoShan/LIO-SAM/files/5406175/params.zip)
> 
> I hope these will give you help.

Thank you very much! My IMU is in a different position, but it has helped me a lot to find where my error was. :)

**Comment by JJuhyeon-Kim** [comment]
> @TixiaoShan Thanks for your suggestion. I will try that.
> Sorry I have other questions. I would like to ask you.
> 
> 1. Here is the image I captured when I run my datasets. The IMU timestamp and LiDAR timestamp are all using same ros time in secs. But do you know why in nsecs they are not same?
>    ![time_synch](https://user-images.githubusercontent.com/32841491/94356503-525aac80-00ca-11eb-8f59-4d7de6efd207.jpg)
> 2. The time synchronization does care if the LiDAR and IMU readings are captured at the same time? i.e. They do not have to be synchronized. However, they need to share the same clock, meaning that it is important to know that e.g. the IMU data was taken 4ms after the LiDAR data. For this to be possible, the different clocks must be synchronized.

Hi, @px4Li !

You gave me the idea of using ptpd, I cound sync the timestamp of LiDAR. 
I'm really grateful to you.

I have a question for you, are you still going through this problem?
I'm using OS1-128 (GEN2), and I'm having the same problem as issue207.
https://github.com/TixiaoShan/LIO-SAM/issues/207
I solved the timestamp problem, but the mapping is unstable like you.
Did you solve this problem?
