### ISSUE TITLE
lidar horizontal resolution 

### ISSUE THREAD

**Issue by ganindu7** [TixiaoShan/LIO-SAM#129]
Hi can you please explain 
```
Horizon_SCAN: 1800                          # lidar horizontal resolution (Velodyne:1800, Ouster:512,1024,2048)
```
I know that VLP 16 outputs 384 firings per packet, @0.2 Azimuth res at 600 RPM. I don't get how 1800 fits in. my code works but this is bugging me. I've used 3 lidar manufactures (Robosense, RFANS and LS) and all seem to work without this value being changed. (robosense and LS I've personally tested) 

explanation about 384: in single return mode there are 2 firings for data block (that means 16 * 2 measurements or points, meaning 16 rows and two columns) and there are 12 blocks per packet. 

per block there are 2 columns (azimuth points) and per packet there are 24 ( 2 * 12) columns = azimuth points .

if the Lidar rotates at 600 RPM (10 per second ) and VLP 16 releases 753.5 packets per seconds -> therefore one rotation is about 75.35 (approx 76 packets)  

Therefore for one rotation there can be 1824 (76 * 24) columns or azimuth measurements. 

I assume you got 1800 by rounding down (75 * 24) ? 

oops.. looks like I answered my own question!! Just mentioning here my thoughts so others don't have to.. Thanks a lot for producing LIO-SAM it's pretty cool. 

Thanks,
Ganindu.

**Comment by iportolesrb** [comment]
Hi @ganindu7,
How did you test it with the robosense lidar? The driver does not publish the "time" and "ring" fields in the pointcloud, does it?

**Comment by ganindu7** [comment]
HI @iportolesrb I wrote a new driver. Basically you just have to augment the point type. Have a look at point types in PCL and the datasheet for the device. The one I self-solved is the only problem I had.
Cheers,
Ganindu.

**Comment by DamienSalle** [comment]
@ganindu7, I'd also want to use a rs-lidar16 with lio-sam. Could you please share your new driver publishing the time and ring fields?
That would help a lot! 
Thanks
Damien
