### ISSUE TITLE
What is reason for two extrinsic rotation?

### ISSUE THREAD

**Issue by jojo89776** [TixiaoShan/LIO-SAM#13]
First, I really appreciate your code! It is really good to understand recent lidar-based SLAM. 

My question is, What is the reason for two extrinsic rotation? extrinsicRot and extrinsicRPY. 
extrinsicRPY seems to be used for orientation, and transformed rotation is used in initialization. 
Can we just use extrinsicRot (which used to transform imu info to lidar frame) for all process?

**Comment by TixiaoShan** [comment]
Here is the answer for it.
https://github.com/TixiaoShan/LIO-SAM/issues/6

**Comment by jojo89776** [comment]
Thanks. I'll close the issue
