### ISSUE TITLE
Some question about the start point

### ISSUE THREAD

**Issue by qian5683** [TixiaoShan/LIO-SAM#132]
Hi,I change the code like this
···
 // initialization
        if (cloudKeyPoses3D->points.empty())
        {
            transformTobeMapped[0] = cloudInfo.imuRollInit;
            transformTobeMapped[1] = cloudInfo.imuPitchInit;
            transformTobeMapped[2] = cloudInfo.imuYawInit;
            transformTobeMapped[3] = 100;
            transformTobeMapped[4] = -100;
            transformTobeMapped[5] = 10;

            if (!useImuHeadingInitialization)
                transformTobeMapped[2] = 0;

            lastImuTransformation = pcl::getTransformation(0, 0, 0, cloudInfo.imuRollInit, cloudInfo.imuPitchInit, cloudInfo.imuYawInit); // save imu before return;
            return;
        }
···

but it sometimes can't initialize well as the zero start point.

when the start point is [0,0,0], it can work well. But when i change the start point ,it can't work. 
Could you give me some advice? thank you very much.

**Comment by TixiaoShan** [comment]
I tried
```
transformTobeMapped[3] = 10000;
transformTobeMapped[4] = -10000;
transformTobeMapped[5] = 10000;
```
everything is initialized fine. Maybe something else is wrong.
