### ISSUE TITLE
When I use GPS,the map direction is different from when GPS is not used

### ISSUE THREAD

**Issue by qian5683** [TixiaoShan/LIO-SAM#134]
when I use GPS, it makes the map rotate, and the direction isn't the IMU anymore.

**Comment by Pallav1299** [comment]
Please verify the following:
1. 9-axis IMU is being used.
2. **useImuHeadingInitialization** is set to **true** in **params.yaml**

**Comment by cklbywq** [comment]
> when I use GPS, it makes the map rotate, and the direction isn't the IMU anymore.

Hi, can you tell me how to add GPS data in the project? I tried but no output in topic /odometry/gps and /odometry/navsat. Or can you show me your params.yaml and module_navsat.launch?

**Comment by FishInWave** [comment]
> > when I use GPS, it makes the map rotate, and the direction isn't the IMU anymore.
> 
> Hi, can you tell me how to add GPS data in the project? I tried but no output in topic /odometry/gps and /odometry/navsat. Or can you show me your params.yaml and module_navsat.launch?

I meet the same question. Did you finally solve it？

**Comment by Pallav1299** [comment]
@FishInWave, I think your issue is already addressed. Please go through the known issues in README.
