### ISSUE TITLE
error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by he-guo** [TixiaoShan/LIO-SAM#139]
hello,I encountered this kind of problem: 
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: undefined reference to symbol '_ZN3tbb8internal23allocate_via_handler_v3Em'
//usr/lib/x86_64-linux-gnu/libtbb.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
and Can you give me any suggestions? Thank you.

**Comment by he-guo** [comment]
oh, it's ok, I have solved.

**Comment by farhad-dalirani** [comment]
@narutojxl  I have the same problem. I do not understand your solution, can you explain with more detail?
