### ISSUE TITLE
LIO-SAM Coordinate definition

### ISSUE THREAD

**Issue by ygfwqqz** [TixiaoShan/LIO-SAM#140]
Hi @TixiaoShan  Thank you for sharing your amazing work and it is really enjoyable. 

Coordinate definition in LIO-SAM
1.	As shown in VLP Lidar user manual, its coordinate is defined as x-right, y-forward, z-up. The coordinate used in LIO_SAM is x-forward, y-left, z-upward. 
Do we need to perform some axis switch operation to unify the coordinate? 

In function. projectPointCloud(); I find that the laserCloudIn’s coordinates (x,y,z) is directly given to thisPoint.
`thisPoint.x = laserCloudIn->points[i].x;`
`thisPoint.y = laserCloudIn->points[i].y;`
`thisPoint.z = laserCloudIn->points[i].z;`

Thank you

**Comment by ygfwqqz** [comment]
As per discussed in website https://www.ros.org/reps/rep-0103.html

REP-103 describes the relationship between axes. i.e.,

In relation to a body the standard is:
x forward
y left
z up

Is it a typo in the document of REP-105 which should be REP-103??

**Comment by px4Li** [comment]
@ygfwqqz please read  README.md file carefully.

**Comment by ygfwqqz** [comment]
> @ygfwqqz please read README.md file carefully.

I do not think you understand my question carefully or understand the coordinate definition carefully.
