### ISSUE TITLE
GTSAM was built against a different version of Eigen.

### ISSUE THREAD

**Issue by Danis199** [TixiaoShan/LIO-SAM#142]
Hi everyone! Maybe someone faced such a problem when building a package?
![Снимок экрана от 2020-10-27 11-21-36](https://user-images.githubusercontent.com/73522138/97275151-a16d3c00-1846-11eb-9379-91c6968a0bbf.png)

**Comment by cklbywq** [comment]
Hi, you can add "set(GTSAM_USE_SYSTEM_EIGEN ON)" before "if(GTSAM_USE_SYSTEM_EIGEN)  find_package(Eigen3 REQUIRED)" in CMakeLists.txt of gtsam, and then re-compile gtsam again.

**Comment by Danis199** [comment]
Thank you! It's work.

**Comment by AndreiBarsan** [comment]
This helped me as well. By the way, for the sake of simplicity, you can achieve the same effect by simply passing an additional flag to `cmake`: `-DGTSAM_USE_SYSTEM_EIGEN=ON`

**Comment by congphase** [comment]
I modified `CMakeLists.txt` as suggested. But it does not even have a change I think.

![Screenshot from 2021-09-01 18-29-29](https://user-images.githubusercontent.com/33423127/131663989-f8ef0679-31fe-4e64-be9e-2079a786c0ad.png)

![Screenshot from 2021-09-01 18-30-05](https://user-images.githubusercontent.com/33423127/131664005-eb48eb25-977f-4055-870a-6c9a4ccee347.png)

**Comment by hellojarmon** [comment]
> I modified `CMakeLists.txt` as suggested. But it does not even have a change I think.
> 
> ![Screenshot from 2021-09-01 18-29-29](https://user-images.githubusercontent.com/33423127/131663989-f8ef0679-31fe-4e64-be9e-2079a786c0ad.png)
> 
> ![Screenshot from 2021-09-01 18-30-05](https://user-images.githubusercontent.com/33423127/131664005-eb48eb25-977f-4055-870a-6c9a4ccee347.png)
> 
> Do you have any idea?

Did you solve it ?

**Comment by congphase** [comment]
@hellojarmon Have you tried running the ["Using Docker"](https://github.com/TixiaoShan/LIO-SAM#using-docker) in the README?

Back then (Sept 2021), I solved it by creating a Docker image to resolve all the painful conflicts. But it was in Sept 2021, the repo did not support Docker stuff. Now they have one, you should use them, it should work.
