### ISSUE TITLE
lio_sam_imuPreintegration-1

### ISSUE THREAD

**Issue by he-guo** [TixiaoShan/LIO-SAM#148]
hi, I have this problem: 
[lio_sam_imuPreintegration-1] process has died [pid 30652, exit code -6, cmd /home/fire/catkin_lio/devel/lib/lio_sam/lio_sam_imuPreintegration __name:=lio_sam_imuPreintegration __log:=/home/fire/.ros/log/a40f131e-1d9d-11eb-b2d7-cc3d826486ce/lio_sam_imuPreintegration-1.log].
log file: /home/fire/.ros/log/a40f131e-1d9d-11eb-b2d7-cc3d826486ce/lio_sam_imuPreintegration-1*.log
![图片](https://user-images.githubusercontent.com/54622758/97955564-6d16f400-1de1-11eb-8916-afbf91d327cc.png)
is my imu data wrong? can you give me some suggestions?

**Comment by gaowc1990** [comment]
I got the same problem with you~

**Comment by he-guo** [comment]
Maybe the pose has changed a lot, generally the pose is not set correctly. I use the original IMU data and will not report this error, but the data will be jittered too much, which will cause confusion in the mapping. This problem occurs when I use imu data synthesized by fusion data. The problem has not been solved yet, I hope you can tell me what progress you have.

**Comment by oussama-chhoud** [comment]
i have the same problem.
there is a solution available? 
Thanks in advance

**Comment by lonlonago** [comment]
I have solved this problem . lonlonago@foxmail.com @oussama-chhoud  @he-guo  @gaowc1990

**Comment by narutojxl** [comment]
Maybe you can try [allan_variance_ros](https://github.com/ori-drs/allan_variance_ros) to give lio-sam proper noise param firstly :)

**Comment by oussama-chhoud** [comment]
@lonlonago can you please tell us the solution ?
thanks in advance

**Comment by Kenzo2511** [comment]
```
cd ~/Downloads/gtsam-4.0.2/
cd build
cmake -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF ..
sudo make install -j8
```

**Comment by mikolodz** [comment]
Using gtsam-4.0.2 is not helping in my case. I'm still facing the issue. It can be due to the fact that I'm using Isaac Sim and I'm not sure if it publishes the sensor readings properly. 10hz Ouster 3d lidar publishes more than 50 messages/sec, often multiple of them in a single nanosecond period. I think there might be some internal Isaac Sim problem causing this. Although, IDK how the LIO-SAM should react in such a case.
