### ISSUE TITLE
A loop detection integration 

### ISSUE THREAD

**Issue by gisbi-kim** [TixiaoShan/LIO-SAM#150]
Hi Tixiao Shan, I always appreciate you for sharing a good resource to study and even also practically amazing. 

Based on your work, I could easily integrate the global localizer and applied a bag of minor tricks for better loop closing.

The codes are here https://github.com/gisbi-kim/SC-LIO-SAM
I hope this also could be a little help to other researchers.

Thank you!

**Comment by TixiaoShan** [comment]
Thank you!

**Comment by chxyfishge** [comment]
Thank you for sharing this!
