### ISSUE TITLE
How does this compare with LeGO-LOAM?

### ISSUE THREAD

**Issue by soulslicer** [TixiaoShan/LIO-SAM#151]
Is the only difference between this code and that..is that IMU is used?

**Comment by xieqi1** [comment]
loose coupling -> tightly coupling

**Comment by soulslicer** [comment]
I dont understand what you mean by that? Is the ground plane constraint non existent in this one then?

**Comment by xieqi1** [comment]
ground plane constraint in LeGO-LOAM only used in scan-to-scan-match odometry rather than scan-to-map mapping, it make odometry faster than LOAM.
while in LIO-SAM,tightly coupling Lidar-IMU fusion provide better odometry, so it does not need scan-to-scan match to provide odometry.

**Comment by soulslicer** [comment]
Can I ask what scan to scan match means?

**Comment by xieqi1** [comment]
There is a thread named odometry which provide initial guess for mapping thread, in LOAM or LeGO-LOAM, scan-to-scan match is used as odometry, which means use current scan and last scan to do scan matching, the result offers initial guess for mapping.

**Comment by soulslicer** [comment]
okay, i was just concerned that it referred to each lidar column for each scanning angle. looks like my questions are answered thank you
