### ISSUE TITLE
GTSAM from ppa

### ISSUE THREAD

**Issue by Timple** [TixiaoShan/LIO-SAM#156]
The GTSAM [Quick-start guide](https://gtsam.org/get_started/) also states there is a ppa available.

It seems like it's using version [4.0.3](https://launchpad.net/~borglab/+archive/ubuntu/gtsam-release-4.0)

Would this work? I am not sure what the `-DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF` does and if that is also present in the ppa.

**Comment by Timple** [comment]
I figured out that the `BUILD_WITH_MARCH_NATIVE` would need to be off for a ppa. So that is alright.

Now I have to find the time to test this :)

**Comment by HappySamuel** [comment]
Hi @Timple 

I am currently also trying to use the gtsam (4.0.3) from ppa, how do you turn OFF the BUILD_WITH_MARCH_NATIVE? 

Best,
Samuel
