### ISSUE TITLE
ros2 version

### ISSUE THREAD

**Issue by CAKGOD** [TixiaoShan/LIO-SAM#161]
Hi! Thanks for your great work! Is there a ros2 version of LIO-SAM?
Now I am porting this framework to ros2. The codes are put in [lio_sam_ros2](https://github.com/CAKGOD/lio_sam_ros2).
Looking forward to your advice.

**Comment by CAKGOD** [comment]
> Hi! Thanks for your great work! Is there a ros2 version of LIO-SAM?
> Now I am porting this framework to ros2. The codes are put in [lio_sam_ros2](https://github.com/CAKGOD/lio_sam_ros2).
Looking forward to your advice.

**Comment by TixiaoShan** [comment]
Thank you!
