### ISSUE TITLE
how to get extrinsic and time offset between imu and lidar ?

### ISSUE THREAD

**Issue by chennuo0125-HIT** [TixiaoShan/LIO-SAM#169]

**Comment by HMellor** [comment]
Extrinsic offset is measured (by hand or using CAD if you designed a mounting bracket) between the sensor output origin for your IMU and LiDAR. Sensor origins can be found in the manuals for your sensors.

What do you mean by time offset?

**Comment by chennuo0125-HIT** [comment]
measure extrinsic by hand isnt precise, this error will influence mapping precise ?

**Comment by chennuo0125-HIT** [comment]
time offset means time difference introduced by clock out of sync

**Comment by HMellor** [comment]
> measure extrinsic by hand isnt precise, this error will influence mapping precise ?
You're right. But unless you have CAD models and CNC/3D printed mounting hardware that is the best you can do with the current implementation. You could try to optimise the extrinsic values based on the quality of the mapping, but that is not trivial or part of this codebase.

> time offset means time difference introduced by clock out of sync
As far as I'm aware (@TixiaoShan correct me if I'm wrong), there are no parameters for synchronising the clocks of the sensors. I believe that if the sensors are connected to the same computer as the ROS master, they will all be operating from the system clock.

**Comment by chennuo0125-HIT** [comment]
i have wrote a project to calibrate the extrinsic rotation from lidar to imu [https://github.com/chennuo0125-HIT/lidar_imu_calib](https://github.com/chennuo0125-HIT/lidar_imu_calib)

**Comment by chennuo0125-HIT** [comment]
measure extrinsic by hand is Inappropriate, especially for product development, everyone maybe get different result :(
