### ISSUE TITLE
Some questions about the 9-axis IMU

### ISSUE THREAD

**Issue by windwolf9** [TixiaoShan/LIO-SAM#17]
Hi,@TiXiaoShan,Thank you for your great work!  I don't know why you have to use a 9-axis IMU,and the magnetometer in the IMU is not used in your code，Can you tell me the reason for using a 9-axis IMU instead of a 6-axis IMU?
Thank you very much!

**Comment by TixiaoShan** [comment]
The reason is that 9-axis IMU gives roll pitch yaw, which are used for LIO-SAM initialization. More descriptions can be found in readme (IMU requirement).

**Comment by windwolf9** [comment]
Thank you. I see！
