### ISSUE TITLE
RSLIDAR point deskew 

### ISSUE THREAD

**Issue by Pallav1299** [TixiaoShan/LIO-SAM#170]
I tried LIO-SAM with RS-16 LIDAR. I am not getting proper LIDAR rings. See pic.
The vehicle speed is around **15-20kmph**. 
I tried using the commented position deskew in imageProjection node, but the results were similar.
AFAIK, there is no motion compensation/ pointcloud deskew in RSLIDAR. Is this particular to RSLIDAR? How can I improve this?
![deskew_1](https://user-images.githubusercontent.com/32015105/102067893-bebf8f00-3e21-11eb-9234-24ae869879a4.png)
![deskew_2](https://user-images.githubusercontent.com/32015105/102067929-c8e18d80-3e21-11eb-8d8c-934aa7101fdc.png)
White: raw pointcloud, Intensity: deskewed cloud from imageProjection.cpp

**Comment by 415522099** [comment]
I have the same problem.
