### ISSUE TITLE
Larger velocity warning with subT dataset

### ISSUE THREAD

**Issue by DJNing** [TixiaoShan/LIO-SAM#180]
Hello, I am testing the lio-sam system but I got a continuous warning for "Large velocity, reset IMU-preintegration!". And the trajectory result is very bad. The IMU data is from gx5-25 and with lidar ouster os1-64. Could you give me some hints for solving this?

**Comment by TixiaoShan** [comment]
Please refer to this issue for using Ouster lidar.
https://github.com/TixiaoShan/LIO-SAM/issues/94

**Comment by DJNing** [comment]
Thanks for the reply, I've already check this. I am new to ROS, and wonder how to apply the ros::time::now() during the bag file play?

**Comment by bugdeveloper0** [comment]
@DJNing hello，I encountered the same situation as you，have you solve it already？
