### ISSUE TITLE
Ideas on deskewing the point cloud

### ISSUE THREAD

**Issue by SubMishMar** [TixiaoShan/LIO-SAM#182]
Hi, thanks for your code. I am trying to implement an algorithm to deskew lidar scans using IMU measurements. I wanted to know how exactly you did it. From what I can decipher from the code base, you iterate through the entire point cloud and deskew each point individually. How do you ensure that this can be done in real time? My guess, from what I see in the code is, you remove a lot of points by putting range filters, downsampling, etc.. Does it lead to deterioration of quality if you downsample the cloud? 

When I try to iterate through the entire point cloud it takes really long.
Thanks.

**Comment by TixiaoShan** [comment]
The deskew code in imageProjection.cpp is for the entire cloud. I didn't try to deskew downsampled cloud, probably the accuracy will be reduced.
