### ISSUE TITLE
Error about using with GPS

### ISSUE THREAD

**Issue by raewon-sudo** [TixiaoShan/LIO-SAM#183]
i am using this lio sam for mapping, i using tf between gps and base link, but i can't see anything about odometry/gps. Can you help me to solution

**Comment by px4Li** [comment]
Do you have "imu_correct" topic in your rosbag?

**Comment by raewon-sudo** [comment]
I had only /imu/data. Can i use it instead ? 
You can share detail information about topic /imu_correct . It is different from /imu/data ?
Thank you,

**Comment by px4Li** [comment]
https://github.com/TixiaoShan/LIO-SAM/issues/137

hi, I think you can find the answer from here.

**Comment by MengHuiLei** [comment]
hello. I want to use GPS factor. I only modify the GPS topic in param.yaml, but it doesn't work. Can you help me ? Thank you !
