### ISSUE TITLE
how to do localization with Lio slam generated map?

### ISSUE THREAD

**Issue by Thedush** [TixiaoShan/LIO-SAM#184]
Hi currently i was working with the lio slam package but i want to know. is it possible to run the localization alone with a build map.
For example i have created a map using lio slam. now i want to localize my robot inside the map with build map features and graph.
is there anyway i can achieve this

**Comment by xieqi1** [comment]
If you only save the global map, you can use general scan matching methods such as GICP or NDT.While if you save the map consist of corner point cloud and surf point cloud, you can also use the scan matching method just like what LOAM does.

**Comment by Thedush** [comment]
How do i save the map generated by the lio-sam . In rviz they map was shown in '/lio_sam/mapping/cloud_registered' topic but it wasn't a complete map it was decayed points. how do i save the map to a pcd

**Comment by xieqi1** [comment]
i think you can refer this issue #3

**Comment by jjbecomespheh** [comment]
You can also use this pull request by zang09
https://github.com/TixiaoShan/LIO-SAM/pull/196
