### ISSUE TITLE
Can not run sample datasets

### ISSUE THREAD

**Issue by fergcd** [TixiaoShan/LIO-SAM#186]
![NotWorking](https://user-images.githubusercontent.com/13186723/103994816-e0baf000-51da-11eb-886a-97de6f51dfe2.PNG)

When I "roslaunch lio_sam run.launch", lio_sam_rviz is showing Global Status, base_link, and Velodyne "RED" on its Displays view.
And when I tried to run casual_walk.bag file, lio_sam_mapOptimization keeps dying and nothing is displayed on lio_sam_rviz.

![StillNotWorking](https://user-images.githubusercontent.com/13186723/103999825-bd933f00-51e0-11eb-9c7a-c5a46a12b50f.PNG)

Sometimes I can see point cloud like second screenshot, but lio_sam_mapOptimization still keeps dying and lio_sam_rviz shows drift.

Why is this happening and what should I do?  I installed gtsam following README.md, so I don't think it's gtsam version problem.
I'm using Ubuntu16.04 on VirtualBox.

**Comment by cumulo-autumn** [comment]
I have the same problem. Any update?

**Comment by px4Li** [comment]
did you install all of these:

sudo apt-get install -y ros-kinetic-navigation
sudo apt-get install -y ros-kinetic-robot-localization
sudo apt-get install -y ros-kinetic-robot-state-publisher

**Comment by fergcd** [comment]
@px4Li Yes, I did.  I followed all the commands written in README.md.

**Comment by cumulo-autumn** [comment]
I am using melodic. Should I still install ros-kinetic-navigation or should I install ros-melodic-navigation instead?

**Comment by fergcd** [comment]
Problem solved by setting Virtual Machine's RAM from 4GB to 16GB.
I think it was caused by memory issue.
