### ISSUE TITLE
OS1-128 mapping error

### ISSUE THREAD

**Issue by JJuhyeon-Kim** [TixiaoShan/LIO-SAM#188]
Dear TixiaoShan, thank you for your brilliant work.

I tried SLAM with Velodyne lidar using your source code and succeeded.
Now I'm trying to use Ouster lidar but there was a mapping error.
I used the same sensor as you. (OS1-128, LORD IMU sensor)

What I changed in 'params.yaml' file is topic name, lidar model, number of channel, and horizontal resolution. 
![image](https://user-images.githubusercontent.com/67694476/104454680-93c78700-55e9-11eb-8eac-4ab2538085df.png)

When I did roslaunch with ouster launch file, I defined timestamp mode as you mentioned. 
![image](https://user-images.githubusercontent.com/67694476/104454924-e7d26b80-55e9-11eb-9b4f-926a6346677e.png)

I don't know the cause, but I can't map it. I've been trying to solve this problem for weeks. If you know anything about this, please give me some advice.
![image](https://user-images.githubusercontent.com/67694476/104455173-40096d80-55ea-11eb-9892-74a20757f71d.png)

I also share my bag file here.
https://drive.google.com/drive/folders/1F_kMXPAdxfhmymauiMEeppUkxK9Gc26d?usp=sharing

Thank you!

**Comment by px4Li** [comment]
LIO-SAM only works with a 9-axis IMU.

**Comment by JJuhyeon-Kim** [comment]
> LIO-SAM only works with a 9-axis IMU.

Yes. I used 9-axis IMU, but I failed mapping with OS1-128

**Comment by IvanVN** [comment]
Hi,

We are having what it looks like the same problem. We are doing the same as @JJuhyeon-Kim, with the same result.

I'm using the same Ouster OS1-128 with a Vectornav VN-100 IMU. We are using the [official Ouster driver](https://github.com/ouster-lidar/ouster_example).

We have successfully used LIO-SAM with Velodyne and RSLidar with the same IMU previously, but we are not able to make it work with the Ouster.

Was the problem solved? How?

Thank you for your help.

**Comment by Cristian-wp** [comment]
Same problem, but with an Ouster OS0-64.

**Comment by IvanVN** [comment]
> Same problem, but with an Ouster OS0-64.

FYI, in our case it resulted a problem with the Ouster driver [not providing proper ROS timestamp](https://github.com/ouster-lidar/ouster_example/pull/214) if not synchronized by PTP. We solved it applying the proposed patch to the driver, but apparently [this functionality has been already added recently](https://github.com/ouster-lidar/ouster_example/issues/74) to the latest release (we have not tested it yet).

**Comment by tokoro10g** [comment]
For someone who run into this problem and found this issue, here are the solutions as of today:
- Launch driver.launch in the ouster-ros package with `timestamp_mode:=TIME_FROM_ROS_TIME` instead of `TIME_FROM_PTP_1588`.
- If you would like to use PTP and the timestamp of the data is about 37 sec behind the system clock, set `ptp_utc_tai_offset` to 0 for driver.launch.
