### ISSUE TITLE
The error result for Campus dataset (large) dataset

### ISSUE THREAD

**Issue by sysuzyc** [TixiaoShan/LIO-SAM#19]
Hi, @TixiaoShan, thanks for your excellent work !
There are some questions for Campus dataset (large) dataset.  I have changed the `imuTopic` to `imu_correct` and `extrinsicRot`, `extrinsicRPY` to Identity matrix in `config/params.yaml`. 
And the rosbag plays at normal speed:`rosbag play big_loop.bag` 
But the final result is not as expected.  There is a big shift in the global map.
Here is the result in my computer.
![](https://raw.githubusercontent.com/sysuzyc/Picture/master/LOAM%E7%B3%BB/IMG_0139.jpg)
And this is the demo result in LIO-SAM Paper.
![](https://raw.githubusercontent.com/sysuzyc/Picture/master/LOAM%E7%B3%BB/IMG_0141.jpg)
The red and black block is the different area.
The detail is shown as:
![](https://raw.githubusercontent.com/sysuzyc/Picture/master/LOAM%E7%B3%BB/globalerror.png)
![](https://raw.githubusercontent.com/sysuzyc/Picture/master/LOAM%E7%B3%BB/lio-sam-error.png)

How can I get the correct result? 
Thanks very much!

**Comment by TixiaoShan** [comment]
That's expected because LIO-SAM has drift when loop closure is not enabled.

**Comment by TixiaoShan** [comment]
You can enable the loop closure function by following README instructions.
https://github.com/TixiaoShan/LIO-SAM/issues/21

**Comment by sysuzyc** [comment]
Thanks. I have changed the `loopClosureEnableFlag` parameter to `true` in `config/params.yaml` . 
The result is better now.
![](https://raw.githubusercontent.com/sysuzyc/Picture/master/LOAM%E7%B3%BB/lio-sam-result.png)
![](https://raw.githubusercontent.com/sysuzyc/Picture/master/LOAM%E7%B3%BB/loop_closure.png)

**By the way**, the IMU used in this project is 9-axis. The orientation could be get defaultly.  If there is a 6-axis IMU, could I get the orientation by Integrating the angular velocity? Therefore, the 6-axis IMU could also be used in this project.

**Comment by TixiaoShan** [comment]
Theoretically, it's possible to use a 6-axis IMU. There are only a few places used roll, pitch, and yaw info.

**Comment by sysuzyc** [comment]
OK. I will try it. Thanks very much.
