### ISSUE TITLE
About Hesai Pandar 40P Lidar. IMU error?

### ISSUE THREAD

**Issue by raewon-sudo** [TixiaoShan/LIO-SAM#192]
I am using Hesai Pandar 40P with IMU MTI-100. Sometimes, IMU is zigzag and drifted far. Can you give me suggestions about this problem

**Comment by HMellor** [comment]
As per the [issues section](https://github.com/TixiaoShan/LIO-SAM#issues) of the README, this usually happens when the LiDAR and IMU is out of sync. Try setting the USB/serial port you are using for the IMU to low latency mode.

**Comment by hanlinniu** [comment]
> I am using Hesai Pandar 40P with IMU MTI-100. Sometimes, IMU is zigzag and drifted far. Can you give me suggestions about this problem

Have you solved this problem with Hesai lidar?
