### ISSUE TITLE
how to use GPS?

### ISSUE THREAD

**Issue by MengHuiLei** [TixiaoShan/LIO-SAM#198]
hello,I am sorry to trouble you. I want to use GPS factor, and I modify the GPS topic in param.yaml but it doesn't work. Can you help me ? Thank you very much!

**Comment by MengHuiLei** [comment]
Can you help me ? I will be very grateful to you.

**Comment by FishInWave** [comment]
> Can you help me ? I will be very grateful to you.

Hi, Do you find the way to use GPS?
