### ISSUE TITLE
Why Large Velocity Happens - Large velocity, reset IMU-preintegration!?

### ISSUE THREAD

**Issue by carlin314** [TixiaoShan/LIO-SAM#20]
Hi,

Thx for great work, I use our dataset and find imu path is not that stable and the imu when turn happens, alway like zigzag, 

and when in large yawrate, failure happens in so big velocity, any ideas?

![image](https://user-images.githubusercontent.com/16414165/87412337-82320200-c5fb-11ea-9766-166041a5737b.png)

BR

**Comment by TixiaoShan** [comment]
It's probably the extrinsic between IMU and Lidar is not correct, so the imu integration is wrong.

**Comment by carlin314** [comment]
> It's probably the extrinsic between IMU and Lidar is not correct, so the imu integration is wrong.

Thx, the extrinsics are right, I find it is the imu data which is not right for it, it took me a while to get that right to work

**Comment by carlin314** [comment]
If someone also has imu data problem, Mine is under as a reference, mine is Novatel pp7d-e1, which inertial is EG320N
![image](https://user-images.githubusercontent.com/16414165/87505807-62064f80-c69c-11ea-9656-deac53e5522c.png)

**Comment by zwmisdu** [comment]
> If someone also has imu data problem, Mine is under as a reference, mine is Novatel pp7d-e1, which inertial is EG320N
> ![image](https://user-images.githubusercontent.com/16414165/87505807-62064f80-c69c-11ea-9656-deac53e5522c.png)

I have the same problem as yours. Could you leave the e-mail so that we can communicate further?

**Comment by ibrahimhroob** [comment]
Hi @zwmisdu 

I am having the same issue, have you figured out how to solve it?
