### ISSUE TITLE
Run big-loop.bag data set with different results  

### ISSUE THREAD

**Issue by windwolf9** [TixiaoShan/LIO-SAM#21]
Hi,@TixiaoShan,I run big-loop.bag dataset, the results of  loop closure is different，and Sometimes the results was good, sometimes it was bad! (Three times out of ten the results were good) Did I miss some key steps？ Thanks!

The results are as follows：

![20200714181842](https://user-images.githubusercontent.com/17972452/87415666-fec6df80-c5ff-11ea-8024-4b2595893c8b.png)

![20200714182539](https://user-images.githubusercontent.com/17972452/87415681-071f1a80-c600-11ea-8655-8b1729e6ecc4.png)

**Comment by TixiaoShan** [comment]
The loop closure results come from PCL icp. Sometimes ICP gives bad results. A more advanced loop closure can be found here.
https://github.com/irapkaist/SC-LeGO-LOAM

**Comment by windwolf9** [comment]
Thanks,and I found that the loop closure is good In the beginning()，and it will going to get worse immediately and  an error occurs :[ WARN] [1594800092.012221229]: Large velocity, reset IMU-preintegration! When it happened，the maps got worse。

The results are as follows：
![20200715162417](https://user-images.githubusercontent.com/17972452/87522284-00ec7500-c6b8-11ea-88d8-b2cdb8449d09.png)
![20200715162513](https://user-images.githubusercontent.com/17972452/87522312-0944b000-c6b8-11ea-835c-bce18e995ce0.png)
![20200715162557](https://user-images.githubusercontent.com/17972452/87522336-119ceb00-c6b8-11ea-8f1e-438868da6019.png)

**Comment by TixiaoShan** [comment]
The current implementation of loop closure is not ideal. The success rate heavily depends on the performance of PCL icp.

**Comment by TixiaoShan** [comment]
**A better implementation is welcome from the community.** 
**Feel free to join and discuss how to improve its performance.**

**Comment by TixiaoShan** [comment]
> **A better implementation is welcome from the community.**
> **Feel free to join and discuss how to improve its performance.**

Loop closure should be fixed now.
