### ISSUE TITLE
Point cloud timestamp not available, deskew function disabled, system will drift significantly!

### ISSUE THREAD

**Issue by yutouwd** [TixiaoShan/LIO-SAM#216]
Hello @TixiaoShan,

Thanks for your outstanding work. I am trying to run LIO-SAM by using our own rosbag. The system would drift significantly after first few second and have the warming:`Point cloud timestamp not available, deskew function disabled, system will drift significantly!'`. Just like the below gif.

![Peek 2021-03-09 21-57](https://user-images.githubusercontent.com/6382417/110482006-25073580-8123-11eb-8fb6-6e1826f1a6bb.gif)

I have modified IMU setting by using [imu_utils][1]. And I also set `use_sim_time` to true and adding `--clock` when playing the rosbag. But all these don't solve the problem. Would you give some suggestions on it? Thank you so much. 

[1]:https://github.com/gaowenliang/imu_utils

**Comment by greenfield932** [comment]
Check ROS driver of your LIDAR, it should support timestamp for each point in the cloud. Warning means point cloud data in your rosbag does not have such information.
Your movement does not look too fast in translation and rotation, so I guess disabled deskew is not a main reason. Possible problems are misaligned timestamps in lidar/imu, too noisy IMU, issues in IMU setup. Did you perform IMU setup procedure  described by the author?
