### ISSUE TITLE
Velodyne frame of reference

### ISSUE THREAD

**Issue by WysokiStudent** [TixiaoShan/LIO-SAM#225]
In the README velodyne's frame of reference is presented as follows:
![obraz](https://user-images.githubusercontent.com/37147444/113274923-819ee000-92de-11eb-808b-b11f3309a81c.png)
with the x axis opposite the cable. In the manual it is the y axis that is opposite the cable.
![obraz](https://user-images.githubusercontent.com/37147444/113275148-c165c780-92de-11eb-9fbc-4ee4b3407db2.png)
Where does this difference come from? I have not noticed the velodyne ROS driver mention anything about it.

**Comment by Cristian-wp** [comment]
Hi @WysokiStudent I have notice the same thing trying to create my  extrinsicRPY matrix in params.yaml . Have you find a solution?
