### ISSUE TITLE
Ouster + Brick v2 IMU extrinsics setup

### ISSUE THREAD

**Issue by Jaetriel** [TixiaoShan/LIO-SAM#227]
Hello, I've got a setup consisting of the OS1-128 lidar and a Brick v2 IMU, a 9-axis external IMU. I have managed to get the configuration up and running, orientation seems mostly fine, but the problem is if I start moving the sensors a bit faster, or sometimes just on their own, I start getting jerking and even bigger jumps and leaps and the whole setup becomes pretty much unstable and unusable. Sometimes also when I tilt the sensor in a direction the velocity starts increasing and it starts jumping and flying everywhere as well.

![lio-sam 1](https://user-images.githubusercontent.com/43788971/113897967-b2de4b00-97cb-11eb-8861-d099a7697d24.png)

![lio-sam 2](https://user-images.githubusercontent.com/43788971/113898001-ba9def80-97cb-11eb-8fe7-7219caf120f1.png)

![lio-sam 3](https://user-images.githubusercontent.com/43788971/113898008-bbcf1c80-97cb-11eb-9e3f-0f91e5cf8954.png)

I have managed to sync the timestamps correctly(as far as i have tested and know) using PTP and the lidar is running in TIME_FROM_PTP_1588 mode. Could this be also caused by the fact that the IMU's max frequency is only 100hz or is it just the case that the extrinsics are not setup correctly? My params.yaml file looks like this: 
[Link to gist with params](https://gist.github.com/Jaetriel/7e74e4cfcb7049b6c239f2918aa61a53)

And this is what my stamps look like when I print timeScanCur, timeScanEnd, imuQueue front and back in imageProjection.cpp:
![lio-sam 4](https://user-images.githubusercontent.com/43788971/114007806-f2577680-9861-11eb-98a6-0a87b28b31f4.png)

I tried using the imu lidar calibration package in the project and the results I've put commented in the yaml file and I tried replacing the extrinsicRot and extrinsicRPY values with the ones I got from the package, but if anything, the situation got a little bit worse and I'm not exactly sure how to proceed to get the correct extrinsics for my setup?  

Any help or suggestions would be appreciated, thanks.

**Comment by Jaetriel** [comment]
Update: So the biggest issue was a little oversight on my part, in my IMU node it was taking linear acceleration instead of acceleration with the effects of gravity accounted for, so now it's a lot more stable. One issue still remains, that if I rotate the sensor a bit more rapidly, or if it stays rotated for a longer period of time, it gets some weird acceleration values and starts roaming again, could this be some sort of wrong extrinsic or gravity values?

**Comment by ataparlar** [comment]
Hi there,
Could you solve the roaming problem after configured your IMU? I am dealing with the same issue. Map occurs correct first but after moving about 10 meters, it starts to roaming. 
Have a good day.
ataparlar

**Comment by 18954534983** [comment]
> Hi there, Could you solve the roaming problem after configured your IMU? I am dealing with the same issue. Map occurs correct first but after moving about 10 meters, it starts to roaming. Have a good day. ataparlar



> Hello, I have encountered the same problem as you, but the method of calibration and time stamp synchronization has not been solved. May I ask how you solved this problem?

**Comment by 18954534983** [comment]
> Hi there, Could you solve the roaming problem after configured your IMU? I am dealing with the same issue. Map occurs correct first but after moving about 10 meters, it starts to roaming. Have a good day. ataparlar

Hello, I have encountered the same problem as you. Since my IMU position is above the ridar, I ruled out the reason that the external parameter calibration of IMU and ridar is not accurate. I synchronized the time stamps of IMU and ridar, but the problem of ground rise still exists. How did you solve it? Thank you.
