### ISSUE TITLE
[Enhancement] Move class declarations to headers and add doxygen strings

### ISSUE THREAD

**Issue by YoshuaNava** [TixiaoShan/LIO-SAM#23]
Dear Tixiao,
This work is really awesome. Thank you for sharing it with the community.

By means of this issue I would like to suggest introducing headers for each class, and adding doxygen strings to the methods.

Please let me know what you think. I would be happy to submit pull requests for one module at a time, if possible with no changes to the underlying functionality.

Best,
Yoshua

**Comment by TixiaoShan** [comment]
This sounds great to me!
