### ISSUE TITLE
Failed to save map

### ISSUE THREAD

**Issue by ghz009** [TixiaoShan/LIO-SAM#231]
Thank you for your code, which helped me a lot.
And when I play back my recorded bag and want to save the map, I get the following error:

terminate called after throwing an instance of 'pcl::IOException'
  what():  : [pcl::PCDWriter::writeBinary] Input point cloud has no data!

**Comment by ibrahimhroob** [comment]
Hi @ghz009

Have you figured out how to save the map/path? 

Thanks

**Comment by ghz009** [comment]
> Hi @ghz009
> 
> Have you figured out how to save the map/path?
> 
> Thanks

Thank you for your reply.
I know how to save the map and can successfully save the official map.
But when I save my own map, I get errors.

**Comment by christophTUM** [comment]
> > Hi @ghz009
> > Have you figured out how to save the map/path?
> > Thanks
> 
> Thank you for your reply.
> I know how to save the map and can successfully save the official map.
> But when I save my own map, I get errors.

How did you save the official map?

**Comment by ibrahimhroob** [comment]
In the params.yaml file, you need to set "savePCD" to true
