### ISSUE TITLE
Image projection keeps restarting! 

### ISSUE THREAD

**Issue by ibrahimhroob** [TixiaoShan/LIO-SAM#232]
Hi @TixiaoShan 

I have an issue when running the algorithm, not sure why but the image projection keeps restarting and I wan not able to debug the source if the issue. I have attached the terminal output messages. Any help would be much appreciated, many thanks. 

![liosamwtf](https://user-images.githubusercontent.com/47870260/115412306-17e26980-a1ec-11eb-8db5-df86b9abc556.PNG)

**Comment by ibrahimhroob** [comment]
The issue was with the data from velodyne, for some reason the point cloud width and height were the other way around, swapping them back seems to fix the issue!

**Comment by lyhbit** [comment]
very good

**Comment by jyothishkiran** [comment]
hi @ibrahimhroob i am new to autonomous projects. I have the same issue while running the algorithm. Could you tell me how you swapped height and width of point cloud?

**Comment by jyothishkiran** [comment]
hi @ibrahimhroob i am new to autonomous projects. I have the same issue while running the algorithm. Could you tell me how you swapped height and width of point cloud?

**Comment by ibrahimhroob** [comment]
Hi @jyothishkiran 
In the image projection node modified the first bit of `cachePointCloud` function to the following:
`

    bool cachePointCloud(const sensor_msgs::PointCloud2ConstPtr& laserCloudMsg)
    {
        // cache point cloud
        cloudQueue.push_back(*laserCloudMsg);
        if (cloudQueue.size() <= 2)
            return false;

        // convert cloud
        currentCloudMsg = std::move(cloudQueue.front());
        cloudQueue.pop_front();

        //For some reason the point cloud data from the velodyne plugin does not follow stander point cloud data structure!!   
        if(currentCloudMsg.height > 1){
            currentCloudMsg.width = currentCloudMsg.height;
            currentCloudMsg.height = 1;
        }
        currentCloudMsg.header.frame_id = "base_link";

.
.
.


` 

Hope it helps

**Comment by jyothishkiran** [comment]
thank you so much @ibrahimhroob  it worked

**Comment by cs2514** [comment]
hi @ibrahimhroob i have an issue in generated map. could you help me solve this https://github.com/TixiaoShan/LIO-SAM/issues/244#issue-895805726
