### ISSUE TITLE
[Enhancement] Add linter

### ISSUE THREAD

**Issue by YoshuaNava** [TixiaoShan/LIO-SAM#24]
Hi Tixiao,
By means of this issue I want to suggest supporting clang format and clang tidy to:

1) Keep the code well-formatted, accelerate contributions and reduce time spent discussing formatting.
2) Discover possible issues and find out ways to modernize the code thanks to clang code analysis.

Please let me know what you think.

Best,
Yoshua

**Comment by TixiaoShan** [comment]
I am not very familiar to this proposal. I will take to do some research first.
