### ISSUE TITLE
Trajectory misaligned compared to KITTI ground truth

### ISSUE THREAD

**Issue by polbolso** [TixiaoShan/LIO-SAM#241]
I am evaluating the results of LIO-SAM using KITTI's 2011_09_30_drive_0028 (sequence 8 from KITTI odometry benchmark) and at first glance, these are clearly misaligned. 

I just adjusted the parameters in params.yaml as is suggested and didn't change anything else.

However, I see that for example in #162 it worked quite well using the same dataset, so I assume there is something wrong with my settings. 
Any clue how to solve this?

![Screenshot from 2021-05-13 17-45-55](https://user-images.githubusercontent.com/72814058/118153874-a9717f80-b416-11eb-8b48-c1bc046527a8.png)

**Comment by tigerschweiger** [comment]
> I am evaluating the results of LIO-SAM using KITTI's 2011_09_30_drive_0028 (sequence 8 from KITTI odometry benchmark) and at first glance, these are clearly misaligned.
> 
> I just adjusted the parameters in params.yaml as is suggested and didn't change anything else.
> 
> However, I see that for example in #162 it worked quite well using the same dataset, so I assume there is something wrong with my settings. Any clue how to solve this?
> 
> ![Screenshot from 2021-05-13 17-45-55](https://user-images.githubusercontent.com/72814058/118153874-a9717f80-b416-11eb-8b48-c1bc046527a8.png)

Hey,did u solve it ? i have also this problem. seems like that the timestamp goes wrong

**Comment by 15358283586cxQ** [comment]
你好，从2011_09_30_DRIVE_0028的115s处开始播放bag文件即可以解决这个问题（貌似是bag文件比ground_truth数据多出一段路程）
