### ISSUE TITLE
Map appearing in red color only

### ISSUE THREAD

**Issue by cs2514** [TixiaoShan/LIO-SAM#244]
Hi @TixiaoShan i am a newbie and i was doing mapping using LIO SAM. Everything worked perfectly without any errors when i used my bag but I am getting map only in red color(rviz dispaly). I dont know whether this is an issue since all the other bags(eg: campus dataset) produced colourful maps. 
![A38CBDB7-3CBD-49CC-AA1E-0831C7754021](https://user-images.githubusercontent.com/83896005/118872664-dd0e4700-b8f9-11eb-8945-e8f9218c8b71.jpeg)
![A1167768-AE3F-4FE6-BDD8-86D59C504BF5](https://user-images.githubusercontent.com/83896005/118872677-e13a6480-b8f9-11eb-82a4-00057d42abd4.jpeg)
![0BA4868D-15C1-407B-A08C-F7C48E679410](https://user-images.githubusercontent.com/83896005/118872684-e39cbe80-b8f9-11eb-9bea-87195048e33a.jpeg)
![7EA2530B-0A4A-498B-8BE4-EC46058AE9B8](https://user-images.githubusercontent.com/83896005/118872694-e697af00-b8f9-11eb-8186-d69c1c9d39a5.jpeg)

**Comment by jyothishkiran** [comment]
> Hi @TixiaoShan i am a newbie and i was doing mapping using LIO SAM. Everything worked perfectly without any errors when i used my bag but I am getting map only in red color(rviz dispaly). I dont know whether this is an issue since all the other bags(eg: campus dataset) produced colourful maps.
> ![A38CBDB7-3CBD-49CC-AA1E-0831C7754021](https://user-images.githubusercontent.com/83896005/118872664-dd0e4700-b8f9-11eb-8945-e8f9218c8b71.jpeg)
> ![A1167768-AE3F-4FE6-BDD8-86D59C504BF5](https://user-images.githubusercontent.com/83896005/118872677-e13a6480-b8f9-11eb-82a4-00057d42abd4.jpeg)
> ![0BA4868D-15C1-407B-A08C-F7C48E679410](https://user-images.githubusercontent.com/83896005/118872684-e39cbe80-b8f9-11eb-9bea-87195048e33a.jpeg)
> ![7EA2530B-0A4A-498B-8BE4-EC46058AE9B8](https://user-images.githubusercontent.com/83896005/118872694-e697af00-b8f9-11eb-8186-d69c1c9d39a5

**Comment by cbaus** [comment]
Do you see a coloured map when you switch on `Map (Global)` in rviz?

**Comment by cs2514** [comment]
hi @cbaus i tried switching on Map (Global) in rviz but still it is in red color. i will attach the screen shots of my configurations.
/home/jyothish/Pictures/Screenshot from 2021-05-20 15-27-36.png
/home/jyothish/Pictures/Screenshot from 2021-05-20 15-27-44.png

i launched campus dataset bag using LIO SAM but i got colored map with same rviz configuration
/home/jyothish/Pictures/Screenshot from 2021-05-20 15-33-03.png

**Comment by cs2514** [comment]
hi @cbaus i tried switching on Map (Global) in rviz but still it is in red color. i will attach the screen shots of my configurations.
![Screenshot from 2021-05-20 15-11-07](https://user-images.githubusercontent.com/83896005/118972632-ce6b7280-b981-11eb-889b-eea6703ab491.png)
![Screenshot from 2021-05-20 15-27-44](https://user-images.githubusercontent.com/83896005/118972655-d6c3ad80-b981-11eb-9c51-659e4d214431.png)

i launched campus dataset bag using LIO SAM but i got colored map with same rviz configuration
![Screenshot from 2021-05-20 15-33-03](https://user-images.githubusercontent.com/83896005/118972677-ddeabb80-b981-11eb-97b6-b1b154eba50f.png)

**Comment by cbaus** [comment]
I see. I am really new at using lio-sam but maybe check if your point clouds have intensity value (XYZ**I**)

**Comment by lucksonzhen** [comment]
@cs2514 Hi, could you please show me your config yaml for campus dataset? Thanks a lot!!! I think I have followed the guide from the readme.md , and tried a lot of change to the parameters, but the mapping process for 3 datasets I've tried seems quite messy, with the warning of "Large velocity, reset imu preintegration"&"not enough features" a lot.

**Comment by cs2514** [comment]
@lucksonzhen sure 

lio_sam:

  # Topics
  pointCloudTopic: "points_raw"               # Point cloud data
  imuTopic: "imu_correct"                         # IMU data
  odomTopic: "odometry/imu"                   # IMU pre-preintegration odometry, same frequency as IMU
  gpsTopic: "odometry/gpsz"                   # GPS odometry topic from navsat, see module_navsat.launch file

  # Frames
  lidarFrame: "base_link"
  baselinkFrame: "base_link"
  odometryFrame: "odom"
  mapFrame: "map"

  # GPS Settings
  useImuHeadingInitialization: false          # if using GPS data, set to "true"
  useGpsElevation: false                      # if GPS elevation is bad, set to "false"
  gpsCovThreshold: 2.0                        # m^2, threshold for using GPS data
  poseCovThreshold: 25.0                      # m^2, threshold for using GPS data
  
  # Export settings
  savePCD: false                              # https://github.com/TixiaoShan/LIO-SAM/issues/3
  savePCDDirectory: "/Downloads/LOAM/"        # in your home folder, starts and ends with "/". Warning: the code deletes "LOAM" folder then recreates it. See "mapOptimization" for implementation

  # Sensor Settings
  sensor: velodyne                            # lidar sensor type, either 'velodyne' or 'ouster'
  N_SCAN:   16                              # number of lidar channel (i.e., 16, 32, 64, 128)
  Horizon_SCAN: 1800                          # lidar horizontal resolution (Velodyne:1800, Ouster:512,1024,2048)
  timeField: "time" 
  downsampleRate: 1                           # default: 1. Downsample your data if too many points. i.e., 16 = 64 / 4, 16 = 16 / 1
  lidarMinRange: 1.0                          # default: 1.0, minimum lidar range to be used
  lidarMaxRange: 1000.0                       # default: 1000.0, maximum lidar range to be used

  # IMU Settings
  imuAccNoise: 3.9939570888238808e-03
  imuGyrNoise: 1.5636343949698187e-03
  imuAccBiasN: 6.4356659353532566e-05
  imuGyrBiasN: 3.5640318696367613e-05
  imuGravity: 9.80511
  imuRPYWeight: 0.01

  # Extrinsics (lidar -> IMU)
  extrinsicTrans: [0, 0, 0]
  extrinsicRot: [1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]
  extrinsicRPY: [1,  0, 0,
                 0, 1, 0,
                  0, 0, 1]
  # extrinsicRot: [1, 0, 0,
  #                 0, 1, 0,
  #                 0, 0, 1]
  # extrinsicRPY: [1, 0, 0,
  #                 0, 1, 0,
  #                 0, 0, 1]

  # LOAM feature threshold
  edgeThreshold: 1.0
  surfThreshold: 0.1
  edgeFeatureMinValidNum: 10
  surfFeatureMinValidNum: 100

  # voxel filter paprams
  odometrySurfLeafSize: 0.4                     # default: 0.4 - outdoor, 0.2 - indoor
  mappingCornerLeafSize: 0.2                    # default: 0.2 - outdoor, 0.1 - indoor
  mappingSurfLeafSize: 0.4                      # default: 0.4 - outdoor, 0.2 - indoor

  # robot motion constraint (in case you are using a 2D robot)
  z_tollerance: 1000                            # meters
  rotation_tollerance: 1000                     # radians

  # CPU Params
  numberOfCores: 4                              # number of cores for mapping optimization
  mappingProcessInterval: 0.15                  # seconds, regulate mapping frequency

  # Surrounding map
  surroundingkeyframeAddingDistThreshold: 1.0   # meters, regulate keyframe adding threshold
  surroundingkeyframeAddingAngleThreshold: 0.2  # radians, regulate keyframe adding threshold
  surroundingKeyframeDensity: 2.0               # meters, downsample surrounding keyframe poses   
  surroundingKeyframeSearchRadius: 50.0         # meters, within n meters scan-to-map optimization (when loop closure disabled)

  # Loop closure
  loopClosureEnableFlag: true
  loopClosureFrequency: 1.0                     # Hz, regulate loop closure constraint add frequency
  surroundingKeyframeSize: 50                   # submap size (when loop closure enabled)
  historyKeyframeSearchRadius: 15.0             # meters, key frame that is within n meters from current pose will be considerd for loop closure
  historyKeyframeSearchTimeDiff: 30.0           # seconds, key frame that is n seconds older will be considered for loop closure
  historyKeyframeSearchNum: 25                  # number of hostory key frames will be fused into a submap for loop closure
  historyKeyframeFitnessScore: 0.3              # icp threshold, the smaller the better alignment

  # Visualization
  globalMapVisualizationSearchRadius: 1000.0    # meters, global map visualization radius
  globalMapVisualizationPoseDensity: 10.0       # meters, global map visualization keyframe density
  globalMapVisualizationLeafSize: 1.0           # meters, global map visualization cloud density




# Navsat (convert GPS coordinates to Cartesian)
navsat:
  frequency: 50
  wait_for_datum: false
  delay: 0.0
  magnetic_declination_radians: 0
  yaw_offset: 0
  zero_altitude: true
  broadcast_utm_transform: false
  broadcast_utm_transform_as_parent_frame: false
  publish_filtered_gps: false

# EKF for Navsat
ekf_gps:
  publish_tf: false
  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  frequency: 50
  two_d_mode: false
  sensor_timeout: 0.01
  # -------------------------------------
  # External IMU:
  # -------------------------------------
  imu0: imu_correct
  # make sure the input is aligned with ROS REP105. "imu_correct" is manually transformed by myself. EKF can also transform the data using tf between your imu and base_link
  imu0_config: [false, false, false,
                true,  true,  true,
                false, false, false,
                false, false, true,
                true,  true,  true]
  imu0_differential: false
  imu0_queue_size: 50 
  imu0_remove_gravitational_acceleration: true
  # -------------------------------------
  # Odometry (From Navsat):
  # -------------------------------------
  odom0: odometry/gps
  odom0_config: [true,  true,  true,
                 false, false, false,
                 false, false, false,
                 false, false, false,
                 false, false, false]
  odom0_differential: false
  odom0_queue_size: 10

  #                            x     y     z     r     p     y   x_dot  y_dot  z_dot  r_dot p_dot y_dot x_ddot y_ddot z_ddot
  process_noise_covariance: [  1.0,  0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,      0,
                               0,    1.0,  0,    0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,      0,
                               0,    0,    10.0, 0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,      0,
                               0,    0,    0,    0.03, 0,    0,    0,     0,     0,     0,    0,    0,    0,    0,      0,
                               0,    0,    0,    0,    0.03, 0,    0,     0,     0,     0,    0,    0,    0,    0,      0,
                               0,    0,    0,    0,    0,    0.1,  0,     0,     0,     0,    0,    0,    0,    0,      0,
                               0,    0,    0,    0,    0,    0,    0.25,  0,     0,     0,    0,    0,    0,    0,      0,
                               0,    0,    0,    0,    0,    0,    0,     0.25,  0,     0,    0,    0,    0,    0,      0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0.04,  0,    0,    0,    0,    0,      0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,     0.01, 0,    0,    0,    0,      0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0.01, 0,    0,    0,      0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0.5,  0,    0,      0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,    0.01, 0,      0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0.01,   0,
                               0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,    0,    0,      0.015]

**Comment by cs2514** [comment]
@lucksonzhen sure
[params.pdf](https://github.com/TixiaoShan/LIO-SAM/files/6520727/params.pdf)

check lidar -> IMU transform part in the above file.

**Comment by cs2514** [comment]
hi @TixiaoShan  @cbaus i am using HDL-32e lidar. Tried many times changing lidar and the world but still the mapping process is coming in red color.

**Comment by cs2514** [comment]
hi @TixiaoShan  @cbaus i am using HDL-32e lidar. Tried many times changing lidar and the world but still the mapping process is coming in red color.

**Comment by lucksonzhen** [comment]
> @lucksonzhen sure
> [params.pdf](https://github.com/TixiaoShan/LIO-SAM/files/6520727/params.pdf)
> 
> check lidar -> IMU transform part in the above file.

Thanks !

**Comment by lincob** [comment]
> hi @TixiaoShan @cbaus i am using HDL-32e lidar. Tried many times changing lidar and the world but still the mapping process is coming in red color. it would be great if someone could help me on this.

What velodyne drivers are you using ? When you launch a rviz to visualize only the point cloud does it shows intensity ?

**Comment by yxallnyy** [comment]
> @lucksonzhen sure
> [params.pdf](https://github.com/TixiaoShan/LIO-SAM/files/6520727/params.pdf)
> 
> check lidar -> IMU transform part in the above file.

hi,could you share your dataset & yaml, i get the same problem. thx

**Comment by yxallnyy** [comment]
> Hi @TixiaoShan i am a newbie and i was doing mapping using LIO SAM. Everything worked perfectly without any errors when i used my bag but I am getting map only in red color(rviz dispaly). I dont know whether this is an issue since all the other bags(eg: campus dataset) produced colourful maps.
> ![A38CBDB7-3CBD-49CC-AA1E-0831C7754021](https://user-images.githubusercontent.com/83896005/118872664-dd0e4700-b8f9-11eb-8945-e8f9218c8b71.jpeg)
> ![A1167768-AE3F-4FE6-BDD8-86D59C504BF5](https://user-images.githubusercontent.com/83896005/118872677-e13a6480-b8f9-11eb-82a4-00057d42abd4.jpeg)
> ![0BA4868D-15C1-407B-A08C-F7C48E679410](https://user-images.githubusercontent.com/83896005/118872684-e39cbe80-b8f9-11eb-9bea-87195048e33a.jpeg)
> ![7EA2530B-0A4A-498B-8BE4-EC46058AE9B8](https://user-images.githubusercontent.com/83896005/118872694-e697af00-b8f9-11eb-8186-d69c1c9d39a5.jpeg)



> Hi @TixiaoShan i am a newbie and i was doing mapping using LIO SAM. Everything worked perfectly without any errors when i used my bag but I am getting map only in red color(rviz dispaly). I dont know whether this is an issue since all the other bags(eg: campus dataset) produced colourful maps.
> ![A38CBDB7-3CBD-49CC-AA1E-0831C7754021](https://user-images.githubusercontent.com/83896005/118872664-dd0e4700-b8f9-11eb-8945-e8f9218c8b71.jpeg)
> ![A1167768-AE3F-4FE6-BDD8-86D59C504BF5](https://user-images.githubusercontent.com/83896005/118872677-e13a6480-b8f9-11eb-82a4-00057d42abd4.jpeg)
> ![0BA4868D-15C1-407B-A08C-F7C48E679410](https://user-images.githubusercontent.com/83896005/118872684-e39cbe80-b8f9-11eb-9bea-87195048e33a.jpeg)
> ![7EA2530B-0A4A-498B-8BE4-EC46058AE9B8](https://user-images.githubusercontent.com/83896005/118872694-e697af00-b8f9-11eb-8186-d69c1c9d39a5.jpeg)

hi, could you share your data & yaml ? i got the same problem. thx

**Comment by viettiepx2** [comment]
Hi @cs2514 !
I got same issue, did you fix it?
