### ISSUE TITLE
can we let the LiDAR start from Z-down status?

### ISSUE THREAD

**Issue by XW-HKU** [TixiaoShan/LIO-SAM#248]
Thanks for your works!

I wonder if we can let the LiDAR works starting from Z-down status? do we need to change some parameters?

**Comment by spiffy673** [comment]
I am trying to do the same thing.  What I have tried so far:
1.  Tested with ladar and IMU in z-up position and verified that it worked.  Flipped it over and it would not initialize in that position.
2. Flipped to z-down position (around x axis), but kept imu in z-up position.  Set transforms to:
  extrinsicRot: [1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]
  extrinsicRPY: [1, 0, 0,
                   0, -1, 0,
                   0, 0, -1]
Didn't initialize, but the transforms may very well be wrong.
3.  Flipped to z-down position (around x axis), but kept imu in z-up position.  Set transforms to identity, but changed lines 220 and 221 in imageProjection.cpp to:
                dst.y = -src.y;
                dst.z = -src.z;
It initializes and functions, but two issues showed up.  In the output the x axis is reversed and the y axis is reversed.  Along with that the /odometry/imu_incremental is a saw tooth.  The imu data pushes it the correct direction, but then it jumps in the incorrect direction presumably based on the ladar data.

Have you had any more success in getting it to work?
