### ISSUE TITLE
Add camera to LIO-SAM to texture and color point cloud

### ISSUE THREAD

**Issue by Jaetriel** [TixiaoShan/LIO-SAM#249]
Hey guys, would it be possible to add camera images to LIO-SAM to texture and color the point cloud( not just for visual odometry ), and if so what are the possible ways to go about doing it? Maybe there are already some ready packages to add the camera images in or it could be done with some software as post-processing after we've scanned and collected the cloud with a Lidar and IMU

**Comment by cyhunblr** [comment]
Did you find anything else?

**Comment by WFram** [comment]
There are two main packages now regarding the question:
1) [R3LIVE](https://github.com/hku-mars/r3live)
2) [FAST-LIVO](https://github.com/hku-mars/FAST-LIVO)
