### ISSUE TITLE
[Enhancement] Silence warnings from external dependencies

### ISSUE THREAD

**Issue by YoshuaNava** [TixiaoShan/LIO-SAM#25]
Currently, the cmake file specifies include directories as follows:

```cmake
include_directories(
	include
	${catkin_INCLUDE_DIRS}
	${PCL_INCLUDE_DIRS}
  ${OpenCV_INCLUDE_DIRS}
	${GTSAM_INCLUDE_DIR}
)
```

However, there is no distinction between internal and external source files (e.g. PCL, OpenCV). I propose that we add the CMake [include dirs SYSTEM flag ](https://cmake.org/cmake/help/v3.0/command/include_directories.html) so that the compiler only outputs warnings for internal source files.

Example:

```cmake
include_directories(
	include
        SYSTEM
  	  ${catkin_INCLUDE_DIRS}
	  ${PCL_INCLUDE_DIRS}
          ${OpenCV_INCLUDE_DIRS}
	  ${GTSAM_INCLUDE_DIR}
)
```

**Comment by TixiaoShan** [comment]
This sounds good to me. Please make sure this won't introduce compiling problems if using different computers or platforms.
