### ISSUE TITLE
test lio sam with carla with no noise pointcloud  and no imu noise

### ISSUE THREAD

**Issue by agusorte** [TixiaoShan/LIO-SAM#250]
I am trying to test LIO-SAM with carla simulator https://carla.readthedocs.io/en/latest/start_introduction/ without noise point cloud and noise imu. I am trying to see the performance of LIO_SAM by adding noise and comparing the results to the basic truth.

The expected output results are to have a trajectory and a map with almost zero noise in the best case, and gradually increase the noise to see the performance of the algorithm.

Results with zero noise seem to degrade in z even with no noise presence, also when I include noise at almost zero imu there are integration problems

imuAccNoise: 1.0e-07
   imuGyrNoise: 1.0e-07
   imuAccBiasN: 1.0e-07
   imuGyrBiasN: 1.0e-07
   imuGravity: 9.80511
   imuRPYWeight: 0.01

some results can be visualized here 

![image](https://user-images.githubusercontent.com/12071168/120758826-9b44e980-c512-11eb-9fc6-e7783a05b0ae.png)

**Comment by JaySlamer** [comment]
Do your mind sharing your data and your config?
