### ISSUE TITLE
IMU raw vs filtered data

### ISSUE THREAD

**Issue by Jaetriel** [TixiaoShan/LIO-SAM#251]
Hi @TixiaoShan, I was wondering if there is a particular reason why LIO-SAM uses raw IMU data and not filtered data? I think most IMUs have pretty decent Kalman Filters built-in, like Bosch BNO055 or the Microstrain one you are using, thanks

**Comment by alitekes1** [comment]
did you decide which topic will you should use? i use bno055 imu and unitree L1 lidar. Can you help me?
