### ISSUE TITLE
Wrong results using KITTI sample data

### ISSUE THREAD

**Issue by polbolso** [TixiaoShan/LIO-SAM#252]
I'm testing kitti_2011_09_30_drive_0028_synced.bag provided as sample data.

When I evaluate it with KITTI ground truth (using evo tools in tum format), there is a large error (1st and 2nd image below). 
I haven't changed anything else besides the extrinsic IMU-LiDAR as recommended.

The sample results provided on the main page of this repository (3rd image below) seem to be much more similar to the ground truth and quite better than what I obtained.
I can't understand why I'm not getting the same output if I'm using exactly the same input.

Hence, I wanted to ask how were these results obtained and if anything else must be changed. Or, alternatively, if you have any clue about what I could be doing wrong.

![traj](https://user-images.githubusercontent.com/72814058/121048197-e3843600-c7b6-11eb-9444-e6f0b425ffeb.jpg)
![ape](https://user-images.githubusercontent.com/72814058/121048212-e67f2680-c7b6-11eb-856b-b636a2565589.jpg)
![kitti-map](https://user-images.githubusercontent.com/72814058/121048223-e8e18080-c7b6-11eb-80dd-2318d27eeaec.png)

**Comment by xingyuuchen** [comment]
I got the same results as yours
