### ISSUE TITLE
Relocalization 

### ISSUE THREAD

**Issue by adamanov** [TixiaoShan/LIO-SAM#253]
Hi, 

First of all, thank you for your great work and contribution. 
After generating a successfully 3D scan map, can we re-use it for the relocalization of the robot in that environment? 
If yes, what kind of change do I need to apply?

All Best

**Comment by Sollimann** [comment]
@adamanov I curious of the same thing. Did you figure out whether or not it was possible to do re-localization in existing map?

**Comment by adamanov** [comment]
> @adamanov I curious of the same thing. Did you figure out whether or not it was possible to do re-localization in existing map?

unfortunately, I could not figure it out. But according to the paper, it was possible

**Comment by Sollimann** [comment]
Okey, thank you. Which onecdid you go with? Mabye I could consider changing our SLAM solution as well

**Comment by Sollimann** [comment]
> > @adamanov I curious of the same thing. Did you figure out whether or not it was possible to do re-localization in existing map?
> 
> 
> 
> unfortunately, I could not figure it out. I went with another slam approach 

Okey, thank you. Which onecdid you go with? Mabye I could consider changing our SLAM solution as well

**Comment by adamanov** [comment]
We went with Cartographer, since it is well documented and has integration with ROS

**Comment by adamanov** [comment]
> > > @adamanov I curious of the same thing. Did you figure out whether or not it was possible to do re-localization in existing map?
> > 
> > 
> > 
> > unfortunately, I could not figure it out. I went with another slam approach 
> 
> Okey, thank you. Which one did you go with? Mabye I could consider changing our SLAM solution as well

We went with Cartographer, since it is well documented and has integration with ROS
