### ISSUE TITLE
Unable to test with custom (own) dataset

### ISSUE THREAD

**Issue by ajay1606** [TixiaoShan/LIO-SAM#256]
Hello,
Thanks for the very much useful source. I have tested the source with a sample dataset. But unable to test with my own dataset.
Configured the topic name and frame_id as it in the sample dataset. But once running bag file getting continuous error as below. Could anyone please suggest fix this issue?

```
terminate called after throwing an instance of 'gtsam::IndeterminantLinearSystemException'
what():
Indeterminant linear system detected while working near variable
7061644215716937728 (Symbol: b0).
```

Working Platform: 
Ubuntu 18.04
GTSAM: 4.0.2

Regards,
Ajay

**Comment by SlammerD** [comment]
Check this one out https://github.com/TixiaoShan/LIO-SAM/issues/165#issuecomment-1000247782
