### ISSUE TITLE
Recorded dataset issue!

### ISSUE THREAD

**Issue by qaisarehman** [TixiaoShan/LIO-SAM#260]
Hi,

I have build and tested the lio-sam with the walk dataset. everything is perfect. But when I tried to use it with my own recorded bag file. Im getting some warnings and errors. Please if someone can see the log and point me out the issue! the IMU im using is 9aixes OpenIMU300ZI. But I got the error which tells me to use 9axis IMU. 

[log.txt](https://github.com/TixiaoShan/LIO-SAM/files/6676612/log.txt)

Thanks

**Comment by pauldeee** [comment]
I am no expert in this, but it seems like the rotation matrix you have set in your params.yaml is not valid.

This is from the file:
```
 * /lio_sam/extrinsicRPY: [0, 0, 0, 0, 0, 0...
 * /lio_sam/extrinsicRot: [0, 0, 0, 0, 0, 0...
 ```
 
Looks like your RPY and Rot matrices are full of zeroes.
