### ISSUE TITLE
point cloud delay 2 frames

### ISSUE THREAD

**Issue by simple-binary** [TixiaoShan/LIO-SAM#262]
Hello everyone,

I'm tried the liosam ros vesrion, and realize the output of cloudInfo (lio_sam/deskew/cloud_info) is delay about 208ms (process the previous point cloud after recived 2 point cloud message).
I saw the cachePointCloud() function cached 2 point cloud message(see the figure), so it delay the processing of frame at t (we projected the frame t-2). 
![Selection_133](https://user-images.githubusercontent.com/63908498/123186776-115dc000-d4c3-11eb-85e7-7ad57f847f95.png)

I have question: why we cache 2 point cloud messages? is this bug or we have a purpose?
thanks.

**Comment by p-CXTN** [comment]
My guess is that it ensures the preintegration finishes processing frames corresponding to current lidar frame or enough imu frames have come in. Just a wild guess tho, I'm not so sure.
