### ISSUE TITLE
undefined reference to `void pcl::removeNaNFromPointCloud<VelodynePointXYZIRT>(pcl::PointCloud<VelodynePointXYZIRT> const&, pcl::PointCloud<VelodynePointXYZIRT>&, std::vector<int, std::allocator<int> >&)'

### ISSUE THREAD

**Issue by qserdel** [TixiaoShan/LIO-SAM#263]
Hi,
I'm trying to use LIO-SAM with a Velodyne VLP-32 Lidar which seems to have NaN values.
I tried to remove them using :

`        vector<int> indices;`
`        pcl::removeNaNFromPointCloud(*laserCloudIn, *laserCloudIn, indices);`

but get the following error :

``undefined reference to `void pcl::removeNaNFromPointCloud<VelodynePointXYZIRT>(pcl::PointCloud<VelodynePointXYZIRT> const&, pcl::PointCloud<VelodynePointXYZIRT>&, std::vector<int, std::allocator<int> >&)     ``

Please help me I don't know what to do

**Comment by beyondpzk** [comment]
> Hi,
> I'm trying to use LIO-SAM with a Velodyne VLP-32 Lidar which seems to have NaN values.
> I tried to remove them using :
> 
> ` vector<int> indices;`
> ` pcl::removeNaNFromPointCloud(*laserCloudIn, *laserCloudIn, indices);`
> 
> but get the following error :
> 
> `` undefined reference to `void pcl::removeNaNFromPointCloud<VelodynePointXYZIRT>(pcl::PointCloud<VelodynePointXYZIRT> const&, pcl::PointCloud<VelodynePointXYZIRT>&, std::vector<int, std::allocator<int> >&) ``
> 
> Please help me I don't know what to do

Have you solved this problem? I also have met this problem.

**Comment by z1047941150** [comment]
Have you solved this problem? I have met this problem too.

**Comment by flashlau** [comment]
`
undefined reference to `void pcl::removeNaNFromPointCloud<RsPointXYZIRT>(pcl::PointCloud<RsPointXYZIRT> const&, pcl::PointCloud<RsPointXYZIRT>&, std::vector<int, std::allocator<int> >&)'
`
It was solved  by adding #include "pcl-1.8/pcl/filters/impl/filter.hpp"

**Comment by FALCONYU** [comment]
It was solved by adding #include "pcl-1.13/pcl/filters/impl/filter.hpp"

**Comment by yxxzhuzhuxia** [comment]
thanks!!!!!!!!
