### ISSUE TITLE
Use of RGB-D Sensor

### ISSUE THREAD

**Issue by SyllogismRXS** [TixiaoShan/LIO-SAM#265]
I understand that as currently written that LIO-SAM requires the use of a LIDAR. However, are there any theoretical reasons why the LIDAR couldn't be replaced with an RGB-D sensor like an Intel RealSense D435i?  What changes would have to be made to LIO-SAM to support RGB-D sensors? Are the maintainers willing to entertain pull requests that enable the use of RGB-D sensors or is that outside the scope of this project? Thanks.

**Comment by RalphCodesTheInternet** [comment]
Not completely sure about this, but looks like LIO-SAM only works with 360 degree ring lidars. So far it has not worked out with my intel realsense. Would be nice to add color to the velodyne scans though
