### ISSUE TITLE
the map will be bad when the car turning

### ISSUE THREAD

**Issue by llxClover** [TixiaoShan/LIO-SAM#280]
The imu data is in ENU(x-forword  y-left  z-up), so the two matrices are  identity matrix.
Once my car makes a turnning, the map will be overlap or flying.
lidar:  velodyne-16
IMU:  UM7
why?

![A396ACAE67B26A1EEB7ECA6170C9993A](https://user-images.githubusercontent.com/34941619/131211261-407e4a57-2568-474d-b55e-033ba8409747.jpg)
@TixiaoShan

**Comment by llxClover** [comment]
laser: velodyne16      IMU:  UM7

**Comment by llxClover** [comment]
It may be tcaused by bad time sync between the lidar and IMU.
The first figure is the timeStamp for the west.bag which is provied by author.

The last
![Uploading 2.jpg…]()
![Uploading 2.jpg…]()
 figure  is the timeStamp for the Lee.bag which is recorded myself.
but, how to resolve the bad time sync?

**Comment by llxClover** [comment]
I have resolved the trouble, but the method is offline.
I have sync the Lee.bag by python:

#!/usr/bin/env python2

import rospy
import rosbag
import sys
import datetime
import time

if sys.getdefaultencoding() != 'utf-8':
    reload(sys)
    sys.setdefaultencoding('utf-8')
bag_name = 'Lee.bag' 
out_bag_name = 'Lee_correct.bag' 
dst_dir = '/home/dt/Downloads/data/Lee/'

with rosbag.Bag(dst_dir+out_bag_name, 'w') as outbag:
    
    for topic, msg, t in rosbag.Bag(dst_dir+bag_name).read_messages():
        if topic =='/imu/data':
            stampFlag = msg.header.stamp
            outbag.write(topic, msg, msg.header.stamp)
        elif topic =='/imu/data_raw':
            outbag.write(topic, msg, msg.header.stamp)
        elif topic == '/velodyne_points':
            msg.header.stamp = stampFlag
            outbag.write(topic, msg, msg.header.stamp)

print("finished")
 
![Screenshot 2021-08-29 09:17:37](https://user-images.githubusercontent.com/34941619/131235061-67585302-4d43-490c-b487-18c952035137.png)

**Comment by Jaetriel** [comment]
> It may be caused by bad time sync between the lidar and IMU.
> The figure is the timeStamp for the west.bag which is provied by author.
> ![作者对齐](https://user-images.githubusercontent.com/34941619/131215000-8129abf0-edf0-4db4-88bb-3df579ad3ca8.jpg)
> The figure is the timeStamp for the Lee.bag which is recorded myself.
> ![自己未对齐](https://user-images.githubusercontent.com/34941619/131215008-664d14db-89bc-485f-9947-9bad8787c794.jpg)
> but, how to resolve the bad time sync?

Hey, can I ask what tool you are using in the figure to check the time sync between IMU and lidar?

**Comment by FishInWave** [comment]
> > It may be caused by bad time sync between the lidar and IMU.
> > The figure is the timeStamp for the west.bag which is provied by author.
> > ![作者对齐](https://user-images.githubusercontent.com/34941619/131215000-8129abf0-edf0-4db4-88bb-3df579ad3ca8.jpg)
> > The figure is the timeStamp for the Lee.bag which is recorded myself.
> > ![自己未对齐](https://user-images.githubusercontent.com/34941619/131215008-664d14db-89bc-485f-9947-9bad8787c794.jpg)
> > but, how to resolve the bad time sync?
> 
> Hey, can I ask what tool you are using in the figure to check the time sync between IMU and lidar?

rosrun rqt_bag rqt_bag

**Comment by llxClover** [comment]
rqt_bag&nbsp; &nbsp; *.bag



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 3, 2021 21:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TixiaoShan/LIO-SAM] the map will be bad when the car turning (#280)




   
It may be caused by bad time sync between the lidar and IMU.
 The figure is the timeStamp for the west.bag which is provied by author.
 
 The figure is the timeStamp for the Lee.bag which is recorded myself.
 
 but, how to resolve the bad time sync?
  
Hey, can I ask what tool you are using in the figure to check the time sync between IMU and lidar?
  
rosrun rqt_bag rqt_bag
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by llxClover** [comment]
> > > It may be caused by bad time sync between the lidar and IMU.
> > > The figure is the timeStamp for the west.bag which is provied by author.
> > > ![作者对齐](https://user-images.githubusercontent.com/34941619/131215000-8129abf0-edf0-4db4-88bb-3df579ad3ca8.jpg)
> > > The figure is the timeStamp for the Lee.bag which is recorded myself.
> > > ![自己未对齐](https://user-images.githubusercontent.com/34941619/131215008-664d14db-89bc-485f-9947-9bad8787c794.jpg)
> > > but, how to resolve the bad time sync?
> > 
> > 
> > Hey, can I ask what tool you are using in the figure to check the time sync between IMU and lidar?
> 
> rosrun rqt_bag rqt_bag

rqt_bag *.bag

**Comment by Jaetriel** [comment]
thank you, do you think this is an efficient way to time sync the data? I think it should be possible to achieve sensor synchronization real-time without having to rely on such a script, even though it seems to do a great job

**Comment by llxClover** [comment]
I'm sorry！ I don't know how to do， but I have run LIO-SAM real-time by a ros-node successfully which is same to&nbsp; the script.



---Original---
From: "Nikola ***@***.***&gt;
Date: Fri, Sep 3, 2021 22:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TixiaoShan/LIO-SAM] the map will be bad when the car turning (#280)




 
thank you, do you think this is an efficient way to time sync the data? I think it should be possible to achieve sensor synchronization real-time without having to rely on such a script, even though it seems to do a great job
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FishInWave** [comment]
> I'm sorry！ I don't know how to do， but I have run LIO-SAM real-time by a ros-node successfully which is same to&nbsp; the script.
> […](#)
> ---Original--- From: "Nikola ***@***.***&gt; Date: Fri, Sep 3, 2021 22:57 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [TixiaoShan/LIO-SAM] the map will be bad when the car turning (#280) thank you, do you think this is an efficient way to time sync the data? I think it should be possible to achieve sensor synchronization real-time without having to rely on such a script, even though it seems to do a great job — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Your IMU seems like running at 20Hz, which is so low. Usually, IMU runs at 100Hz or higher. I think maybe this is the reason why time-synchronization is so important for your bag.

**Comment by llxClover** [comment]
> > I'm sorry！ I don't know how to do， but I have run LIO-SAM real-time by a ros-node successfully which is same to  the script.
> > […](#)
> > ---Original--- From: "Nikola _**@**_._**> Date: Fri, Sep 3, 2021 22:57 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [TixiaoShan/LIO-SAM] the map will be bad when the car turning (#280) thank you, do you think this is an efficient way to time sync the data? I think it should be possible to achieve sensor synchronization real-time without having to rely on such a script, even though it seems to do a great job — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> Your IMU seems like running at 20Hz, which is so low. Usually, IMU runs at 100Hz or higher. I think maybe this is the reason why time-synchronization is so important for your bag.

“ However the um7_driver has a default configuration which sets the transmission rate of all the parameters to 20 hz”。Haha， I used a default configuration. 
Thank you!

**Comment by Jaetriel** [comment]
did this way of timesyncing improve the quality of your data drastically? it seems a bit brute force to me

**Comment by llxClover** [comment]
yes，it&nbsp;improves the quality of mapping

---Original---
From: "Nikola ***@***.***&gt;
Date: Mon, Sep 6, 2021 18:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TixiaoShan/LIO-SAM] the map will be bad when the car turning (#280)




 
did this way of timesyncing a drastically? it seems a bit brute force to me
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Jaetriel** [comment]
@llxClover thank you I think I might give it a try on my own data to see if I get better results

**Comment by Huguet57** [comment]
Had the same problem with working with a IMU at 20Hz! Definitely was solved when going to 200Hz. @llxClover if you find that timesyncing improves the map that would be a huge discover. However in the README it specifically says that the IMU should work at a minimum of 200Hz rate.

**Comment by wienans** [comment]
100 Hz works well too
