### ISSUE TITLE
double free or corruption

### ISSUE THREAD

**Issue by jhch1995** [TixiaoShan/LIO-SAM#281]
Hi ,Im sorry to trouble you, but I have followed the step for installation but I encountered the follow problem.I install the gtsam which version is  4.0.3. I'm not sure the reason which causes this problem. Look forward to your reply！

This is the ros log which shows on the terminal. 
[ INFO] [1630807920.218335937]: ----> Feature Extraction Started.
*** Error in `/home/jianghc/catkin_avp/devel/lib/lio_sam/lio_sam_featureExtraction': double free or corruption (out): 0x00000000011e3dc0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777f5)[0x7f8083ecc7f5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8038a)[0x7f8083ed538a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f8083ed958c]
/home/jianghc/catkin_avp/devel/lib/lio_sam/lio_sam_featureExtraction(_ZN5boost6detail17sp_counted_impl_pIN3pcl10PointCloudINS2_9PointXYZIEEEE7disposeEv+0x49)[0x410069]
/home/jianghc/catkin_avp/devel/lib/lio_sam/lio_sam_featureExtraction[0x40ed4a]
/home/jianghc/catkin_avp/devel/lib/lio_sam/lio_sam_featureExtraction(_ZN17FeatureExtraction15extractFeaturesEv+0xcc8)[0x41f458]
/home/jianghc/catkin_avp/devel/lib/lio_sam/lio_sam_featureExtraction(_ZN17FeatureExtraction21laserCloudInfoHandlerERKN5boost10shared_ptrIKN7lio_sam11cloud_info_ISaIvEEEEE+0x590)[0x420980]
/home/jianghc/catkin_avp/devel/lib/lio_sam/lio_sam_featureExtraction(_ZN5boost6detail8function26void_function_obj_invoker1INS_8functionIFvRKNS_10shared_ptrIKN7lio_sam11cloud_info_ISaIvEEEEEEEEvSA_E6invokeERNS1_15function_bufferESA_+0x2b)[0x417a0b]
/home/jianghc/catkin_avp/devel/lib/lio_sam/lio_sam_featureExtraction(_ZN3ros27SubscriptionCallbackHelperTIRKN5boost10shared_ptrIKN7lio_sam11cloud_info_ISaIvEEEEEvE4callERNS_36SubscriptionCallbackHelperCallParamsE+0x28e)[0x4228ce]
/opt/ros/kinetic/lib/libroscpp.so(_ZN3ros17SubscriptionQueue4callEv+0xadd)[0x7f80877a1d8d]
/opt/ros/kinetic/lib/libroscpp.so(_ZN3ros13CallbackQueue9callOneCBEPNS0_3TLSE+0x4b8)[0x7f8087747838]
/opt/ros/kinetic/lib/libroscpp.so(_ZN3ros13CallbackQueue13callAvailableENS_12WallDurationE+0x54b)[0x7f808774923b]
/opt/ros/kinetic/lib/libroscpp.so(_ZN3ros21SingleThreadedSpinner4spinEPNS_13CallbackQueueE+0x2a9)[0x7f80877a5e39]
/opt/ros/kinetic/lib/libroscpp.so(_ZN3ros4spinEv+0x2b)[0x7f808778ae9b]
/home/jianghc/catkin_avp/devel/lib/lio_sam/lio_sam_featureExtraction(main+0xa6)[0x40e7b6]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f8083e75840]
/home/jianghc/catkin_avp/devel/lib/lio_sam/lio_sam_featureExtraction(_start+0x29)[0x40eb59]
======= Memory map: ========
00400000-0042c000 r-xp 00000000 08:04 9591394                            /home/jianghc/catkin_avp/devel/lib/lio_sam/lio_sam_featureExtraction
0062b000-0062c000 r--p 0002b000 08:04 9591394                            /home/jianghc/catkin_avp/devel/lib/lio_sam/lio_sam_featureExtraction
0062c000-0062d000 rw-p 0002c000 08:04 9591394                            /home/jianghc/catkin_avp/devel/lib/lio_sam/lio_sam_featureExtraction
00fdc000-013bd000 rw-p 00000000 00:00 0                                  [heap]
7f8058000000-7f8058021000 rw-p 00000000 00:00 0 
7f8058021000-7f805c000000 ---p 00000000 00:00 0 
7f8060000000-7f8060021000 rw-p 00000000 00:00 0 
7f8060021000-7f8064000000 ---p 00000000 00:00 0 
7f8064000000-7f8064021000 rw-p 00000000 00:00 0 
7f8064021000-7f8068000000 ---p 00000000 00:00 0 
7f8068000000-7f8068021000 rw-p 00000000 00:00 0 
7f8068021000-7f806c000000 ---p 00000000 00:00 0 
7f806effe000-7f806efff000 ---p 00000000 00:00 0 
7f806efff000-7f806f7ff000 rw-p 00000000 00:00 0 
7f806f7ff000-7f806f800000 ---p 00000000 00:00 0 
7f806f800000-7f8070000000 rw-p 00000000 00:00 0 
7f8070000000-7f8070021000 rw-p 00000000 00:00 0 
7f8070021000-7f8074000000 ---p 00000000 00:00 0 
7f807443c000-7f807443d000 ---p 00000000 00:00 0 
7f807443d000-7f8074c3d000 rw-p 00000000 00:00 0 
7f8074c3d000-7f8074c3e000 ---p 00000000 00:00 0 
7f8074c3e000-7f807543e000 rw-p 00000000 00:00 0 
7f807543e000-7f8075449000 r-xp 00000000 103:07 160579                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f8075449000-7f8075648000 ---p 0000b000 103:07 160579                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f8075648000-7f8075649000 r--p 0000a000 103:07 160579                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f8075649000-7f807564a000 rw-p 0000b000 103:07 160579                    /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f807564a000-7f8075650000 rw-p 00000000 00:00 0

**Comment by HaisenbergPeng** [comment]
try pcl1.7 instead of pcl1.8
