### ISSUE TITLE
Some questions about surface feature extraction

### ISSUE THREAD

**Issue by BLB0803** [TixiaoShan/LIO-SAM#283]
Hello, Shan, I had read the article and watched the LIO-SAM and LVI-SAM demo on YouTube, there are amazing work.

And I'm reading the codes to get further understanding of whole system now.

BUT, I found something really confusing me, at

[featureExtraction.cpp](https://github.com/TixiaoShan/LIO-SAM/blob/master/src/featureExtraction.cpp), function `extractFeatures()`,  **line 202,**

I saw that a point belongs to planar feature will be labeled as -1 in the array called `cloudLabel`.

In which part makes me confused is, at **line 227** of [featureExtraction.cpp](https://github.com/TixiaoShan/LIO-SAM/blob/master/src/featureExtraction.cpp),  below the labeling part mentioned before, 

`if (cloudLabel[k] <= 0){
     surfaceCloudScan->push_back(extractedCloud->points[k]);
}`

It seems like you chosed not only points  labeled as -1 but also labeled as 0.

To check out this part, I visualized the  `surfaceCloud` that published by the publisher called `pubSurfacePoints` at rviz, here's the result:

![Screenshot from 2021-09-27 16-07-16](https://user-images.githubusercontent.com/42734518/134869148-f9e1b3f2-7245-4d58-8f06-73ef80b5865b.png)

Some points should not belongs to planar feature(like points of trees) had been extracted, cuz of pushing not only -1 but also 0 labeled points into surfaceCloudScan.

So I tryed to change 
`if (cloudLabel[k] <= 0){
     surfaceCloudScan->push_back(extractedCloud->points[k]);
}`
with
`if (cloudLabel[k] < 0){
     surfaceCloudScan->push_back(extractedCloud->points[k]);
}`

to save planar features properly, and the visualize result like below:
![Screenshot from 2021-09-27 16-20-11](https://user-images.githubusercontent.com/42734518/134871871-d903ac23-385c-4c6e-8b32-86f5d6127255.png)

It seems like extracted some "real" planar features, although are sparse.

But after I changed that, **every time** when I test with the dataset named **campus_large_dataset.bag**, 

It crashed at the timestamp of`[PAUSED ]  Bag Time: 1572807852.632124   Duration: 430.792850 / 994.965750 `like below:

![Screenshot from 2021-09-27 16-35-01](https://user-images.githubusercontent.com/42734518/134874269-843b6136-caf6-4f5d-af30-4b2db425b734.png)

![Screenshot from 2021-09-27 16-38-51](https://user-images.githubusercontent.com/42734518/134874349-07e66d96-6b69-472b-af0b-61853a463453.png)

Although  I had double checked the `/config/params.yaml` to ensure parameters were configured properly.

And the WARN message is:

`[ WARN] [1632731906.350954159]: Large velocity, reset IMU-preintegration!`

Maybe it's because of lacking of features after I changed code like that, I guess.

Is this a bug or just I misunderstood the codes of that part?  Because I had checked the same part of LVI-SAM at [featureExtraction.cpp](https://github.com/TixiaoShan/LVI-SAM/blob/master/src/lidar_odometry/featureExtraction.cpp), it's exactly the same as:

`if (cloudLabel[k] <= 0){
     surfaceCloudScan->push_back(extractedCloud->points[k]);
}`

But in my opinion, a points labeled as '0' should not belongs to planar feature, since the value of each points in the label container `cloudLabel`, would be initialized as 0 by default.

So how could I fix this problem? Expecting for your reply.

**Comment by Huguet57** [comment]
Hi,
I do not know the reasoning behind this part of the code but isn't true that if we take the edges of a cloud, everything else would belong in the surface category? I guess this is because it's easier to pinpoint which points belong to the edges (because they are normally singular discontinuities) that which ones belong to surfaces (because we do not have continuous resolution). So I guess classifying points that are definitely edges (1), that are definitely surfaces (-1) and the rest that might belong to surfaces (0) is what is being done here.

**Comment by AlexReimann** [comment]
fyi:
From my experience the `degenerate` check can make issues if the amount of points is small:
https://github.com/TixiaoShan/LIO-SAM/blob/3a3d82fac4ba614ff2324be4ef83381b4256cc48/src/mapOptmization.cpp#L1225-L1247

When turning it off, the small campus dataset worked fine.
