### ISSUE TITLE
The map is overlapping while looping, why?

### ISSUE THREAD

**Issue by XinrunChao** [TixiaoShan/LIO-SAM#285]
lidar: lslidar-16(10Hz)
IMU: sanchi(100Hz)
While looping, the map is overlapping, how to correct it, or some tips for mapping?
Thank you!

![image](https://user-images.githubusercontent.com/35392119/137433647-bf56e467-7181-44d2-8e33-33090aa8fce8.png)

**Comment by zhouqigao** [comment]
hi,I also had the same problem before, but then I changed the starting point and walked around again,this overlapping phenomenon disappeared , which is very strange.do you have any solution now?

> lidar: lslidar-16(10Hz) IMU: sanchi(100Hz) While looping, the map is overlapping, how to correct it, or some tips for mapping? Thank you!
> 
> ![image](https://user-images.githubusercontent.com/35392119/137433647-bf56e467-7181-44d2-8e33-33090aa8fce8.png)

**Comment by JACKLiuDay** [comment]
I have the same problem. When the test area is undulating terrain, the map will overlap at the looping point.
