### ISSUE TITLE
error while loading shared libraries: libGeographic.so.19

### ISSUE THREAD

**Issue by ZhangZh3ng** [TixiaoShan/LIO-SAM#287]
Error info:
/opt/ros/noetic/lib/robot_localization/navsat_transform_node: error while loading shared libraries: libGeographic.so.19: cannot open shared object file: No such file or directory
log4cxx: Could not read configuration file [/home/zz/??????/cpp_project/LIO_SAM_ws/src/LIO-SAM/launch/include/rosconsole/rosconsole_error.conf].
process[lio_sam_rviz-9]: started with pid [53535]
[navsat-8] process has died [pid 53530, exit code 127, cmd /opt/ros/noetic/lib/robot_localization/navsat_transform_node imu/data:=imu_correct gps/fix:=gps/fix odometry/filtered:=odometry/navsat __name:=navsat __log:=/home/zz/.ros/log/a1ca73aa-332c-11ec-ba59-178e13b8db7e/navsat-8.log].
log file: /home/zz/.ros/log/a1ca73aa-332c-11ec-ba59-178e13b8db7e/navsat-8*.log

It seems caused by the the missing of libGeographic, but I do have installed it:
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/lib/libGeographic.so.19.2.0
-- Up-to-date: /usr/local/lib/libGeographic.so.19
-- Up-to-date: /usr/local/lib/libGeographic.so
...

Who can give me some advise? Thank you very much!

**Comment by SebastianTroy** [comment]
How did you resolve this?

**Comment by 1213881262** [comment]
The following method may be useful:
Step 1: cd to your workspace directory
Step 2: check dependencies for the entire workspace: 
`rosdep check --from-path src --ignore-src -r -y`
Step 3: Install dependencies: 
`rosdep install --from-path src --ignore-src -r -y`
