### ISSUE TITLE
Walking dataset can't be runned.

### ISSUE THREAD

**Issue by ZhangZh3ng** [TixiaoShan/LIO-SAM#288]
Thank you for sharing this great work! I had successfully run on the park_dataset.bag, but when I tried on the walk_dataset, this error occurred:
$ rosbag play /home/zz/DataSet/lio_sam_provided/walking_dataset.bag -r 3
[ INFO] [1634904842.491227370]: Opening /home/zz/DataSet/lio_sam_provided/walking_dataset.bag
[FATAL] [1634904842.506633811]: Error reading version line

It will be appreciate it if you can give some advice, thanks!

**Comment by adijams01** [comment]
Hello,
can you explain how were you able to solve this?
