### ISSUE TITLE
why not using the result of 'imuIntegratorOpt_' as the final output?

### ISSUE THREAD

**Issue by 925779599** [TixiaoShan/LIO-SAM#291]
Thanks for you Open source your algorithm.There is two question.
ONE：I think that you using the result of 'mapOptmization.cpp'  (topic 'lio_sam/mapping/odometry') as the final result,I think that it's like a LO result.I think that the result of 'imuIntegratorOpt_' is the LO and IMU Preintegration optimize result , by reason,this should be more accurate.But in my dateset it‘s accuracy is not as good as the result of 'mapOptmization.cpp'  (topic 'lio_sam/mapping/odometry') .why not using the result of 'imuIntegratorOpt_' as the final output?and why it's not accuracy as good as the result of 'mapOptmization.cpp'.
TWO：I think that it's better to use between factor rather than prior factor  in 'imuIntegratorOpt_' to lead in LO（'mapOptmization.cpp'  (topic 'lio_sam/mapping/odometry') ),when run a long time the LO attitude will drift,the prior factor constraint will lead to imu acceleration bias drift.In my dataset it's more bad.Why not use the between factor?and why it‘s bad than prior factor？
Any reply will help!

**Comment by YoshuaNava** [comment]
Hi there!

I thought your question was quite interesting and I tried myself to replace the prior factors with between factors.

However, I found that this led to instability.
* The Lidar pose prior factors are an absolute anchor, with invariant values, which can be used by the preintegration front-end to constrain the problem between two IMU propagated values.

* When we transform the lidar priors into between factors, they **lose their invariance**, and if you are e.g. in a zero-velocity scenario and you don't take any **explicit action**, propagating the graph values with IMU measurements (with are noisy) will slowly **drag** the between factors away, and potentially lead to a positive feedback loop :boom:
