### ISSUE TITLE
Question on cornerOptimization()

### ISSUE THREAD

**Issue by mysterybc** [TixiaoShan/LIO-SAM#293]
Hi,
  I want to consult you about the details of the cornerOptimization() function, I can understand **a012/l12** represents the distance between the corner point and the corresponding edge line, but what does **la**, **lb**, and **lc** mean? According to mathematical calculations, **la** represents the angle between the projection of normal vector of the plane composed of three points and the corresponding edge on the YZ plane, but I don’t quite understand its physical meaning. Hope you could help me with that. Thanks!

**Comment by xmqv0913** [comment]
maybe the derivatives of distance with respect to the corner point.
