### ISSUE TITLE
Problem in running walking dataset

### ISSUE THREAD

**Issue by tejalbarnwal** [TixiaoShan/LIO-SAM#295]
![image](https://user-images.githubusercontent.com/64950661/144452122-fff03df8-4a76-496f-877d-8e633add899c.png)
Do I have to manually provide a transform between base_link and map frame?
also, the visualization space in rviz remains black though I change the global frame. How can I solve this problem?
Thankyou for helping!

**Comment by tejalbarnwal** [comment]
I figured out the error.

**Comment by dsb6063** [comment]
What was the error?

**Comment by tejalbarnwal** [comment]
It was the topic in the ros bag for imu was different than the one I used in YAML file
