### ISSUE TITLE
Warning faced in all the datasets

### ISSUE THREAD

**Issue by tejalbarnwal** [TixiaoShan/LIO-SAM#296]
I see this  `[ WARN] [1638465495.017856149]: Large velocity, reset IMU-preintegration!` popping up for any dataset I try. What is the reason behind this? Should I lower the rate at which the bagfile is run?

**Comment by jefftian666** [comment]
I have the same error, Do you solved it?

**Comment by tejalbarnwal** [comment]
No, I wasn't able to

**Comment by SlammerD** [comment]
Have you checked your imu data? Most common reason ist that your extrinsics are wrong. Have you adapted the extrinsics 
in the params.yaml?
