### ISSUE TITLE
Maps cannot overlap

### ISSUE THREAD

**Issue by AntarcticaSkj** [TixiaoShan/LIO-SAM#298]
Hi. When I run lio-sam in Gazebo simulation environment, the maps cannot overlap.

![wrong scene](https://user-images.githubusercontent.com/53070328/146391343-b25f8e42-2c86-4a9f-83df-dc9adf355a2b.png)

Here are my[ _.xacro_ files and _params.yaml_ files](https://github.com/AntarcticaSkj/flie-about-LIO-SAM):
https://github.com/AntarcticaSkj/flie-about-LIO-SAM

**Comment by PengXinli** [comment]
Hello,I also had the same problem,did you solve it?
