### ISSUE TITLE
imu linear acceleration sign

### ISSUE THREAD

**Issue by Mediumcore** [TixiaoShan/LIO-SAM#300]
Great work,thanks for sharing,but i am confused by imu direction.
Why imu linear acceleration sign is positive is ROS x-forward ,y-left,z-up frame? 
Because gravity is 9.8 m/s2 down,why in ros z-up linear acceleration is 9.8 positive, it's not obeying physics law.

**Comment by SlammerD** [comment]
Look into the REP 145. It is a convention to show gravity positively although the z-axis of the body is pointing upwards.
