### ISSUE TITLE
I had this problem too. In my case the reason was that some imu messages were sent with the same timestamp. This causes trouble in imuPreintegration.cpp lines 356, 424 and 469. As you can see there is no check if the imuTime - lastimuTime is equal to 0. So in my case dt gets 0 which then in turn leads to the fact that in gtsam the systems of equations can no longer be solved.

### ISSUE THREAD

**Issue by lijian636** [TixiaoShan/LIO-SAM#303]
I had this problem too. In my case the reason was that some imu messages were sent with the same timestamp. This causes trouble in imuPreintegration.cpp lines 356, 424 and 469. As you can see there is no check if the imuTime - lastimuTime is equal to 0. So in my case dt gets 0 which then in turn leads to the fact that in gtsam the systems of equations can no longer be solved.
My solution simply was to make sure imuTime - lastImuTime is not 0 before I set it as new dt.

_Originally posted by @SlammerD in https://github.com/TixiaoShan/LIO-SAM/issues/165#issuecomment-1000247782_
Hello, I also encountered the same problem. It is said that the code has been modified, or the same style. What else may have gone wrong?

**Comment by SlammerD** [comment]
I'm not sure if I understand you correctly. If your question ist how I modified my code, I for example changed line 356 from
double dt = (lastImuT_opt < 0) ? (1.0 / 500.0) : (imuTime - lastImuT_opt);
to
double dt = (lastImuT_opt < 0 || (imuTime - lastImuT_opt) <= 0) ? (1.0 / 500) : (imuTime - lastImuT_opt);
