### ISSUE TITLE
error after bulding enviroment - catkin_make

### ISSUE THREAD

**Issue by macnack** [TixiaoShan/LIO-SAM#318]
Im using Ubuntu 18.04.6 LTS. Melodic ROS, acording to readme after catkin_make, i get answer: 
`Base path: /home/macko-pc/catkin_ws
Source space: /home/macko-pc/catkin_ws/src
Build space: /home/macko-pc/catkin_ws/build
Devel space: /home/macko-pc/catkin_ws/devel
Install space: /home/macko-pc/catkin_ws/install
Creating symlink "/home/macko-pc/catkin_ws/src/CMakeLists.txt" pointing to "/opt/ros/melodic/share/catkin/cmake/toplevel.cmake"
####
####
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/macko-pc/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/macko-pc/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - lio_sam
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'lio_sam'
-- ==> add_subdirectory(LIO-SAM)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Checking for module 'eigen3'
--   Found eigen3, version 3.3.4
-- Found eigen: /usr/include/eigen3  
-- Checking for module 'libopenni'
--   Found libopenni, version 1.5.4.0
-- Found openni: /usr/lib/libOpenNI.so  
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.3/VTKTargets.cmake"
but not all the files it references.

-- Found libusb-1.0: /usr/include  
-- Checking for module 'flann'
--   Found flann, version 1.9.1
-- Found Flann: /usr/lib/x86_64-linux-gnu/libflann_cpp_s.a  
-- Found qhull: /usr/lib/x86_64-linux-gnu/libqhull.so  
-- Found PCL_COMMON: /usr/lib/x86_64-linux-gnu/libpcl_common.so  
-- Found PCL_OCTREE: /usr/lib/x86_64-linux-gnu/libpcl_octree.so  
-- Found PCL_IO: /usr/lib/x86_64-linux-gnu/libpcl_io.so  
-- Found PCL_KDTREE: /usr/lib/x86_64-linux-gnu/libpcl_kdtree.so  
-- Found PCL_SEARCH: /usr/lib/x86_64-linux-gnu/libpcl_search.so  
-- Found PCL_SAMPLE_CONSENSUS: /usr/lib/x86_64-linux-gnu/libpcl_sample_consensus.so  
-- Found PCL_FILTERS: /usr/lib/x86_64-linux-gnu/libpcl_filters.so  
-- Found PCL_2D: /usr/include/pcl-1.8  
-- Found PCL_GEOMETRY: /usr/include/pcl-1.8  
-- Found PCL_FEATURES: /usr/lib/x86_64-linux-gnu/libpcl_features.so  
-- Found PCL_ML: /usr/lib/x86_64-linux-gnu/libpcl_ml.so  
-- Found PCL_SEGMENTATION: /usr/lib/x86_64-linux-gnu/libpcl_segmentation.so  
-- Found PCL_VISUALIZATION: /usr/lib/x86_64-linux-gnu/libpcl_visualization.so  
-- Found PCL_SURFACE: /usr/lib/x86_64-linux-gnu/libpcl_surface.so  
-- Found PCL_REGISTRATION: /usr/lib/x86_64-linux-gnu/libpcl_registration.so  
-- Found PCL_KEYPOINTS: /usr/lib/x86_64-linux-gnu/libpcl_keypoints.so  
-- Found PCL_TRACKING: /usr/lib/x86_64-linux-gnu/libpcl_tracking.so  
-- Found PCL_RECOGNITION: /usr/lib/x86_64-linux-gnu/libpcl_recognition.so  
-- Found PCL_STEREO: /usr/lib/x86_64-linux-gnu/libpcl_stereo.so  
-- Found PCL_APPS: /usr/lib/x86_64-linux-gnu/libpcl_apps.so  
-- Found PCL_IN_HAND_SCANNER: /usr/include/pcl-1.8  
-- Found PCL_MODELER: /usr/include/pcl-1.8  
-- Found PCL_POINT_CLOUD_EDITOR: /usr/include/pcl-1.8  
-- Found PCL_OUTOFCORE: /usr/lib/x86_64-linux-gnu/libpcl_outofcore.so  
-- Found PCL_PEOPLE: /usr/lib/x86_64-linux-gnu/libpcl_people.so  
-- GTSAM include directory:  /usr/lib/cmake/GTSAM/../../../include
-- lio_sam: 1 messages, 1 services
CMake Warning at /opt/ros/melodic/share/catkin/cmake/catkin_package.cmake:166 (message):
  catkin_package() DEPENDS on 'GTSAM' but neither 'GTSAM_INCLUDE_DIRS' nor
  'GTSAM_LIBRARIES' is defined.
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  LIO-SAM/CMakeLists.txt:49 (catkin_package)

-- Configuring done
CMake Warning (dev) at LIO-SAM/CMakeLists.txt:95 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "lio_sam_mapOptmization" links to target "Boost::timer" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at LIO-SAM/CMakeLists.txt:101 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "lio_sam_imuPreintegration" links to target "Boost::timer" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/macko-pc/catkin_ws/build
####
####
Scanning dependencies of target nav_msgs_generate_messages_eus
Scanning dependencies of target geometry_msgs_generate_messages_eus
Scanning dependencies of target std_msgs_generate_messages_eus
Scanning dependencies of target _lio_sam_generate_messages_check_deps_cloud_info
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target nav_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_eus
Scanning dependencies of target sensor_msgs_generate_messages_eus
Scanning dependencies of target nav_msgs_generate_messages_lisp
Scanning dependencies of target _lio_sam_generate_messages_check_deps_save_map
[  0%] Built target sensor_msgs_generate_messages_eus
[  0%] Built target nav_msgs_generate_messages_lisp
[  0%] Built target _lio_sam_generate_messages_check_deps_cloud_info
Scanning dependencies of target geometry_msgs_generate_messages_lisp
Scanning dependencies of target std_msgs_generate_messages_lisp
Scanning dependencies of target sensor_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target _lio_sam_generate_messages_check_deps_save_map
Scanning dependencies of target nav_msgs_generate_messages_cpp
Scanning dependencies of target geometry_msgs_generate_messages_cpp
Scanning dependencies of target std_msgs_generate_messages_cpp
[  0%] Built target nav_msgs_generate_messages_cpp
Scanning dependencies of target sensor_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_cpp
Scanning dependencies of target nav_msgs_generate_messages_nodejs
[  0%] Built target sensor_msgs_generate_messages_cpp
Scanning dependencies of target geometry_msgs_generate_messages_nodejs
Scanning dependencies of target sensor_msgs_generate_messages_nodejs
[  0%] Built target nav_msgs_generate_messages_nodejs
Scanning dependencies of target std_msgs_generate_messages_nodejs
[  0%] Built target sensor_msgs_generate_messages_nodejs
Scanning dependencies of target nav_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_nodejs
Scanning dependencies of target sensor_msgs_generate_messages_py
[  0%] Built target nav_msgs_generate_messages_py
Scanning dependencies of target geometry_msgs_generate_messages_py
Scanning dependencies of target std_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_py
Scanning dependencies of target tf2_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_py
Scanning dependencies of target tf_generate_messages_py
[  0%] Built target tf2_msgs_generate_messages_nodejs
Scanning dependencies of target actionlib_generate_messages_cpp
[  0%] Built target tf_generate_messages_py
Scanning dependencies of target roscpp_generate_messages_cpp
Scanning dependencies of target rosgraph_msgs_generate_messages_cpp
[  0%] Built target actionlib_generate_messages_cpp
Scanning dependencies of target tf_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_cpp
Scanning dependencies of target actionlib_generate_messages_lisp
[  0%] Built target tf_generate_messages_nodejs
Scanning dependencies of target rosgraph_msgs_generate_messages_eus
Scanning dependencies of target actionlib_msgs_generate_messages_cpp
Scanning dependencies of target tf_generate_messages_eus
[  0%] Built target actionlib_generate_messages_lisp
[  0%] Built target rosgraph_msgs_generate_messages_eus
[  0%] Built target actionlib_msgs_generate_messages_cpp
[  0%] Built target tf_generate_messages_eus
Scanning dependencies of target rosgraph_msgs_generate_messages_nodejs
Scanning dependencies of target roscpp_generate_messages_lisp
Scanning dependencies of target tf_generate_messages_lisp
Scanning dependencies of target roscpp_generate_messages_py
[  0%] Built target tf_generate_messages_lisp
[  0%] Built target rosgraph_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_lisp
[  0%] Built target roscpp_generate_messages_py
Scanning dependencies of target visualization_msgs_generate_messages_nodejs
Scanning dependencies of target visualization_msgs_generate_messages_lisp
Scanning dependencies of target _catkin_empty_exported_target
Scanning dependencies of target roscpp_generate_messages_nodejs
[  0%] Built target visualization_msgs_generate_messages_lisp
[  0%] Built target visualization_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_nodejs
[  0%] Built target _catkin_empty_exported_target
Scanning dependencies of target roscpp_generate_messages_eus
Scanning dependencies of target rosgraph_msgs_generate_messages_py
Scanning dependencies of target actionlib_msgs_generate_messages_eus
Scanning dependencies of target actionlib_msgs_generate_messages_lisp
[  0%] Built target roscpp_generate_messages_eus
[  0%] Built target actionlib_msgs_generate_messages_eus
[  0%] Built target rosgraph_msgs_generate_messages_py
[  0%] Built target actionlib_msgs_generate_messages_lisp
Scanning dependencies of target actionlib_msgs_generate_messages_py
Scanning dependencies of target actionlib_msgs_generate_messages_nodejs
Scanning dependencies of target tf2_msgs_generate_messages_cpp
Scanning dependencies of target actionlib_generate_messages_py
[  0%] Built target actionlib_msgs_generate_messages_py
[  0%] Built target actionlib_msgs_generate_messages_nodejs
[  0%] Built target tf2_msgs_generate_messages_cpp
[  0%] Built target actionlib_generate_messages_py
Scanning dependencies of target tf2_msgs_generate_messages_py
Scanning dependencies of target pcl_msgs_generate_messages_cpp
Scanning dependencies of target pcl_msgs_generate_messages_eus
Scanning dependencies of target actionlib_generate_messages_nodejs
[  0%] Built target tf2_msgs_generate_messages_py
[  0%] Built target pcl_msgs_generate_messages_cpp
[  0%] Built target pcl_msgs_generate_messages_eus
[  0%] Built target actionlib_generate_messages_nodejs
Scanning dependencies of target tf_generate_messages_cpp
Scanning dependencies of target pcl_msgs_generate_messages_lisp
Scanning dependencies of target actionlib_generate_messages_eus
Scanning dependencies of target pcl_msgs_generate_messages_py
[  0%] Built target pcl_msgs_generate_messages_lisp
[  0%] Built target tf_generate_messages_cpp
[  0%] Built target actionlib_generate_messages_eus
[  0%] Built target pcl_msgs_generate_messages_py
Scanning dependencies of target tf2_msgs_generate_messages_lisp
Scanning dependencies of target pcl_msgs_generate_messages_nodejs
Scanning dependencies of target tf2_msgs_generate_messages_eus
Scanning dependencies of target visualization_msgs_generate_messages_cpp
[  0%] Built target tf2_msgs_generate_messages_lisp
[  0%] Built target pcl_msgs_generate_messages_nodejs
[  0%] Built target tf2_msgs_generate_messages_eus
[  0%] Built target visualization_msgs_generate_messages_cpp
Scanning dependencies of target visualization_msgs_generate_messages_eus
Scanning dependencies of target visualization_msgs_generate_messages_py
Scanning dependencies of target rosgraph_msgs_generate_messages_lisp
Scanning dependencies of target lio_sam_imuPreintegration
[  0%] Built target visualization_msgs_generate_messages_eus
[  0%] Built target visualization_msgs_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_lisp
Scanning dependencies of target lio_sam_generate_messages_eus
Scanning dependencies of target lio_sam_generate_messages_cpp
Scanning dependencies of target lio_sam_generate_messages_lisp
[  4%] Generating EusLisp code from lio_sam/cloud_info.msg
[  9%] Generating C++ code from lio_sam/cloud_info.msg
[ 14%] Generating Lisp code from lio_sam/cloud_info.msg
[ 19%] Generating Lisp code from lio_sam/save_map.srv
[ 23%] Generating EusLisp code from lio_sam/save_map.srv
[ 23%] Built target lio_sam_generate_messages_lisp
Scanning dependencies of target lio_sam_generate_messages_nodejs
[ 28%] Generating Javascript code from lio_sam/cloud_info.msg
[ 33%] Generating EusLisp manifest code for lio_sam
[ 38%] Generating C++ code from lio_sam/save_map.srv
[ 42%] Generating Javascript code from lio_sam/save_map.srv
[ 42%] Built target lio_sam_generate_messages_nodejs
Scanning dependencies of target lio_sam_generate_messages_py
[ 47%] Generating Python from MSG lio_sam/cloud_info
[ 47%] Built target lio_sam_generate_messages_cpp
[ 52%] Generating Python code from SRV lio_sam/save_map
Scanning dependencies of target lio_sam_mapOptmization
[ 57%] Building CXX object LIO-SAM/CMakeFiles/lio_sam_imuPreintegration.dir/src/imuPreintegration.cpp.o
[ 61%] Generating Python msg __init__.py for lio_sam
[ 66%] Generating Python srv __init__.py for lio_sam
[ 66%] Built target lio_sam_generate_messages_eus
Scanning dependencies of target lio_sam_imageProjection
[ 66%] Built target lio_sam_generate_messages_py
Scanning dependencies of target lio_sam_featureExtraction
[ 71%] Building CXX object LIO-SAM/CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o
[ 76%] Building CXX object LIO-SAM/CMakeFiles/lio_sam_imageProjection.dir/src/imageProjection.cpp.o
[ 80%] Building CXX object LIO-SAM/CMakeFiles/lio_sam_featureExtraction.dir/src/featureExtraction.cpp.o
/home/macko-pc/catkin_ws/src/LIO-SAM/src/mapOptmization.cpp: In member function ‘bool mapOptimization::saveMapService(lio_sam::save_mapRequest&, lio_sam::save_mapResponse&)’:
/home/macko-pc/catkin_ws/src/LIO-SAM/src/mapOptmization.cpp:365:11: warning: variable ‘unused’ set but not used [-Wunused-but-set-variable]
       int unused = system((std::string("exec rm -r ") + saveMapDirectory).c_str());
           ^~~~~~
/home/macko-pc/catkin_ws/src/LIO-SAM/src/mapOptmization.cpp: In member function ‘void mapOptimization::publishFrames()’:
/home/macko-pc/catkin_ws/src/LIO-SAM/src/mapOptmization.cpp:1741:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (lastSLAMInfoPubSize != cloudKeyPoses6D->size())
                 ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model.h:52:0,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/sac.h:45,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/ransac.h:44,
                 from /usr/include/pcl-1.8/pcl/registration/icp.h:45,
                 from /home/macko-pc/catkin_ws/src/LIO-SAM/include/utility.h:27,
                 from /home/macko-pc/catkin_ws/src/LIO-SAM/src/featureExtraction.cpp:1:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h: In function ‘void __static_initialization_and_destruction_0(int, int)’:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
   SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
   ^~~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
In file included from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model.h:52:0,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/sac.h:45,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/ransac.h:44,
                 from /usr/include/pcl-1.8/pcl/registration/icp.h:45,
                 from /home/macko-pc/catkin_ws/src/LIO-SAM/include/utility.h:27,
                 from /home/macko-pc/catkin_ws/src/LIO-SAM/src/imageProjection.cpp:1:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h: In function ‘void __static_initialization_and_destruction_0(int, int)’:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
   SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
   ^~~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
[ 85%] Linking CXX executable /home/macko-pc/catkin_ws/devel/lib/lio_sam/lio_sam_featureExtraction
[ 90%] Linking CXX executable /home/macko-pc/catkin_ws/devel/lib/lio_sam/lio_sam_imageProjection
In file included from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model.h:52:0,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/sac.h:45,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/ransac.h:44,
                 from /usr/include/pcl-1.8/pcl/registration/icp.h:45,
                 from /home/macko-pc/catkin_ws/src/LIO-SAM/include/utility.h:27,
                 from /home/macko-pc/catkin_ws/src/LIO-SAM/src/imuPreintegration.cpp:1:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h: In function ‘void __static_initialization_and_destruction_0(int, int)’:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
   SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
   ^~~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
[ 90%] Built target lio_sam_featureExtraction
Scanning dependencies of target lio_sam_generate_messages
[ 90%] Built target lio_sam_generate_messages
[ 90%] Built target lio_sam_imageProjection
In file included from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model.h:52:0,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/sac.h:45,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/ransac.h:44,
                 from /usr/include/pcl-1.8/pcl/registration/icp.h:45,
                 from /home/macko-pc/catkin_ws/src/LIO-SAM/include/utility.h:27,
                 from /home/macko-pc/catkin_ws/src/LIO-SAM/src/mapOptmization.cpp:1:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h: In function ‘void __static_initialization_and_destruction_0(int, int)’:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
   SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
   ^~~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
[ 95%] Linking CXX executable /home/macko-pc/catkin_ws/devel/lib/lio_sam/lio_sam_imuPreintegration
/usr/bin/ld: cannot find -lBoost::timer
collect2: error: ld returned 1 exit status
LIO-SAM/CMakeFiles/lio_sam_imuPreintegration.dir/build.make:759: recipe for target '/home/macko-pc/catkin_ws/devel/lib/lio_sam/lio_sam_imuPreintegration' failed
make[2]: *** [/home/macko-pc/catkin_ws/devel/lib/lio_sam/lio_sam_imuPreintegration] Error 1
CMakeFiles/Makefile2:3207: recipe for target 'LIO-SAM/CMakeFiles/lio_sam_imuPreintegration.dir/all' failed
make[1]: *** [LIO-SAM/CMakeFiles/lio_sam_imuPreintegration.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable /home/macko-pc/catkin_ws/devel/lib/lio_sam/lio_sam_mapOptmization
/usr/bin/ld: cannot find -lBoost::timer
collect2: error: ld returned 1 exit status
LIO-SAM/CMakeFiles/lio_sam_mapOptmization.dir/build.make:759: recipe for target '/home/macko-pc/catkin_ws/devel/lib/lio_sam/lio_sam_mapOptmization' failed
make[2]: *** [/home/macko-pc/catkin_ws/devel/lib/lio_sam/lio_sam_mapOptmization] Error 1
CMakeFiles/Makefile2:2868: recipe for target 'LIO-SAM/CMakeFiles/lio_sam_mapOptmization.dir/all' failed
make[1]: *** [LIO-SAM/CMakeFiles/lio_sam_mapOptmization.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed`

**Comment by Today20180409** [comment]
I have the same problem, did you solve it？ @macnack

**Comment by THLL245** [comment]
I too am having this same problem, any solutions?

**Comment by Today20180409** [comment]
> 
I solved this problem by following two methods：
1.Please refer to this link [link](https://github.com/TixiaoShan/LIO-SAM/issues/229)；
2.I downgraded the version of gtsam from 4.0.3 to 4.0.2，then it compiles fine. This means it's a gtsam version problem。
The second method is recommended，the first method compiles normally, but the node will exit abnormally at runtime.
hope this helps.

**Comment by aladin2022** [comment]
Hi , can you help me with the directory or a link to install GTSAM 4.0.2
