### ISSUE TITLE
cannot launch node of type [lio_sam/lio_sam_imuPreintegration]: Cannot locate node of type [lio_sam_imuPreintegration] in package [lio_sam].

### ISSUE THREAD

**Issue by Xu-Huitong** [TixiaoShan/LIO-SAM#319]
When I run the command "roslaunch lio_sam run.launch", I get the following error, while rviz can be opened.
ERROR: cannot launch node of type [lio_sam/lio_sam_imuPreintegration]: Cannot locate node of type [lio_sam_imuPreintegration] in package [lio_sam]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [lio_sam/lio_sam_imageProjection]: Cannot locate node of type [lio_sam_imageProjection] in package [lio_sam]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [lio_sam/lio_sam_featureExtraction]: Cannot locate node of type [lio_sam_featureExtraction] in package [lio_sam]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [lio_sam/lio_sam_mapOptmization]: Cannot locate node of type [lio_sam_mapOptmization] in package [lio_sam]. Make sure file exists in package path and permission is set to executable (chmod +x)

**Comment by houcemsaidani** [comment]
same... waiting for a solution

**Comment by houcemsaidani** [comment]
Hey i found this and it worked like a charm for me.
The solution is to specify the package to compile
just type:
catkin_make -DCATKIN_WHITELIST_PACKAGES="lio_sam"

i found the solution here:
https://zhuanlan-zhihu-com.translate.goog/p/419116270?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=ar

**Comment by Xu-Huitong** [comment]
> Hey i found this and it worked like a charm for me. The solution is to specify the package to compile just type: catkin_make -DCATKIN_WHITELIST_PACKAGES="lio_sam"
> 
> i found the solution here: https://zhuanlan-zhihu-com.translate.goog/p/419116270?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=ar

thanks

**Comment by nyxrobotics** [comment]
I have the same problem.
I am using Ubuntu 18.04+ROS melodic.
This bug should not be closed.
