### ISSUE TITLE
Some problems occurred during operation

### ISSUE THREAD

**Issue by eminbogen** [TixiaoShan/LIO-SAM#32]
![2020-07-15 21-15-10屏幕截图](https://user-images.githubusercontent.com/49379943/87549596-9a2f8180-c6e0-11ea-8b66-58638fe2f727.png)
Hello. I used your public data to run your program, and this happened. The z coordinate keeps dropping. What is the problem? Is my configuration file not modified?

**Comment by TixiaoShan** [comment]
Sounds like a configuration problem. I suggest testing with the latest code and the Casual Walking dataset.

**Comment by eminbogen** [comment]
Thank you, I found the reason is that I forgot to modify extrinsicRot and extrinsicRPY. Your results are really good.

**Comment by duongthao1218** [comment]
> Thank you, I found the reason is that I forgot to modify extrinsicRot and extrinsicRPY. Your results are really good.

How to modify extrinsicRot and extrinsicRPY?
