### ISSUE TITLE
question about kitti2bag about velodyne data timestamp

### ISSUE THREAD

**Issue by LongruiDong** [TixiaoShan/LIO-SAM#322]
Hi~

I am using LIO-SAM to test kitti.  as mentioned in #34 , to deskew kitti raw velodyne data, I need to add relative time for each point in a scan (just like [@LeisureLei said](https://github.com/TixiaoShan/LIO-SAM/issues/112#issuecomment-694687818) ). 
according to 《Vision meets robotics: The KITTI dataset》 Sec 3.1 :

> As the Velodyne laser scanner has a ‘rolling shutter’, three timestamp files are provided for this sensor, one for the start position (timestamps_start.txt) of a spin, one for the end position (timestamps_end.txt) of a spin, and one for the time, where the laser scanner is facing forward and triggering the cameras (timestamps.txt). 

each velodyne frame 's start timestamp should be timestamps_start.txt, which shoud be header.stamp(cloudHeader.stamp) of each scan. As https://github.com/TixiaoShan/LIO-SAM/blob/6665aa0a4fcb5a9bb3af7d3923ae4a035b489d47/src/imageProjection.cpp#L238

is written, the deskew function in LIO-SAM should bet fed the reltime with right to start time of each scan

So in my understanding, may be https://github.com/TixiaoShan/LIO-SAM/blob/6665aa0a4fcb5a9bb3af7d3923ae4a035b489d47/config/doc/kitti2bag/kitti2bag.py#L215
should change the 'timestamps' to 'timestamps_start'?

**Comment by Sonne-Zhu** [comment]
I think u are right. 
btw, in question #34 , I also left a comment about the timestamp of the point.
