### ISSUE TITLE
Installing on Noetic-- Error with gtsam

### ISSUE THREAD

**Issue by baberjunaid** [TixiaoShan/LIO-SAM#332]
I tried to follow the steps of [Juliangaal](https://github.com/juliangaal/LIO-SAM). I am getting follow errors when I do 
`catkin_make`

[ 94%] Built target os_node
[ 97%] Built target img_node
/usr/bin/ld: CMakeFiles/lio_sam_imuPreintegration.dir/src/imuPreintegration.cpp.o: in function `bool gtsam::equal_with_abs_tol<Eigen::Matrix<double, 3, 1, 0, 3, 1> >(Eigen::DenseBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> > const&, Eigen::DenseBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> > const&, double)':
/usr/local/include/gtsam/base/Matrix.h:92: undefined reference to `gtsam::fpEqual(double, double, double)'
/usr/bin/ld: CMakeFiles/lio_sam_imuPreintegration.dir/src/imuPreintegration.cpp.o: in function `gtsam::Pose3::operator*(gtsam::Pose3 const&) const':
/usr/local/include/gtsam/geometry/Pose3.h:112: undefined reference to `gtsam::Rot3::operator*(gtsam::Point3 const&) const'
/usr/bin/ld: /usr/local/include/gtsam/geometry/Pose3.h:112: undefined reference to `gtsam::Rot3::operator*(gtsam::Point3 const&) const'
/usr/bin/ld: CMakeFiles/lio_sam_imuPreintegration.dir/src/imuPreintegration.cpp.o: in function `bool gtsam::equal_with_abs_tol<Eigen::Matrix<double, 3, 1, 0, 3, 1> >(Eigen::DenseBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> > const&, Eigen::DenseBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> > const&, double)':
/usr/local/include/gtsam/base/Matrix.h:92: undefined reference to `gtsam::fpEqual(double, double, double)'
/usr/bin/ld: /usr/local/include/gtsam/base/Matrix.h:92: undefined reference to `gtsam::fpEqual(double, double, double)'
/usr/bin/ld: CMakeFiles/lio_sam_imuPreintegration.dir/src/imuPreintegration.cpp.o: in function `gtsam::Pose3::operator*(gtsam::Pose3 const&) const':
/usr/local/include/gtsam/geometry/Pose3.h:112: undefined reference to `gtsam::Rot3::operator*(gtsam::Point3 const&) const'
/usr/bin/ld: /usr/local/include/gtsam/geometry/Pose3.h:112: undefined reference to `gtsam::Rot3::operator*(gtsam::Point3 const&) const'
/usr/bin/ld: CMakeFiles/lio_sam_imuPreintegration.dir/src/imuPreintegration.cpp.o:(.data.rel.ro._ZTVN5gtsam17NoiseModelFactor1INS_5Pose3EEE[_ZTVN5gtsam17NoiseModelFactor1INS_5Pose3EEE]+0x10): undefined reference to `gtsam::NoiseModelFactor::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (unsigned long)> const&) const'
/usr/bin/ld: CMakeFiles/lio_sam_imuPreintegration.dir/src/imuPreintegration.cpp.o:(.data.rel.ro._ZTVN5gtsam17NoiseModelFactor5INS_5Pose3EN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEES1_S4_NS_7imuBias12ConstantBiasEEE[_ZTVN5gtsam17NoiseModelFactor5INS_5Pose3EN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEES1_S4_NS_7imuBias12ConstantBiasEEE]+0x10): undefined reference to `gtsam::NoiseModelFactor::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (unsigned long)> const&) const'
/usr/bin/ld: CMakeFiles/lio_sam_imuPreintegration.dir/src/imuPreintegration.cpp.o:(.data.rel.ro._ZTVN5gtsam17NoiseModelFactor1IN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEE[_ZTVN5gtsam17NoiseModelFactor1IN5Eigen6MatrixIdLi3ELi1ELi0ELi3ELi1EEEEE]+0x10): undefined reference to `gtsam::NoiseModelFactor::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (unsigned long)> const&) const'
/usr/bin/ld: CMakeFiles/lio_sam_imuPreintegration.dir/src/imuPreintegration.cpp.o:(.data.rel.ro._ZTVN5gtsam17NoiseModelFactor1INS_7imuBias12ConstantBiasEEE[_ZTVN5gtsam17NoiseModelFactor1INS_7imuBias12ConstantBiasEEE]+0x10): undefined reference to `gtsam::NoiseModelFactor::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (unsigned long)> const&) const'
/usr/bin/ld: CMakeFiles/lio_sam_imuPreintegration.dir/src/imuPreintegration.cpp.o:(.data.rel.ro._ZTVN5gtsam17NoiseModelFactor2INS_7imuBias12ConstantBiasES2_EE[_ZTVN5gtsam17NoiseModelFactor2INS_7imuBias12ConstantBiasES2_EE]+0x10): undefined reference to `gtsam::NoiseModelFactor::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (unsigned long)> const&) const'
collect2: error: ld returned 1 exit status
make[2]: *** [LIO-SAM/CMakeFiles/lio_sam_imuPreintegration.dir/build.make:440: /home/junaid/catkin_ws/devel/lib/lio_sam/lio_sam_imuPreintegration] Error 1
make[1]: *** [CMakeFiles/Makefile2:2961: LIO-SAM/CMakeFiles/lio_sam_imuPreintegration.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `gtsam::Pose3::operator*(gtsam::Pose3 const&) const':
/usr/local/include/gtsam/geometry/Pose3.h:112: undefined reference to `gtsam::Rot3::operator*(gtsam::Point3 const&) const'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `gtsam::Rot3::roll() const':
/usr/local/include/gtsam/geometry/Rot3.h:448: undefined reference to `gtsam::Rot3::xyz() const'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `gtsam::Rot3::pitch() const':
/usr/local/include/gtsam/geometry/Rot3.h:456: undefined reference to `gtsam::Rot3::xyz() const'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `gtsam::Rot3::yaw() const':
/usr/local/include/gtsam/geometry/Rot3.h:464: undefined reference to `gtsam::Rot3::xyz() const'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `mapOptimization::pclPointTogtsamPose3(PointXYZIRPYT)':
/home/junaid/catkin_ws/src/LIO-SAM/src/mapOptmization.cpp:305: undefined reference to `gtsam::Rot3::RzRyRx(double, double, double)'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `mapOptimization::trans2gtsamPose(float*)':
/home/junaid/catkin_ws/src/LIO-SAM/src/mapOptmization.cpp:311: undefined reference to `gtsam::Rot3::RzRyRx(double, double, double)'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `gtsam::Pose3::operator*(gtsam::Pose3 const&) const':
/usr/local/include/gtsam/geometry/Pose3.h:112: undefined reference to `gtsam::Rot3::operator*(gtsam::Point3 const&) const'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `mapOptimization::trans2gtsamPose(float*)':
/home/junaid/catkin_ws/src/LIO-SAM/src/mapOptmization.cpp:311: undefined reference to `gtsam::Rot3::RzRyRx(double, double, double)'
/usr/bin/ld: /home/junaid/catkin_ws/src/LIO-SAM/src/mapOptmization.cpp:311: undefined reference to `gtsam::Rot3::RzRyRx(double, double, double)'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `gtsam::Pose3::operator*(gtsam::Pose3 const&) const':
/usr/local/include/gtsam/geometry/Pose3.h:112: undefined reference to `gtsam::Rot3::operator*(gtsam::Point3 const&) const'
/usr/bin/ld: /usr/local/include/gtsam/geometry/Pose3.h:112: undefined reference to `gtsam::Rot3::operator*(gtsam::Point3 const&) const'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `gtsam::Rot3::roll() const':
/usr/local/include/gtsam/geometry/Rot3.h:448: undefined reference to `gtsam::Rot3::xyz() const'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `gtsam::Rot3::pitch() const':
/usr/local/include/gtsam/geometry/Rot3.h:456: undefined reference to `gtsam::Rot3::xyz() const'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `gtsam::Rot3::yaw() const':
/usr/local/include/gtsam/geometry/Rot3.h:464: undefined reference to `gtsam::Rot3::xyz() const'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `gtsam::Rot3::roll() const':
/usr/local/include/gtsam/geometry/Rot3.h:448: undefined reference to `gtsam::Rot3::xyz() const'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `gtsam::Rot3::pitch() const':
/usr/local/include/gtsam/geometry/Rot3.h:456: undefined reference to `gtsam::Rot3::xyz() const'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o:/usr/local/include/gtsam/geometry/Rot3.h:464: more undefined references to `gtsam::Rot3::xyz() const' follow
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `mapOptimization::performLoopClosure()':
/home/junaid/catkin_ws/src/LIO-SAM/src/mapOptmization.cpp:588: undefined reference to `gtsam::Rot3::RzRyRx(double, double, double)'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `mapOptimization::pclPointTogtsamPose3(PointXYZIRPYT)':
/home/junaid/catkin_ws/src/LIO-SAM/src/mapOptmization.cpp:305: undefined reference to `gtsam::Rot3::RzRyRx(double, double, double)'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o: in function `gtsam::Pose3::operator*(gtsam::Pose3 const&) const':
/usr/local/include/gtsam/geometry/Pose3.h:112: undefined reference to `gtsam::Rot3::operator*(gtsam::Point3 const&) const'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o:(.data.rel.ro._ZTVN5gtsam17NoiseModelFactor1INS_5Pose3EEE[_ZTVN5gtsam17NoiseModelFactor1INS_5Pose3EEE]+0x10): undefined reference to `gtsam::NoiseModelFactor::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (unsigned long)> const&) const'
/usr/bin/ld: CMakeFiles/lio_sam_mapOptmization.dir/src/mapOptmization.cpp.o:(.data.rel.ro._ZTVN5gtsam17NoiseModelFactor2INS_5Pose3ES1_EE[_ZTVN5gtsam17NoiseModelFactor2INS_5Pose3ES1_EE]+0x10): undefined reference to `gtsam::NoiseModelFactor::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (unsigned long)> const&) const'
collect2: error: ld returned 1 exit status
make[2]: *** [LIO-SAM/CMakeFiles/lio_sam_mapOptmization.dir/build.make:440: /home/junaid/catkin_ws/devel/lib/lio_sam/lio_sam_mapOptmization] Error 1
make[1]: *** [CMakeFiles/Makefile2:3049: LIO-SAM/CMakeFiles/lio_sam_mapOptmization.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Invoking "make -j4 -l4" failed

**Comment by TixiaoShan** [comment]
I compiled successfully with Noetic following this https://github.com/TixiaoShan/LIO-SAM/issues/206#issuecomment-1095370894 issue.
