### ISSUE TITLE
Global pose optimization in mapOptimization?

### ISSUE THREAD

**Issue by Freeecode** [TixiaoShan/LIO-SAM#348]
Thanks for your hard work!
  I am doing some improvements on lio-sam, and I meet a problem when perform loopclosure, I found the default noise model setting used in PriorFactor, which maybe casued a big drift after adding loop factor or GPS factor in my test case, but when I change the noise model to a small value, the big drift didn't appear. The 
  Can you give me some advice?
 (1) The first pose in optimization should be fixed. Why you set the large noise model for priorfactor, espically for position?  
   priorNoise = noiseModel::Diagonal::Variances((Vector(6) << 1e-2, 1e-2, M_PI*M_PI, 1e8, 1e8, 1e8).finished());
 (2)  GPS factor used in lio-sam is relative,  Can I use gps in global coordinate?

**Comment by hirenpatel1207** [comment]
Hi,
Did you understand the reason behind this large noise model for priorfactor?
