### ISSUE TITLE
pcl_conversion_DIR

### ISSUE THREAD

**Issue by cyborgdennett** [TixiaoShan/LIO-SAM#349]
Hello, I tried installing LIO-SAM and I get this error when performing catkin_make:

Ros: Melodic-desktop
System: WSL ubuntu18.04
Chip: Intel 10th gen

=====================================================================

 +++ processing catkin package: 'lio_sam'
-- ==> add_subdirectory(LIO-SAM)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Could NOT find pcl_conversions (missing: pcl_conversions_DIR)
-- Could not find the required component 'pcl_conversions'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "pcl_conversions"
  with any of the following names:

    pcl_conversionsConfig.cmake
    pcl_conversions-config.cmake

  Add the installation prefix of "pcl_conversions" to CMAKE_PREFIX_PATH or
  set "pcl_conversions_DIR" to a directory containing one of the above files.
  If "pcl_conversions" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  LIO-SAM/CMakeLists.txt:8 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/casper/liosam_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/casper/liosam_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by TixiaoShan** [comment]
It's a GTSAM problem. Try to use an older version:
```
sudo apt purge libgtsam*

wget -O ~/Downloads/gtsam.zip https://github.com/borglab/gtsam/archive/4.0.2.zip
cd ~/Downloads/ && unzip gtsam.zip -d ~/Downloads/
cd ~/Downloads/gtsam-4.0.2/
mkdir build && cd build
cmake -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF ..
sudo make install -j8
```

**Comment by cyborgdennett** [comment]
Thank you for the reply, however, a new error emerges

[ 69%] Linking CXX executable Pose2SLAMExample_g2o
../gtsam/libgtsam.so.4.0.2: undefined reference to `libintl_sprintf'
../gtsam/libgtsam.so.4.0.2: undefined reference to `libintl_printf'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/Pose2SLAMExample_g2o.dir/build.make:107: recipe for target 'examples/Pose2SLAMExample_g2o' failed
make[2]: *** [examples/Pose2SLAMExample_g2o] Error 1
CMakeFiles/Makefile2:20604: recipe for target 'examples/CMakeFiles/Pose2SLAMExample_g2o.dir/all' failed
make[1]: *** [examples/CMakeFiles/Pose2SLAMExample_g2o.dir/all] Error 2
[ 69%] Linking CXX executable Pose2SLAMExample_graph
../gtsam/libgtsam.so.4.0.2: undefined reference to `libintl_sprintf'
../gtsam/libgtsam.so.4.0.2: undefined reference to `libintl_printf'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/Pose2SLAMExample_graph.dir/build.make:107: recipe for target 'examples/Pose2SLAMExample_graph' failed
make[2]: *** [examples/Pose2SLAMExample_graph] Error 1
CMakeFiles/Makefile2:21184: recipe for target 'examples/CMakeFiles/Pose2SLAMExample_graph.dir/all' failed
make[1]: *** [examples/CMakeFiles/Pose2SLAMExample_graph.dir/all] Error 2
[ 69%] Linking CXX executable ImuFactorExample2
../gtsam/libgtsam.so.4.0.2: undefined reference to `libintl_sprintf'
../gtsam/libgtsam.so.4.0.2: undefined reference to `libintl_printf'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/ImuFactorExample2.dir/build.make:107: recipe for target 'examples/ImuFactorExample2' failed
make[2]: *** [examples/ImuFactorExample2] Error 1
CMakeFiles/Makefile2:21146: recipe for target 'examples/CMakeFiles/ImuFactorExample2.dir/all' failed
make[1]: *** [examples/CMakeFiles/ImuFactorExample2.dir/all] Error 2
[ 69%] Linking CXX executable SFMExample_bal
../gtsam/libgtsam.so.4.0.2: undefined reference to `libintl_sprintf'
../gtsam/libgtsam.so.4.0.2: undefined reference to `libintl_printf'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/SFMExample_bal.dir/build.make:107: recipe for target 'examples/SFMExample_bal' failed
make[2]: *** [examples/SFMExample_bal] Error 1
CMakeFiles/Makefile2:21222: recipe for target 'examples/CMakeFiles/SFMExample_bal.dir/all' failed
make[1]: *** [examples/CMakeFiles/SFMExample_bal.dir/all] Error 2
[ 69%] Linking CXX executable PlanarSLAMExample
CMakeFiles/PlanarSLAMExample.dir/PlanarSLAMExample.cpp.o: In function `gtsam::ExpressionFactor<gtsam::BearingRange<gtsam::Pose2, gtsam::Point2, gtsam::Rot2, double> >::print(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (unsigned long)> const&) const':
PlanarSLAMExample.cpp:(.text._ZNK5gtsam16ExpressionFactorINS_12BearingRangeINS_5Pose2ENS_6Point2ENS_4Rot2EdEEE5printERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN5boost8functionIFSC_mEEE[_ZNK5gtsam16ExpressionFactorINS_12BearingRangeINS_5Pose2ENS_6Point2ENS_4Rot2EdEEE5printERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN5boost8functionIFSC_mEEE]+0xa3): undefined reference to `libintl_printf'
../gtsam/libgtsam.so.4.0.2: undefined reference to `libintl_sprintf'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/PlanarSLAMExample.dir/build.make:107: recipe for target 'examples/PlanarSLAMExample' failed
make[2]: *** [examples/PlanarSLAMExample] Error 1
CMakeFiles/Makefile2:20974: recipe for target 'examples/CMakeFiles/PlanarSLAMExample.dir/all' failed
make[1]: *** [examples/CMakeFiles/PlanarSLAMExample.dir/all] Error 2
[ 71%] Linking CXX executable Pose2SLAMExampleExpressions
../gtsam/libgtsam.so.4.0.2: undefined reference to `libintl_sprintf'
../gtsam/libgtsam.so.4.0.2: undefined reference to `libintl_printf'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/Pose2SLAMExampleExpressions.dir/build.make:107: recipe for target 'examples/Pose2SLAMExampleExpressions' failed
make[2]: *** [examples/Pose2SLAMExampleExpressions] Error 1
CMakeFiles/Makefile2:20706: recipe for target 'examples/CMakeFiles/Pose2SLAMExampleExpressions.dir/all' failed
make[1]: *** [examples/CMakeFiles/Pose2SLAMExampleExpressions.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by TixiaoShan** [comment]
Did you try this?

https://github.com/TixiaoShan/LIO-SAM/issues/229#issuecomment-1038597243

**Comment by cyborgdennett** [comment]
Thank you i can confirm it compiles succesfully on ROS melodic on ubuntu 18.04 on WSL2 on amd64! 👯

**Comment by cyborgdennett** [comment]
Hey @TixiaoShan, i can compile now and run the program. But if I run any of the example bag files, I get a black screen on Rviz.
![image](https://user-images.githubusercontent.com/40475862/171413352-526cdee8-77b1-4c16-bb9a-c5021a0ae85e.png)

**Comment by cyborgdennett** [comment]
The problem was the bag: 
casper@LAPTOP-0CAT7HLP:~$ rosbag info Downloads/campus_small_dataset.bag
topics:      /gps/fix         2039 msgs    : sensor_msgs/NavSatFix
             /imu_correct   203912 msgs    : sensor_msgs/Imu
             /points_raw      4043 msgs    : sensor_msgs/PointCloud2

So i had to change params.yaml to 

lio_sam:

  # Topics
  pointCloudTopic: "points_raw"               # Point cloud data
  imuTopic: "imu_correct"                         # IMU data
  odomTopic: "odometry/imu"                   # IMU pre-preintegration odometry, same frequency as IMU
  gpsTopic: "gps/fix"
