### ISSUE TITLE
Using GPS with KITTI dataset

### ISSUE THREAD

**Issue by Pallav1299** [TixiaoShan/LIO-SAM#35]
I am facing problems while setting LIO-SAM with GPS for the KITTI dataset. I am getting a lot of sudden jumps in the output ![Uploading gps_issue.png…]().

The package works fairly well without GPS. I think it's an issue with improper configuration. I seek some help regarding the same.

**Comment by TixiaoShan** [comment]
There are still some unsolved problems in LIO-SAM when a loop is closed or a GPS measurement is received. Any inputs are welcome from the community.

**Comment by Pallav1299** [comment]
@TixiaoShan, my use-case requires creating globally correct point cloud maps. I haven't read the code thoroughly. Can you please list down the issues with including GPS measurements and loop closure, so as to keep track of the required changes and improvements?

**Comment by Pallav1299** [comment]
![Screenshot from 2020-07-21 22-11-38](https://user-images.githubusercontent.com/32015105/88148884-e583eb80-cc1c-11ea-8c2c-41c1facc6809.png)
Initial misalignment causes the **/lio_sam/mapping/path** to drift away from **/odometry/gps**. Further, when GPS data should be added to the pose graph, there is sudden jump in the pose. Hence leading to imperfect global poses. 
I am trying with the default params on the **Kitti_raw_data "2011_10_03_drive_0042 (4.5 GB)"** dataset while it doesn't have **position covariance** in the **/gps/fix** data. Am I doing something wrong here?

**Comment by TixiaoShan** [comment]
You should tune the function that adds GPS factor in mapOptimization.cpp carefully. KITTI dataset doesn't give GPS covariance, so you have to change the threshold to figure out the best settings. When a GPS factor is added, imuPreintegration will be reset and cause a loss of initial guess in updateInitialGuess(). If the vehicle is moving very fast, the scan-matching may fail. You can disable [these lines](https://github.com/TixiaoShan/LIO-SAM/blob/74c1147729c282562267a942ca9179b729fd14e3/src/mapOptmization.cpp#L636) to help this problem. But it's not perfect. I am still trying to figure out solving matching failure when a GPS factor is added.

**Comment by Pallav1299** [comment]
1. I tried with the above mentioned changes. I noticed that at points where positionCovariance is greater than the threshold, most of the GPS values though being correct, are neglected due to being relatively old or new w.r.t the pointcloud timestamp. This leads to error accumulation. 
Later when a new GPS factor is added, heavy ISAM optimization takes place on a large no of nodes. During this time the imuPreintegration gets reset.
I tried on the **kitti dataset**. Please correct me if I am wrong.

2. I tried with and without GPS elevation integrated on KITTI dataset and tested with the ground truth data from Odometry sequences(I've less no. of keyposes so the data is scaled down, but the trend is almost same for X and Y axes)
- Without using elevation from GPS, the Z axis has following results:
![Screenshot 2020-07-28 00:38:53](https://user-images.githubusercontent.com/32015105/88581486-dc56ac80-d06a-11ea-8fd6-26267b5be053.png)

- With GPS elevation, the following result is obtained for elevation in the final trajectory as compared to groundtruth :
![Screenshot 2020-07-28 00:44:12](https://user-images.githubusercontent.com/32015105/88581932-8d5d4700-d06b-11ea-9c50-673b046e7c43.png)

**Dotted line is ground truth**

**Comment by polbolso** [comment]
> 1. I tried with the above mentioned changes. I noticed that at points where positionCovariance is greater than the threshold, most of the GPS values though being correct, are neglected due to being relatively old or new w.r.t the pointcloud timestamp. This leads to error accumulation.
>    Later when a new GPS factor is added, heavy ISAM optimization takes place on a large number of nodes. During this time the imuPreintegration gets reset.
>    I tried on the **kitti dataset**. Please correct me if I am wrong.
> 2. I tried with and without GPS elevation integrated on KITTI dataset and tested with the ground truth data from Odometry sequences(I've less no. of keyposes so the data is scaled down, but the trend is almost same for X and Y axes)
> 
> * Without using elevation from GPS, the Z axis has following results:
>   ![Screenshot 2020-07-28 00:38:53](https://user-images.githubusercontent.com/32015105/88581486-dc56ac80-d06a-11ea-8fd6-26267b5be053.png)
> * With GPS elevation, the following result is obtained for elevation in the final trajectory as compared to groundtruth :
>   ![Screenshot 2020-07-28 00:44:12](https://user-images.githubusercontent.com/32015105/88581932-8d5d4700-d06b-11ea-9c50-673b046e7c43.png)
> 
> **Dotted line is ground truth**
> 
> Should we use elevation from GPS or not?

@Pallav1299 You mentioned that the number of keyframes was different from the KITTI's ground truth. 
I actually have the same problem. Did you evaluate the results using tum format for the trajectories?

**Comment by Pallav1299** [comment]
@polbolso I didn't try visualizing in TUM or EUROC formats using EVO. I used KITTI format data. With KITTI format you would have to maintain the same number of poses to evaluate relative and absolute pose errors. This issue is solved by using timestamps in TUM format if I am not wrong. I'd suggest converting KITTI format poses to TUM for evaluation
 in EVO.

**Comment by polbolso** [comment]
Thanks @Pallav1299, I managed to combine the produced results with KITTI ground truth through TUM format. However, it seems that there is a clear misalignment issue. Have you experienced something similar?

![Screenshot from 2021-05-13 17-45-55](https://user-images.githubusercontent.com/72814058/118448942-e4173880-b6f2-11eb-9311-c73270b8848f.png)

**Comment by berkaysahinaskar** [comment]
> Thanks @Pallav1299, I managed to combine the produced results with KITTI ground truth through TUM format. However, it seems that there is a clear misalignment issue. Have you experienced something similar?
> 
> ![Screenshot from 2021-05-13 17-45-55](https://user-images.githubusercontent.com/72814058/118448942-e4173880-b6f2-11eb-9311-c73270b8848f.png)

I experienced same issue. There is a difference between vehicle axis and yours. You need to change the x y z poses reference to KITTI vehicle setup.
