### ISSUE TITLE
IMU to LiDar Transform

### ISSUE THREAD

**Issue by oskarmue** [TixiaoShan/LIO-SAM#355]
![frames](https://user-images.githubusercontent.com/73947915/178254179-83fc3df9-9ab2-4ea6-ae7a-2db1cca270f6.png)

Hi I have a tilted LiDar and I dont really understand how to write the extrinsic Transformations.
I think it schould be [0, 0, -1, 0, 1, 0, 1, 0, 0]. But it is not working. The lidar is mounted on a cart and being driven on a flat surface, but in rviz it is changing in elevation. At the same time the frames (imu and lidar) are doing really big jumps.

I am using 
LiDar: RsLidar Bpearl (using https://github.com/HViktorTsoi/rs_to_velodyne in order to convert the PCL)
IMU: Xsens MTI 680

As far as I understand the IMU values are supposed to be transformed in the Lidar frame. Does that mean, if the x axes is directed downwards to the map frame, that the gravitational force has to be negative on the x axes, when using the imu debugger?

**Comment by ArghyaChatterjee** [comment]
Were you able to work with a tilted lidar? How was the transform from base_link to lidar frame ?
