### ISSUE TITLE
Quaternion Not normalized properly

### ISSUE THREAD

**Issue by Dhruv0208** [TixiaoShan/LIO-SAM#386]
Hi, I was testing lio-sam over my data and I am getting the following errors.
![image](https://user-images.githubusercontent.com/51269047/200611650-01f09664-473a-45ba-b5dd-fbc3edbd1814.png)

Any idea where I might be going wrong?

**Comment by joao-aguizo** [comment]
@Dhruv0208 What was the problem? Did you manage to solve it?

**Comment by buaaysh** [comment]
Have you solved this problem yet？

**Comment by buaaysh** [comment]
> @Dhruv0208 What was the problem? Did you manage to solve it?

Have you solved this problem yet

**Comment by helywin** [comment]
@buaaysh I solved this by normalizing IMU data

```cpp
void normalizeImu(sensor_msgs::Imu& imu_msg) {
    double magnitude = std::sqrt(
        imu_msg.orientation.x * imu_msg.orientation.x +
        imu_msg.orientation.y * imu_msg.orientation.y +
        imu_msg.orientation.z * imu_msg.orientation.z +
        imu_msg.orientation.w * imu_msg.orientation.w
    );

    imu_msg.orientation.x /= magnitude;
    imu_msg.orientation.y /= magnitude;
    imu_msg.orientation.z /= magnitude;
    imu_msg.orientation.w /= magnitude;
}
```
