### ISSUE TITLE
How to use LIO-SAM with ouster 64 lidar?

### ISSUE THREAD

**Issue by JACKLiuDay** [TixiaoShan/LIO-SAM#390]
Hi, thank you for your great about LIO-SAM. I have tried this project with my velodyne-16 and it works perfectly. Now I got a new ouster64 lidar. While I don't know how to use it with LIO-SAM. I see the read.me and I need to change param.yaml. But I really don't which params in the yaml should be changed. Could you give me some advices. Thanks.

**Comment by ChenYihan618** [comment]
Hi, did you find a solution?
