### ISSUE TITLE
imu

### ISSUE THREAD

**Issue by ycl-web** [TixiaoShan/LIO-SAM#392]
I am very grateful to the author for being able to open source such an excellent slam algorithm. There is a small problem here: the imu of the same model as the author, 3dm-gx5-25, can release topic at a frequency of 500hz, but when I modify the driver "microstrain_inertial_driver", I find that it can only be modified up to 145hz. I feel this may have caused a drop in positioning accuracy. May I ask how to adjust the release frequency of 3dm-gx5-25 to 500hz in the Linux environment. Thank you very much.@TixiaoShan

**Comment by AlbertoJimenezUC3M** [comment]
> I am very grateful to the author for being able to open source such an excellent slam algorithm. There is a small problem here: the imu of the same model as the author, 3dm-gx5-25, can release topic at a frequency of 500hz, but when I modify the driver "microstrain_inertial_driver", I find that it can only be modified up to 145hz. I feel this may have caused a drop in positioning accuracy. May I ask how to adjust the release frequency of 3dm-gx5-25 to 500hz in the Linux environment. Thank you very much.@TixiaoShan

Hello @ycl-web . Could you solve it?
