### ISSUE TITLE
How can I prevent point cloud from being deleted over time?

### ISSUE THREAD

**Issue by tlgkyn06** [TixiaoShan/LIO-SAM#399]
Thanks for magnificent work. 
I made your code work perfectly with my system. 
I am trying to visualize and save whole pcd but point cloud gets deleted over time.
How I can prevent this deletion?

**Comment by tlgkyn06** [comment]
it is related with decay time in rviz

**Comment by farhad-dalirani** [comment]
@tlgkyn06 How did you solve this?

**Comment by tlgkyn06** [comment]
@farhad-dalirani it is not about algorithm. it is about rviz decay time, increase the decay time.
