### ISSUE TITLE
Evaluation using KITTI Vision Benchmark

### ISSUE THREAD

**Issue by hlezki** [TixiaoShan/LIO-SAM#4]
Hi,

Thank you sharing your work. 
Is it possible to evaluate LIO-SAM on KITTI Odometry Dataset? Can you explain how to make it possible ?

Thanks in advance.

**Comment by TixiaoShan** [comment]
@hlezki 
I am taking a look at this right now. I may come back later with the tutorial.

**Comment by hlezki** [comment]
Thank you, I am looking forward to your explanation.

**Comment by TixiaoShan** [comment]
@hlezki 

I have one question. Have you worked with KITTI IMU data? It seems that the IMU frequency is only at 1Hz.

**Comment by hlezki** [comment]
No, I have not worked before with IMU data of KITTI Benchmark.

**Comment by hunkyu** [comment]
@TixiaoShan The frequency given by kitti gps/imu is very low, there is no way to verify LIO-SAM

**Comment by TixiaoShan** [comment]
@TixiaoShan 
Thanks for the information. I notice that the synced IMU frequency is the same as the lidar frequency. There is no way to integrate one IMU data during a scan for graph optimization in LIO-SAM.

**Comment by daydayupzhang** [comment]
@TixiaoShan 
The IMU frequency in raw data/synchronized is very low, but in raw data/unsychronized it is 100Hz.
There is a blog about KITTI dataset, which especially mentions how to deal with the problems of IMU data. I hope this will help.
 https://zhuanlan.zhihu.com/p/75672946

**Comment by hlezki** [comment]
Thanks for your time.
