### ISSUE TITLE
Transform from lidar frame to base_link is not taken into account?

### ISSUE THREAD

**Issue by 2scholz** [TixiaoShan/LIO-SAM#40]
I noticed that a `base_link` with an offset from the lidar frame leads to erroneous behavior. In that case, the pose of the lidar is not tracked correctly. I first noticed this because the deskewed point cloud and the original point cloud don't match up. While the deskewed cloud remains in place, the original cloud just moved all over the place.

From what I can tell this happens because the transform from the base_link to the lidar is never taken into account. As a result, the pose of the `base_link` is tracked when the pose of the lidar frame should be tracked instead. Basically: the `base_link` takes the path that the lidar frame should take.

I hope it became clear what I mean. The error should be easy to reproduce by adding a large offset between the `base_link` and the lidar frame. It should be immediately apparent when looking at the frames and point clouds in rviz.

**Comment by kdaun** [comment]
As far as I understand it, `base_link`  is the tracking frame and assumed to coincide with the lidar frame. However, this does not hold true for many robot setups.
To make the frames adaptable for different setups I just introduced a PR https://github.com/TixiaoShan/LIO-SAM/pull/41.
