### ISSUE TITLE
Questions about the initialization

### ISSUE THREAD

**Issue by xxiao-1** [TixiaoShan/LIO-SAM#45]
Dear Tixiao, 
  This work is really awesome. Thank you for sharing it !
  I have noticed that LIO-SAM performs great with the rotation dataset, while LIOM is not able to initialize properly using this  dataset. So I want to ask what kind of initialization method did LIO-SAM use and what's the difference compared to  LIOM.
  Looking forward to your answer～

**Comment by TixiaoShan** [comment]
LIO-SAM uses similar initialization like LOAM. More details about the initialization can be found [here](https://github.com/TixiaoShan/LIO-SAM#prepare-imu-data).
