### ISSUE TITLE
how to get the full lidar frame pose but not only the key frame pose

### ISSUE THREAD

**Issue by Tartisan** [TixiaoShan/LIO-SAM#450]
Thanks for the great works! I want the fully optimized lidar frame pose, but not only the key frame pose, what can I do?

**Comment by rayee-github** [comment]
How about to increase keyframe frequency or decrease voxel filter rate?
Can you describe it in more detail.

**Comment by ghost** [comment]
Changing [here](https://github.com/TixiaoShan/LIO-SAM/blob/master/src/mapOptmization.cpp#L251) and [here](https://github.com/TixiaoShan/LIO-SAM/blob/master/src/mapOptmization.cpp#L1354) to true may output the feature points of each frame，but note that lio-sam is a real-time slam. You may need to ensure that the processor performance can keep up with the playback speed of the rosbag.

**Comment by Robin6416KW** [comment]
hi @XiaomingQu,I testing the same sample file "walking_dataset.bag" with Lio-sam and Liorf.

the parameter in Lio-sam is original param.yaml file and Liorf is lio_sam_default.yaml. 
these two parameters is mosltly the same. 

In Lio-sam it output full lidar frame, but in Liorf it just output keyframe. 
I compare thoese two line you mention in Lio-sam and Liorf but found no difference.
Is there other reason make liorf just output keyframe? 
many thanks.

**Comment by Tartisan** [comment]
> Changing [here](https://github.com/TixiaoShan/LIO-SAM/blob/master/src/mapOptmization.cpp#L251) and [here](https://github.com/TixiaoShan/LIO-SAM/blob/master/src/mapOptmization.cpp#L1354) to true may output the feature points of each frame，but note that lio-sam is a real-time slam. You may need to ensure that the processor performance can keep up with the playback speed of the rosbag.

Thanks, I konw.
