### ISSUE TITLE
Question about the number of the surface points.

### ISSUE THREAD

**Issue by Gaochao-hit** [TixiaoShan/LIO-SAM#46]
I have noticed that there are so many surface points in the extracted features. Is that a bug ?

**Comment by Gaochao-hit** [comment]
And I find that if I set curvature limit on the surface points, the number of surface points will decrease a lot and also the computation consumption will also decline a lot. At the same time, the accuracy will not decline.

**Comment by Gaochao-hit** [comment]
And I find that if a set a curvature limit on the surface points, although the number of the extracted surface points is not very small, the odometry will drift very fast.

**Comment by TixiaoShan** [comment]
I don't think it's a bug. If there are little features, the package won't work.

**Comment by Gaochao-hit** [comment]
> I don't think it's a bug. If there are little features, the package won't work.

You are right. But the curvature of surface points extracted in the code can be very large and the number of surface points is also very large, which will increase computating load. when I set a threshold 0.1 to choose the surface points, there are about several hundreds of surface points which I think is sufficient for calculating transforamtion. But unfortunatelly, it fails and drift away quickly. This confuses me a lot.
