### ISSUE TITLE
Question about Extrinsics

### ISSUE THREAD

**Issue by xieqi1** [TixiaoShan/LIO-SAM#47]
Hi:
  Thanks for sharing you work!
  I am confused with the part of Extrinsics in params.yaml, the Extrinsics represent transform from lidar to imu that meas transform measurement in lidar coordinate to imu coordinate. However, in utility.h, function imuConverter,
    acc = extRot * acc;  and   gyr = extRot * gyr;
  I think it is used to transform the measurement in imu coordinate to lidar coordinate, is it inconsistent with the definition in yaml file?
  Look forward to your reply！

**Comment by TixiaoShan** [comment]
You are right, the extrinsics defined in the YAML file transform the measurements from imu frame to lidar frame.
