### ISSUE TITLE
[ WARN] [1706283012.687423712]: MSG to TF: Quaternion Not Properly Normalized

### ISSUE THREAD

**Issue by Hensbag** [TixiaoShan/LIO-SAM#471]
Hello friends, I am trying to mapping with VLP-16 and BNO055 sensor by DFrobots " https://www.dfrobot.com/product-1793.html "  
My output is not like I expected . 
I use http://wiki.ros.org/ros_imu_bno055 package to obtain IMU data and default velodyne package for VLP16
[roslaunch-hasan-73798.log](https://github.com/TixiaoShan/LIO-SAM/files/14066662/roslaunch-hasan-73798.log)
[rosout.log](https://github.com/TixiaoShan/LIO-SAM/files/14066663/rosout.log)
[ros_imu_bno055_node-1.log](https://github.com/TixiaoShan/LIO-SAM/files/14066666/ros_imu_bno055_node-1.log)
[master.log](https://github.com/TixiaoShan/LIO-SAM/files/14066667/master.log)
![Screenshot from 2024-01-26 18-27-47](https://github.com/TixiaoShan/LIO-SAM/assets/122668994/6e6d948e-9d8b-4ee0-b4f8-b05f787976d5)
How can I get proper Map result, I think I have miss Integrated IMU with LIDAR.

**Comment by ghost** [comment]
It may be that your data is wrong, causing the acc bias to exceed 1. This error was reported after imu bias was reset.

**Comment by momoistda** [comment]
Hallo, Is your problem solved? I have the same problem now...

**Comment by Hensbag** [comment]
> Hallo, Is your problem solved? I have the same problem now...
BNO055 dont have enough sample rate (Hz) so I used to have a zed2 camera so I used zed2's IMU than I was able to SLAM
