### ISSUE TITLE
Large Map Closed Loop Issue

### ISSUE THREAD

**Issue by joewong00** [TixiaoShan/LIO-SAM#493]
![Screenshot 2024-05-21 at 7 10 41 PM](https://github.com/TixiaoShan/LIO-SAM/assets/63445582/5b61fea8-683b-4047-8af7-5c9a3e816c1c)

Hi, this is the map that is produced and we can clearly see that driving the same route is not able to close the loop in the map. There is no GPS correction for my data, may I know how can I tune the loop closure parameters to improve the map? Thanks

**Comment by joewong00** [comment]
I have fixed the issue, turned out I set the wrong TF for the lidar to IMU. For those of you who are having this issue, you can use the formula here to help you to get the correct extrinsics parameters. And now my map looks great!

<img width="268" alt="Screenshot 2024-05-24 at 1 17 24 PM" src="https://github.com/TixiaoShan/LIO-SAM/assets/63445582/c837560e-8c45-450a-b828-cb02805a5c53">

<img width="702" alt="Screenshot 2024-05-24 at 3 13 43 PM" src="https://github.com/TixiaoShan/LIO-SAM/assets/63445582/dbd8f449-64cd-41ac-8e3b-c8de4fbc40c6">

**Comment by Zahra-Farajzadeh** [comment]
Hello, how did you calculate those matrix? what is theta?

**Comment by joewong00** [comment]
> Hello, how did you calculate those matrix? what is theta?

Hi, theta is the angle transform from the lidar to IMU. If your IMU is placed 180 degree in the Z axis (yaw) from your lidar frame, then you can update the rotation matrix for R(z).
