### ISSUE TITLE
How to align map with Google Earth

### ISSUE THREAD

**Issue by Tompson11** [TixiaoShan/LIO-SAM#52]
Hi:
Thank you for sharing your work!
I've noticed that in your paper you align the map with Google Earth like the following figure, could you tell me how to do that?
![image](https://user-images.githubusercontent.com/42952053/89266314-589f5000-d668-11ea-8c3f-3c716e161074.png)

**Comment by TixiaoShan** [comment]
@Tompson11 
I used PowerPoint for that.

**Comment by Tompson11** [comment]
@TixiaoShan 
Thank you for your reply! So It's just the alignment of 2D images instead of 3D models?

**Comment by TixiaoShan** [comment]
Yes.

**Comment by Tompson11** [comment]
Got it, thank you!

**Comment by zhanglei1997** [comment]
@Tompson11 
Hello. May I ask if you have successfully achieved the effect of this map display? If it is convenient, I hope you can share your specific operation. Thank you so much!

**Comment by Tompson11** [comment]
> @Tompson11 Hello. May I ask if you have successfully achieved the effect of this map display? If it is convenient, I hope you can share your specific operation. Thank you so much!

Sorry, I haven't tried yet. 😂

**Comment by grischi** [comment]
have you tried [rviz_satellite](https://github.com/nobleo/rviz_satellite)?
