### ISSUE TITLE
Why are you reset the bias in the imuPreintegration.cpp

### ISSUE THREAD

**Issue by qian5683** [TixiaoShan/LIO-SAM#55]
in the system Initialize, you reset the imu's bias to gtsam::imuBias::ConstantBias(). Doesn't this overwrite the prior bias in the utility.h file?

**Comment by TixiaoShan** [comment]
It's from the official example, [here](https://github.com/borglab/gtsam/blob/269dea3a248f16fe324c84b09f8acbae321adca3/examples/ImuFactorsExample.cpp#L253).
