### ISSUE TITLE
How to generate the point clous with "ring" and "time"

### ISSUE THREAD

**Issue by Mafuqiang** [TixiaoShan/LIO-SAM#63]
Hi, Thanks for sharing this good job! I tested algorithm according to the read-me file, and the result is similar to paper. But I want to run the LIO-SAM with my own lidar sensor, and I have no idea how to generate the point clouds with "ring" and "time" channels. The standard data format of ROS is "x", "y", "z", "intensity", and the bag data format is "x", "y", "z", "intensity", "ring", "time". Only VLP and Ouster lidar can run the algorithm? Thank you very much.

**Comment by zwmisdu** [comment]
you can check the code in imageProjection.cpp and you can find that the filed 'ring' is  used to project the point clouds to a rang image, if your lidar hasn't this channel, you can replace the code projectPointCloud() by another way to project the point clouds (Lego-loam has the solution).Similarly,'time' is used to deskew the point clouds, you can also change the way .
