### ISSUE TITLE
Suffer from altitude drift

### ISSUE THREAD

**Issue by xieqi1** [TixiaoShan/LIO-SAM#64]
Hi !
  I run LIO-SAM on my own dateset,whose path is a big circle and its length about 2.1km, but the drift in altitude about 80m, so it can't form loop constraint. and drift in x and y is acceptable. So any suggestions about how to eliminate the altitude drift?
Thank you !

**Comment by daijiaoshou** [comment]
Is the IMU accuracy too low?

------------------

Best Regards



 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by xieqi1** [comment]
@daijiaoshou Hi ! my imu  is 100Hz.

**Comment by daijiaoshou** [comment]
How about the accurate of the measurement?




------------------

Best Regards
代凯

电话：13224307507
电子邮件：daikai@jluracing.com

 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by xieqi1** [comment]
Hello ! @daijiaoshou what the measurement refer to ? if imu, it come from epson,which cost about 3000RMB,and I think its accuracy maybe enough for mapping. if lidar its Velodyne16.

**Comment by daijiaoshou** [comment]
It's unreasonable to drift so much in the longitudinal direction,&nbsp;


if there is any new dataset, I will share with you.

------------------

Best Regards
代凯

电话：13224307507
电子邮件：daikai@jluracing.com

 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by TixiaoShan** [comment]
One possible reason I can think of is that the IMU intrinsics may not be accurate. For example, gravity param. So a lot of errors will accumulate along that direction.

**Comment by xieqi1** [comment]
> It's unreasonable to drift so much in the longitudinal direction,&nbsp; if there is any new dataset, I will share with you.
> […](#)
> ------------------ Best Regards 代凯 电话：13224307507 电子邮件：daikai@jluracing.com &nbsp; &nbsp; &nbsp; ------------------&nbsp;Original&nbsp;------------------ From: &nbsp;"xieqi1"<notifications@github.com&gt;; Date: &nbsp;Tue, Aug 11, 2020 02:18 PM To: &nbsp;"TixiaoShan/LIO-SAM"<LIO-SAM@noreply.github.com&gt;; Cc: &nbsp;"daijiaoshou-jlu"<daikai@jluracing.com&gt;; "Mention"<mention@noreply.github.com&gt;; Subject: &nbsp;Re: [TixiaoShan/LIO-SAM] Suffer from altitude drift (#64) &nbsp; Hello ! @daijiaoshou what the measurement refer to ? if imu, it come from epson,which cost about 3000RMB,and I think its accuracy maybe enough for mapping. if lidar its Velodyne16. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

OK ! Thank you !

**Comment by xieqi1** [comment]
Hi, @TixiaoShan  I think the initial guess of position from imu maybe not accuarcy, so I changed the imu part instead of fusion with wheel speed using kalman filter while not using acc from imu, however, it doesn't improve the perfomance. Then I set the initial delta altitude be 0 each frame, and unfortunately its altitude still suffer from huge drift.
So, does the drift come from lidar matching ?

**Comment by TixiaoShan** [comment]
> Hi, @TixiaoShan I think the initial guess of position from imu maybe not accuarcy, so I changed the imu part instead of fusion with wheel speed using kalman filter while not using acc from imu, however, it doesn't improve the perfomance. Then I set the initial delta altitude be 0 each frame, and unfortunately its altitude still suffer from huge drift.
> So, does the drift come from lidar matching ?

Yes, lidar scam-matching has drift all the time, the magnitude of this drift is small.

**Comment by xieqi1** [comment]
@TixiaoShan So, I think this drift maybe unreasonable, and any other ways I can have a try ?

**Comment by TixiaoShan** [comment]
> @TixiaoShan So, I think this drift maybe unreasonable, and any other ways I can have a try ?

Did you try to calibrate your IMU to get more accurate intrinsics? Those parameters may effect the results too.

**Comment by xieqi1** [comment]
@TixiaoShan Sure, I agree accuracy of intrinsics is important, and some methods to calibrate  the intrinsics between lidar and imu?I don't find the valid ways to calibrate.
Thank you !

**Comment by TixiaoShan** [comment]
[You can use this package to get the intrinsics of IMU.](https://github.com/gaowenliang/imu_utils)

**Comment by xieqi1** [comment]
@TixiaoShan Thank you ! Maybe I have found the reason that cause the unreasonable result. The extrinsic parameters between lidar and baselink maybe wrong, and I will try to calibrate this param.
Thanks for your time !
