### ISSUE TITLE
[Question] Loop closure + no GPS

### ISSUE THREAD

**Issue by Seanmatthews** [TixiaoShan/LIO-SAM#65]
Is it possible, and reasonable, to use LIO-SAM with loop closure but without GPS? This is not one of the cases covered in the result listed in Table II of the paper. In your experience, what's the quality of the result I should expect when running LIO-SAM with this configuration?

**Comment by TixiaoShan** [comment]
```Is it possible, and reasonable, to use LIO-SAM with loop closure but without GPS?```
Yes, that's how I use it most of the time. As long as the environment is feature-rich, the system performs very well. [Here is a video that only uses loop closure and no GPS.](https://youtu.be/OF_wOgPTNhs)
