### ISSUE TITLE
Dataset server has download limits

### ISSUE THREAD

**Issue by Seanmatthews** [TixiaoShan/LIO-SAM#66]
Consider an additional or alternate server location, with unrestricted downloads, for the sample datasets. I am not able to download them due to the file being "downloaded too many times".

**Comment by Seanmatthews** [comment]
Also, on at least the Park dataset, it seems I do not have the correct access to download the file.

**Comment by TixiaoShan** [comment]
Do you have any suggestions? Google drive space is the only subscription I have.

**Comment by Seanmatthews** [comment]
Unfortunately, I don't have any great solutions. Mega.nz offers 50GB of free storage, but either file size or download size might be limited to 5GB. Amazon AWS offers free tier S3 storage of 5GB with an allowance of 20000 GET requests. Either one of these may wok well for the smaller datasets at least.

**Comment by TixiaoShan** [comment]
@Seanmatthews 
I have added a few Dropbox download links for some of the samples. The rest of the bags that are not added because they are too large.

**Comment by Seanmatthews** [comment]
I think it's reasonable to ensure that at least one dataset, which works with default settings, is available. Thank you.
