### ISSUE TITLE
in Narrow and long corridor, lost position

### ISSUE THREAD

**Issue by smwgf** [TixiaoShan/LIO-SAM#68]
Hi !
I run LIO-SAM on my own dataset, of which path include a Narrow and long corridor that is about 60m long. that corridor width is about 2m. when I enter that corridor, odometry position get lost.
my H/W use only lidar(velodyne VLP16) and imu(Microstrain 3DM-GX5-25).
could you have any solution?

**Comment by TixiaoShan** [comment]
The long corridor is degraded environment for lidar odometry, so it won't work. [You need lidar-visual-inertial odometry for such an environment.](https://www.ri.cmu.edu/wp-content/uploads/2019/01/JFR_2018.pdf)
