### ISSUE TITLE
Help with unknown issue

### ISSUE THREAD

**Issue by Murcamil** [TixiaoShan/LIO-SAM#70]
I have an unknown issue and the position is lost as soon as translations or rotations are applied.
I can successfully run the datasets provided and my environment looks like it is set up correctly. 
I am using an VLP16 sensor, spinning at 20Hz (config updated for 20Hz),  with the latest driver.
I am using an Xsense MTI 630 and I think it is aligned correctly according to the ROS REP105 (with my config). According to the LIO-SAM IMU debug video all is correct.
The testing area is the inside of a 6x6m office.
I have made a video [here](https://youtu.be/ySQrZB2nQW8) and uploaded the bag [here](https://drive.google.com/drive/folders/1cy-1Ru4R-ZbyrxIk42SODm26JuHTjQWo?usp=sharing).
The movement from the video/bag in mostly rotations.
Thank you!

**Comment by TixiaoShan** [comment]
Most indoor environments are degraded. Can you run a test outdoors?
