### ISSUE TITLE
[Question] Why 6 regions?

### ISSUE THREAD

**Issue by Seanmatthews** [TixiaoShan/LIO-SAM#72]
https://github.com/TixiaoShan/LIO-SAM/blob/master/src/featureExtraction.cpp#L153

I'm curious why, in the above code, you've chosen to split each scan into six regions. Does it lower total processing time when sorting a smaller list of smoothness values? Or does it have to do with the detection of edges and surfaces?

**Comment by TixiaoShan** [comment]
Using multiple regions helps extract features more evenly. Giving an extreme example, imagine there is only one region, all the extracted features are located in the sensor front -10 degree ~ +10 degree, then the pose estimation won't be constrained very well.
