### ISSUE TITLE
When I test with other datasets, the system shakes. Do you know what caused it?

### ISSUE THREAD

**Issue by qian5683** [TixiaoShan/LIO-SAM#73]
The point cloud in my dataset that I use doesn't have a timestamp. Is that the cause of the bug?

**Comment by qian5683** [comment]
And the "/lio_sam/imu/path" looks like a wavy line

**Comment by TixiaoShan** [comment]
It sounds like the extrinsics of IMU is not configured properly. When the pose prediction of IMU contradicts with the pose estimation of lidar odometry, the sensor moves jerkily.
