### ISSUE TITLE
Some questions about imuConverter

### ISSUE THREAD

**Issue by qian5683** [TixiaoShan/LIO-SAM#75]
In the function，q_final = q_from * extQRPY; why the RPY is different from acc ang gyr？ And isn't it supposed to be q_final = q_from* (extQRPY).transpose  ? Maybe I misunderstood something, please let me know.

**Comment by qian5683** [comment]
> In the function，acc = extRot * acc; gyr = extRot * gyr;q_final = q_from * extQRPY; why the RPY is different from acc ang gyr？ Isn't it supposed to be q_final = extQRPY *q_from ? Maybe I misunderstood something

**Comment by Pallav1299** [comment]
@qian5683,  " * " operator has a different definition in Eigen. If that is what you are pointing to.

**Comment by hanhaoguang** [comment]
> 

我也是这么理解的，请问问题解决了吗
