### ISSUE TITLE
Scan-matching fails leading to unrestricted jumps in pose 

### ISSUE THREAD

**Issue by Pallav1299** [TixiaoShan/LIO-SAM#76]
I witnessed unrestricted jumps in the optimized trajectory when scan-matching fails at some point. The poseCovariance doesn't grow with jumps, while the imuPreintegration gets reset and the GPS factors are not added. Is this the expected behavior? 
![Screenshot 2020-08-18 12:10:57](https://user-images.githubusercontent.com/32015105/90479242-f9533c80-e14b-11ea-9580-41523a01697f.png)

Can someone please help me with the following questions:
1. Shouldn't the jumps be restricted using GPS?
2. Shouldn't the poseCovariance increase when scan-matching fails and leads to jumps in the estimated poses? How is the poseCovariance actually calculated in GTSAM?
3. Can LIO-SAM be used in highway like environments which have homogeneous features? How robust is the GPS optimization in LIO-SAM for highway like environments?

**Comment by chxyfishge** [comment]
![选区_393](https://user-images.githubusercontent.com/25274979/91025436-f95faa80-e62b-11ea-818c-32c8088e301c.png)
Same as you!
When I put the lidar+imu where they are and do not move, trajectory and point cloud should stay still, but actually it slowly rotating and shaking, finally imuPreintegration gets reset.

**Comment by chxyfishge** [comment]
this issue maybe same as #62

**Comment by TixiaoShan** [comment]
That's very strange. What kind of hardware are you using?

**Comment by TixiaoShan** [comment]
> That's very strange. What kind of hardware are you using?

Also, could you attach a picture that shows a single scan where LIO-SAM starts to drift? I want to have a better understanding of the scene.
