### ISSUE TITLE
How to  use LIO-SAM for solid state lidar? Such as Leishen CH32.

### ISSUE THREAD

**Issue by bage131** [TixiaoShan/LIO-SAM#78]
Does LIO-SAM only be used on mechanical lidars? There is a very serious drift,and sometimes  it goes around in circles, when I used LIO-SAM for solid state lidar rosbag.Could you give me some advice?Thank you.

**Comment by TixiaoShan** [comment]
Currently, LIO-SAM doesn't support solid-state lidar. You may need to modify "imageProjection.cpp" and "featureExtraction.cpp" to make it compatible with your hardware. I think a good start for this would be [LIVOX-LOAM](https://github.com/hku-mars/loam_livox).

**Comment by bage131** [comment]
> Currently, LIO-SAM doesn't support solid-state lidar. You may need to modify "imageProjection.cpp" and "featureExtraction.cpp" to make it compatible with your hardware. I think a good start for this would be [LIVOX-LOAM](https://github.com/hku-mars/loam_livox).
-------------------------------------------------------
Thank you very much.

**Comment by youssefattia98** [comment]
Have anyone done this at some point?
