### ISSUE TITLE
Use the gps fix data in the big_loop.bag data, the first correction occurs drift

### ISSUE THREAD

**Issue by hunkyu** [TixiaoShan/LIO-SAM#8]
Use the gps fix data in the big_loop.bag data, the first correction occurs drift
![2020-07-05 08-44-05 的屏幕截图](https://user-images.githubusercontent.com/20533364/86523228-ea664280-be9b-11ea-8bd2-d3bffffa2504.png)

**Comment by caoyifeng001** [comment]
i have same problem

**Comment by TixiaoShan** [comment]
@hunkyu 
@caoyifeng001 
That;s normal. The map visualized here is not a real map. It's just velodyne points stacked together (rviz timeout). If you visualize Map (local) or Map (global), you will see the map is correct.
