### ISSUE TITLE
bad run result with demo walking rosbag data

### ISSUE THREAD

**Issue by 123dbl** [TixiaoShan/LIO-SAM#83]
![image](https://user-images.githubusercontent.com/31713914/91514595-ba767100-e919-11ea-997c-6bbfafd1fa0b.png)
![image](https://user-images.githubusercontent.com/31713914/91514607-c104e880-e919-11ea-95dc-0252be068bbb.png)

**Comment by TixiaoShan** [comment]
I just tested using the Garden dataset. The results are consistent. Are you using the correct configuration mentioned in the README?
