### ISSUE TITLE
Half of points in the ouster dataset have range < 1m?

### ISSUE THREAD

**Issue by BritskNguyen** [TixiaoShan/LIO-SAM#88]
Dear author,

Thank you for sharing your code and your datasets. Everything works well as you provide. However I find something odd in the ouster dataset.

Basically I added some variables to the cloud hander in imageProjection.cpp as follows:
![checks](https://user-images.githubusercontent.com/13504903/91635795-f26ed880-ea2d-11ea-9e6d-47764a4502fd.png)

When I print out the counts, it seems like half of the ouster points are below 1m.

![short_range](https://user-images.githubusercontent.com/13504903/91635750-a15ee480-ea2d-11ea-9b94-4ec4a2665b38.png)

Is it a normal behaviour of the ouster sensor? I notice that the Velodyne dataset has only a small percentage of submeter points.

Regards

**Comment by TixiaoShan** [comment]
That's normal for Ouster lidar. If you take a closer look at the ground points from the Ouster lidar dataset, you will find it doesn't have many returns from the ground. These points with no returns are filled with point (0,0,0).
