### ISSUE TITLE
runtime synchronization error

### ISSUE THREAD

**Issue by YushengWHU** [TixiaoShan/LIO-SAM#90]
I recorded an ouster os1-64 bag with external IMU, and everything works fine for Lego_LOAM, but when I turn to LIO-SAM, nothing showed in rviz, thus I checked the code and found the synchronization error below.
The first figure is from myself recored bag, which indicates the time is the internal ouster time, while the second is from your dataset, where both timestamp is ros time.
![Screenshot from 2020-08-30 11-16-16](https://user-images.githubusercontent.com/40022787/91650730-c434db80-eab5-11ea-8f27-f137c4eb5368.png)
![Screenshot from 2020-08-30 11-17-08](https://user-images.githubusercontent.com/40022787/91650732-c5fe9f00-eab5-11ea-9101-05a59d997507.png)

**Comment by TixiaoShan** [comment]
There is about 50 years time difference between your IMU and Ouster data. Have you tried to sync your Ouster lidar time with the current time?

**Comment by zwmisdu** [comment]
> I recorded an ouster os1-64 bag with external IMU, and everything works fine for Lego_LOAM, but when I turn to LIO-SAM, nothing showed in rviz, thus I checked the code and found the synchronization error below.
> The first figure is from myself recored bag, which indicates the time is the internal ouster time, while the second is from your dataset, where both timestamp is ros time.
> ![Screenshot from 2020-08-30 11-16-16](https://user-images.githubusercontent.com/40022787/91650730-c434db80-eab5-11ea-8f27-f137c4eb5368.png)
> ![Screenshot from 2020-08-30 11-17-08](https://user-images.githubusercontent.com/40022787/91650732-c5fe9f00-eab5-11ea-9101-05a59d997507.png)

I have the same problem and handled.But I could not download the ouster dataset because the wall.Are you from China too?

**Comment by YushengWHU** [comment]
> > I recorded an ouster os1-64 bag with external IMU, and everything works fine for Lego_LOAM, but when I turn to LIO-SAM, nothing showed in rviz, thus I checked the code and found the synchronization error below.
> > The first figure is from myself recored bag, which indicates the time is the internal ouster time, while the second is from your dataset, where both timestamp is ros time.
> > ![Screenshot from 2020-08-30 11-16-16](https://user-images.githubusercontent.com/40022787/91650730-c434db80-eab5-11ea-8f27-f137c4eb5368.png)
> > ![Screenshot from 2020-08-30 11-17-08](https://user-images.githubusercontent.com/40022787/91650732-c5fe9f00-eab5-11ea-9101-05a59d997507.png)
> 
> I have the same problem and handled.But I could not download the ouster dataset because the wall.Are you from China too?

留个邮箱我发给你老铁

**Comment by YushengWHU** [comment]
> There is about 50 years time difference between your IMU and Ouster data. Have you tried to sync your Ouster lidar time with the current time?

We

> > I recorded an ouster os1-64 bag with external IMU, and everything works fine for Lego_LOAM, but when I turn to LIO-SAM, nothing showed in rviz, thus I checked the code and found the synchronization error below.
> > The first figure is from myself recored bag, which indicates the time is the internal ouster time, while the second is from your dataset, where both timestamp is ros time.
> > ![Screenshot from 2020-08-30 11-16-16](https://user-images.githubusercontent.com/40022787/91650730-c434db80-eab5-11ea-8f27-f137c4eb5368.png)
> > ![Screenshot from 2020-08-30 11-17-08](https://user-images.githubusercontent.com/40022787/91650732-c5fe9f00-eab5-11ea-9101-05a59d997507.png)
> 
> I have the same problem and handled.But I could not download the ouster dataset because the wall.Are you from China too?

哦对，你怎么弄啊，是录bag的时候搞，还是用sim time？

**Comment by YushengWHU** [comment]
> > I recorded an ouster os1-64 bag with external IMU, and everything works fine for Lego_LOAM, but when I turn to LIO-SAM, nothing showed in rviz, thus I checked the code and found the synchronization error below.
> > The first figure is from myself recored bag, which indicates the time is the internal ouster time, while the second is from your dataset, where both timestamp is ros time.
> > ![Screenshot from 2020-08-30 11-16-16](https://user-images.githubusercontent.com/40022787/91650730-c434db80-eab5-11ea-8f27-f137c4eb5368.png)
> > ![Screenshot from 2020-08-30 11-17-08](https://user-images.githubusercontent.com/40022787/91650732-c5fe9f00-eab5-11ea-9101-05a59d997507.png)
> 
> I have the same problem and handled.But I could not download the ouster dataset because the wall.Are you from China too?

哦对，你这个问题是怎么解决的哈~也是全弄sim time还是录bag时候搞？

**Comment by zwmisdu** [comment]
> > > I recorded an ouster os1-64 bag with external IMU, and everything works fine for Lego_LOAM, but when I turn to LIO-SAM, nothing showed in rviz, thus I checked the code and found the synchronization error below.
> > > The first figure is from myself recored bag, which indicates the time is the internal ouster time, while the second is from your dataset, where both timestamp is ros time.
> > > ![Screenshot from 2020-08-30 11-16-16](https://user-images.githubusercontent.com/40022787/91650730-c434db80-eab5-11ea-8f27-f137c4eb5368.png)
> > > ![Screenshot from 2020-08-30 11-17-08](https://user-images.githubusercontent.com/40022787/91650732-c5fe9f00-eab5-11ea-9101-05a59d997507.png)
> > 
> > 
> > I have the same problem and handled.But I could not download the ouster dataset because the wall.Are you from China too?
> 
> 留个邮箱我发给你老铁

zwmjust@126.com 邮箱留个微信吧 交流一下
