### ISSUE TITLE
How can I set the imu params?

### ISSUE THREAD

**Issue by ONMEKEEP** [TixiaoShan/LIO-SAM#91]
Hello. Thank you for your outstanding work. I'm a beginner. I have a question about imu settings. 
How can I set these params for my own imu?  Do you have some advice? My imu is oxts4003.
![image](https://user-images.githubusercontent.com/37762029/91679939-3ec82e80-eb7c-11ea-87a0-2b2b47a63d14.png)

Hope your reply! Thanks.

**Comment by TixiaoShan** [comment]
You can use this package to get the params.
https://github.com/gaowenliang/imu_utils

**Comment by ONMEKEEP** [comment]
> You can use this package to get the params.
> https://github.com/gaowenliang/imu_utils

OK. Thank you very much. I will try it.
