### ISSUE TITLE
Question about deskewing 

### ISSUE THREAD

**Issue by ChangkiSung** [TixiaoShan/LIO-SAM#93]
Hi,

I am using the os1-64 Lidar sensor. I got a question about the effect of the deskewing process.

Does this process affect to the result a lot?

I have compared between the raw pointclouds and deskewed pointcloud on rviz. It looks same...

Thank you.

**Comment by TixiaoShan** [comment]
If you move and rotate your sensor very fast, say rotate it 360 degrees in one second, you will see there is a big difference.
