### ISSUE TITLE
I hawe a livox-mid 40 ,how implement demo

### ISSUE THREAD

**Issue by jiaozhuliu** [TixiaoShan/LIO-SAM#99]
thankyou

**Comment by YushengWHU** [comment]
搞不了的，你用loam_livox好了

**Comment by GigaFlopsis** [comment]
I changed something. For me it works on livox avia and external imu  
https://github.com/Innopolis-UAV-Team/LIO-SAM/blob/livox/launch/livox.launch

**Comment by Liming-Cheng** [comment]
@GigaFlopsis 
hello, how do you change the timestamp of livox pointcloud to ros::time() format ? Can you give me some suggestion? Thank you very much!
